### ISSUE TITLE
Sound Mixer: Setting a column volume does not work as expected

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1481]
GM-201

While writing up and testing the sound mixer, I've found what I would consider to be an error. When working with a REAL mixer, if you change the master volume it affects the other volumes in a relative fashion. Ie: if a sound is at 75% volume and you set the master volume to 50% the final sound will have a volume of 37.5%. Currently the master volume for a column simply sets the final volume for each sound resource to be the same.

This GREATLY reduces the functionality of the sound mixer, because ideally you'd be able to tweak the volumes on each sound in one column then compare it to the sounds in another and then use the master column volume to raise/lower all sounds relative value to bring everything in line. As it currently stands, the column volume control is pretty much useless.

Make the sound mixer column volume slider work like an actual physical mixer by adjusting the sound volume relative to the original sound volume setting.

**Comment by AeternumGames** [comment]
That would be really great! 
I just want to confirm again what iampremo said: This would be a logical way to go, because that's how physical mixers work. Basically, the sounds should have their own volume settings, as it is now. (Which essentially means that each sound has its own channel) These are then "routed" into an audio group "bus channel" which sums all these sounds and then sets the volume for the whole group, without changing the settings of the individual sounds.

**Comment by toby-yoyo** [comment]
- The column volume slider will now scale the volume of the assets in the column.
- Sound mixer volume sliders should now audibly update as they are moved.

**Comment by YYBartT** [comment]
Documented the changes as listed above on the Sound Mixer manual page.

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1300.0.715  Runtime v2024.1300.0.728.
