### ISSUE TITLE
dbg_xxx (slider, checkbox, color) not rendering

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#1547]
### Description
In latest beta dbg_xxx stopped to work (those were working in previous 2-3 betas since they were introduced).

Also, `dbg_view` 3rd and 4th param (x,y) shows that it expects `Unset` instead of `Real`.

### Steps To Reproduce
Run attached project - most of controls will be missing from debug view / sections.

[da8ba583-834b-4334-9fed-aafd8d94b657](https://api.gamemaker.io/api/github/downloads/da8ba583-834b-4334-9fed-aafd8d94b657)

**Comment by rwkay** [comment]
Fixed (see above)

**Comment by YYDan** [comment]
"Also, dbg_view 3rd and 4th param (x,y) shows that it expects Unset instead of Real."

To be clear, this bit is not part of the linked fix and so will not be fixed in Beta 7; however, we already have it reported in our internal repo already, so should be fixed soon. (width and height are affected also.)

**Comment by gnysek** [comment]
Did `dbg_xxx` fixes are in `IDE v2023.800.0.404 Beta Runtime v2023.800.0.425` ? As I see no difference:

![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/bcc6770a-843f-4134-93d9-d59a9c24521d)
