### ISSUE TITLE
Script files are being removed once I've open my project

### ISSUE THREAD

**Issue by Koyan61** [YoYoGames/GameMaker-Bugs#1615]
### Description
Whenever a new update comes or a beta version, some of my script files are being removed for no apparent reason, it says "couldn't find the file" or something like that and removes it. Weird thing is even github doesn't recognize the file as removed so I can't reach it. IT'S A BIG PROBLEM. I've lost 3 days of progress because of this. This bug is been here for more than 2 years now.

### Steps To Reproduce
It just random whenever I open a new version project it just deletes the files sometimes my notes too, it just deletes text based files. I do happened to notice however, it's always a colored file, whenever I put them a color tag, they were to be ones who got removed.

[93cde148-f902-4ea7-bf87-210e9cac96a7](https://api.gamemaker.io/api/github/downloads/93cde148-f902-4ea7-bf87-210e9cac96a7)

**Comment by YYDan** [comment]
Please move your projects out of OneDrive and then you will be fine:

`C:\Users\...\OneDrive\...\GameMakerStudio2\Tranel\Tranel.yyp`

There's nothing we can do about OneDrive syncing/locking/replacing your files - accordingly, our permissions and setup guides have said to not use OneDrive/Dropbox, etc., for a very long time.

Be aware that as of the 2024.4 release we have changed GM already so that it will not use My Documents by default and so users should not find themselves unknowingly putting their source code into OneDrive. However, as you're already storing your projects there, you will need to move any existing ones yourself.
