### ISSUE TITLE
dont run windows gms2vm

### ISSUE THREAD

**Issue by dev816** [YoYoGames/GameMaker-Bugs#1617]
### Description
in compile succes i see that, and thats all
C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.8.0.145/windows/x64/Runner.exe exited with non-zero status (-1073741819)

### Steps To Reproduce
I start the game, no launch and immediately an error, everything was ok before

[f3c232fe-9224-46f8-b366-7db6b10585ce](https://api.gamemaker.io/api/github/downloads/f3c232fe-9224-46f8-b366-7db6b10585ce)

**Comment by jackerley** [comment]
We would need a project in order to be able to investigate this

**Comment by DAndrewBox** [comment]
@jackerley This is a recurrent error since last update.
[I made a post in the forums](https://forum.gamemaker.io/index.php?threads/2023-8-release-thread.105622/page-2#post-636716), is almost impossible to get a small project that make this work, but it seems it has to be with the conversion from last version to newer version runtime.

Have been investigating about, and noticed that even making a blank project show these errors during build/run on windows GMS2 VM

`
Found Project Format 2
(42,2): GMSC Error: Field 'templateType' missing in YoYoStudio.Resources.GMProject.
+++ ORIGINAL SERIALISATION SUCCESSFUL LOAD AND LINK TIME: 11.5775ms
Loaded Project: __yy_sdf_shader
finished.
Found Project Format 2
(43,2): GMSC Error: Field 'templateType' missing in YoYoStudio.Resources.GMProject.
+++ ORIGINAL SERIALISATION SUCCESSFUL LOAD AND LINK TIME: 4.7588ms
Loaded Project: __yy_sdf_effect_shader
finished.
Found Project Format 2
(43,2): GMSC Error: Field 'templateType' missing in YoYoStudio.Resources.GMProject.
+++ ORIGINAL SERIALISATION SUCCESSFUL LOAD AND LINK TIME: 7.5381ms
Loaded Project: __yy_sdf_blur_shader
finished.
Found Project Format 2
(45,2): GMSC Error: Field 'templateType' missing in YoYoStudio.Resources.GMProject.
+++ ORIGINAL SERIALISATION SUCCESSFUL LOAD AND LINK TIME: 4.7015ms
Loaded Project: _filter_large_blur
finished.
Found Project Format 2
(40,2): GMSC Error: Field 'templateType' missing in YoYoStudio.Resources.GMProject.
+++ ORIGINAL SERIALISATION SUCCESSFUL LOAD AND LINK TIME: 27.227ms
Loaded Project: GMPresetParticles
finished.
Release build
`

And when silently crashes (it's random, it could be 30 seconds, or 10 minutes into the game), this is the output:
`
C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2023.8.0.145/windows/x64/Runner.exe exited with non-zero status (-1073741819)
`

I don't know if this works, but this is the ´ui.log´ file after silently crash.

[ui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/12564603/ui.log)
