### ISSUE TITLE
Building Projects: [iOS] Xcode 15 causes fails due to "dyldbootstrap::start"

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#1770]
### Description

When attempting to run a project on iOS with Xcode 15 installed it will fail to start, the callstack will report dyldbootstrap::start

### Steps To Reproduce

1. Start GameMaker
2. Run target for iOS with suppress build enabled
3. Attempt to run game on iOS device from Xcode project
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

iOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
In order to workaround this problem you can add -ld64 to Other Linker Flags under Build Settings. This will allow your game to launch on device

**Comment by scott-dunbar** [comment]
[ios-ld64.txt](https://github.com/YoYoGames/GameMaker-Bugs/files/12819460/ios-ld64.txt)

Im getting an issue with ld: library not found for -ld64 when building to ios using xcode 14.3.1

**Comment by YYDan** [comment]
Looks like this change might be an Xcode 15 bug and one for Apple to fix (judging by their release notes, this might be coming soon).

The change on our side is no good, though, as it breaks older Xcode versions, so reopening.

**Comment by YYDan** [comment]
Another fix has been added now, so the new flag is only added if the build detects Xcode 15+ is being used.

**Comment by YYDan** [comment]
All fine on 2 Macs in Xcode 14 and 15 and when using 2023.8.2. Closing.

**Comment by RamiroCastillo** [comment]
Dear @YYDan

I told you that I have a similar problem with my application and your answer helped me a lot by adding the flag -Id64 in other liker flag but as mentioned, this solution means that I can no longer run it in xcode 14 and in the following comment I make:

> Another fix has been added now, so the new flag is only added if the build detects Xcode 15+ is being used.

I indicate that it could be solved and it can now be executed in both xcode, I tell you that I have the same problem, I investigated and tried to put the conditionals for it but without success, could you please help me or give me some clues so that I can determine what configurations should be made so it can run on both xcode 14 and 15 please
