### ISSUE TITLE
Preferences: Text Editor > "Code Completion Delay" value is always set to 150 by Feather whenever you open a project

### ISSUE THREAD

**Issue by jarrrodnb** [YoYoGames/GameMaker-Bugs#1823]
### Description

Preferences > Text Editor > "Code Completion Delay" is always unexpectedly set to 150 by Feather whenever you open a project, overriding whatever value you set there.

### Expected Change

The user's Preferences values are not amended by Feather.

### Steps To Reproduce

1. Start GameMaker (logged in/out doesn't matter) and reach the Start Page
2. Open Preferences and set "Code Completion Delay" to any custom value, click the OK button
3. Restart GameMaker and open Preferences again, confirm your value is still used, close Preferences
4. Open any project
5. Now open Preferences again and observe the value is set to specifically 150.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Suspect this is because of this unexpected prompt you likely saw (but is not part of your steps/screenshot):

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/a4667643-f8f9-4861-a931-4d4c3ac935fd)

GameMaker should have saved your change (as it certainly all works correctly for me right now), but obviously (as that dialog told you) you're no longer logged-in on the next startup and will need to log back in before you see your change.

If you were to change the value again when logged-out you will see that is saved fine also - and won't overwrite the new value whenever you do log back in - e.g:

- Signed-in, I change it from 150 to 600. Click Apply, get told I will be signed-out and GM needs to restart, OK.
- GM restarts and so now I am logged out - the Preference is the default 150 again because now I am a different user on the PC.
- I change 150 to 400 in the guest account, apply and okay, restart GameMaker.
- Because I am still a guest, now I can see the 400 was saved.
- I now log in and my original user's Preferences are loaded.
- Now Preferences says 600, as I had intended.
- From now on, when logged-in I will get 600 and when I log out it will be 400.

That's all the expected behaviour and works correctly in 2023.8.1, so technically there is no bug here.

However, leaving this one open just now, as I am not sure that dialog saying you need to restart should be the case nowadays.

**Comment by YYDan** [comment]
Note also that the Restore Defaults button shows that the default for that delay is 500, not 150 - so I am not really sure why a guest user is set to 150 (another part of why I am leaving this one open for further investigation).

**Comment by jarrrodnb** [comment]
Hey Dan,
Is there any reason that this only applies to "Code Completion delay"?
Because every other preference in every tab, even "Syntax Checking delay" directly above it works correctly.
It's only Code Completion delay.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/109584258/0db9953a-edb0-4d50-9700-6cfe6506e174)

I just did a quick increment test, increased both those values by 1 (2001 & 151ms) applied, clicked OK then closed Gamemaker.
I reopened and took that screenshot.

**Comment by stuckie** [comment]
There are a couple of oddities here.
By default, the value is 500.
The 150 is actually coming from Feather when a project is loaded, and is reset on the project being closed. ( so you should be able to verify this by changing the value from the start screen without a project loaded, and restarting, and it should keep the value. )
This is the likely culprit, and we'll get this fixed.

The SSO logout dialogue should only appear if the GX Environment has changed ( eg: between Production and Sandbox ) so if that is appearing at other times, that too is a bug; albeit separate to what's going on here.

**Comment by YYDan** [comment]
Yeah, as Steven says - my testing above was only on the Start Page and restarting GM. That all shows the Preferences are saved/loaded correctly. However, what I failed to notice until Steven told me directly was that opening any project would set it to the mystery 150...

Your test above, you must have either been in a project at the time, or you actually reopened your project before you opened Preferences again to check the result and make that screengrab.

**Comment by jarrrodnb** [comment]
Ahh fair enough, when I open gamemaker I always instinctively click into my project before anything else. I didn't even think to mention that.
Glad it's all cleared up & figured out! :D

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.420  Runtime v2023.1100.0.438
