### ISSUE TITLE
In-Game: skeleton_animation_is_finished() fails to return 'true' at certain combinations of frame rates and animation durations

### ISSUE THREAD

**Issue by BscotchSeth** [YoYoGames/GameMaker-Bugs#1895]
### Description

Spine animations break at certain frame rates, because skeleton_animation_is_finished() won't properly return 'true' sometimes.

Included is a sample project. Explainer:

It shows a player character that moves through 3 animations: "idle", "run_transition", and "run".
It starts at 30 fps, and pressing "up" or "down" will change the frame rate.

The animation sequence properly plays through all animations at 25 fps and above, and at 10-11 fps.
When fps is anywhere from 12-24, the second animation ("run_transition") plays, but skeleton_animation_is_finished() doesn't return 'true' when it gets to the end, so we can't progress to the next frame.

[SpineLowFPS.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12873577/SpineLowFPS.zip)

**_Edit: Updated on March 1, 2024 with a new test project that shows the issue is still present when using `draw_sprite_ext()`. The new test project can be found [here](https://github.com/YoYoGames/GameMaker-Bugs/files/14451692/SpineLowFPS2024_draw_ext.zip)._**

### Expected Change

skeleton_animation_is_finished() should always return true when the animation gets to the end.

### Steps To Reproduce

1. Load the sample project.
2. Run the sample project.
3. Press the down arrow to lower the FPS, and watch as the animation stops working at 12-24 fps.
4. Press the 'up' arrow to raise the FPS, and see the animation sequence work at any fps at 25 or above.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, Android, iOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yoyo-danielc** [comment]
Fixes are on the 2024.02 branch now (HTML5 and native runtimes)

For QA:

We've had to fundamentally change how we handle the animation timing to correctly deal with this, on the plus side it should be more robust against this type of problem in the future. I've done some cursory testing with the sample from this bug and also a few previous Spine issues, but this really wants putting through the wringer, in particular:

- Projects which fiddle with the animation speed (e.g. via image_speed).
- Projects which change the game speed.
- Projects which directly control the animation time (by setting image_index) rather than having GM advance it automatically.
- Projects using non-Spine animated sprites (only cursory testing should be necessary here).
- Projects using Spine collisions (via sprite_index and mask_index).

**Comment by BscotchSeth** [comment]
While you're in the guts of the Spine code, we also have this issue from a while back, where using skeleton_animation_set_frame() causes spine events to trigger nonstop:

https://github.com/YoYoGames/GameMaker-Bugs/issues/1798

**Comment by alicemoretti** [comment]
The project attached fails to build on IDE v2024.200.0.451  Runtime v2024.200.0.461 when fetching Spine Sprites Info (same as #1798 ) . 

Reopening the bug. Thank you.

**Comment by yoyo-danielc** [comment]
The crash was an unrelated bug deep inside the `json_stringify()` call - fixed by af8c4146b67f23d30db9191f928ce592d15b744a.

**Comment by YYDan** [comment]
Will take a look - thanks!

**Comment by BscotchSeth** [comment]
We're finding some inconsistencies with it -- will get an updated test project put together.

**Comment by BscotchSeth** [comment]
ABORT! I think this is fine; the issue we are now seeing relates to how we've connected the animation to game physics at low frame rates.

**Comment by YYDan** [comment]
Ahh, glad you figured it out and that all is well with this one. Thanks for letting us know!

**Comment by BscotchSeth** [comment]
Unabort! Turns out it WASN'T our code! If you use `draw_sprite_ext()` instead of `draw_self()`, the issue persists. Shi is attaching a replication test project.

**Comment by shichen85** [comment]
[SpineLowFPS2024_draw_ext.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14451692/SpineLowFPS2024_draw_ext.zip)

Here is the updated project.

**Comment by yoyo-danielc** [comment]
The issue observed when using `draw_sprite_ext()` is technically a different bug, so I've moved that to #4974 and will close this one again :p

**Comment by jackerley** [comment]
GMRT - character does not display properly, looks like only 1 spine part is displaying rather than full character. Unable to verify if this specific issue occurs.
GMS2 runtime:
<img width="817" height="489" alt="Image" src="https://github.com/user-attachments/assets/2331a15b-74a1-4fa3-9c7f-3902dab55225" />
GMRT
<img width="1013" height="503" alt="Image" src="https://github.com/user-attachments/assets/5daa7afc-a7c9-4221-8b0b-1d33053a5933" />
