### ISSUE TITLE
Feather: Tooltips are not shown in the Code Editor in 2023.110 Beta 1

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#2037]
### Description

In the new beta(Beta IDE v2023.1100.0.425 Beta Runtime v2023.1100.0.439) if you try to use the tooltip functionality it will not work and not show anything

https://mega.nz/#P!AgEARFGAoAmvOki1wzX2WZyRyTWmZkuVAo8JICa3O8pHSMuNzZTLLNZ_Wl3Rat_LRs6AyX84_vxeW_dKEAd_CBZsvgsK04CWTTG9EGhETdsCiG1_6ljxdPORZJcPUq9OqmBVezkI8-c

### Expected Change

Feather tooltip is working again

### Steps To Reproduce

1. Start GameMaker
2. hover above a variable/method/script
3. See the issue

### How reliably can you recreate this issue using your steps above?

Most Times

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by zreedy** [comment]
I suspect this bug is fixed now. Waiting for feedback from user on latest Beta.
Root issue was that Feather failed to initialize due to:

- Array index overflow due to suffixes not being accounted for (off by 1 in an if statement)
- GM2017 running even when disabled due to Function entry point (was disabled in Script entry point)
