### ISSUE TITLE
SSH connection error (permission denied)

### ISSUE THREAD

**Issue by Vlazel** [YoYoGames/GameMaker-Bugs#2144]
### Description

I'm using Game Maker Studio 2 version 2.3.5.589.

When compiling on iOS, I mostly did it with the Windows version of Game Maker Studio 2. But after updating MacOS to the Sonoma version, when I ran the compilation on MacOS, an error began to appear in the logs

WARNING: Unable to connect to remote client: permission (public key).

pscp C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2.3.5.458/ios/mobiledevice /tmp/mobiledevice

Renci.SshNet.Common.SshAuthenticationException: Permission denied (public key).

at Renci.SshNet.ClientAuthentication.Authenticate(IConnectionInfoInternal ConnectionInfo, ISession session)

at Renci.SshNet.ConnectionInfo.Authenticate(ISession session, IServiceFactory serviceFactory)

in Renci.SshNet.Session.Connect()

in Renci.SshNet.BaseClient.CreateAndConnectSession()

in Renci.SshNet.BaseClient.Connect()

in Igor.RealSSH.(String, String, Boolean)

in Igor.iOSBuilder.DetectDevices()

Clarification:

On MacOS all rights to remote access are given, Game maker 2 sees the connection to Mac

The latest version of runtime Game Maker Studio 2 does not have this problem, but I can't update to the latest version because I need version runtime 2.3.5.458.

### Steps To Reproduce

1. Start GameMaker
2. try detect device or build project to the Mac
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Other Release (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

macOS

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
2.3.5 is not going to know how to use current versions of Xcode (and Sonoma). We're also not able to release updates to 2.3.5.

You will need to update your GM version or go back to using the matching old versions of Xcode and macOS that you were on before.

Our Required SDKs FAQs are the places to go when you're using old versions in combination with newer tools and want to get the information on whether it should work, rather than submitting bug reports. That FAQ is in the Help menu inside GameMaker, our release notes, and indeed in the readme on the front page of this bug repository.
