### ISSUE TITLE
Path Editor: Rotate and Scale shortcuts only allow for one rotation/scale each press and don't allow free movement when held

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#2250]
### Description

When in the path editor and using the shortcuts, holding T+LMB to translate allows you to freely move the path around but when holding R+LMB or S+LMB, it only allows one rotation/scale and the user has to release the keys and press again to do another.

This happens in both beta and monthly.

IDE v2023.1100.0.444  Runtime v2023.1100.0.455

https://github.com/YoYoGames/GameMaker-Bugs/assets/131007845/712b3f61-ce68-422f-8032-7e5436da9a1e

### Expected Change

Holding R+LMB and S+LMB to rotate/scale should allow user to freely do so without needing to release and press shortcuts again

### Steps To Reproduce

1. Start GameMaker and create new project.
2. Create a path in the path editor.
3. Hold T+LMB and move the path around freely.
4. Hold R+LMB and try to rotate the path around, observe that it only allows one rotation.
5. Hold S+LMB and try to scale the path up and down, observe that it only allows you to scale once.
6. See the issue

OR

1. Start GameMaker and import [patheditorshortcuts.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13425805/patheditorshortcuts.zip)
2. Open up one of the paths and follow steps 3-5 above.
3. See the issue.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly), Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by caitlinrmcintyre** [comment]
I've tested this on Mac and it works as intended, holding the shortcut keys allow you to freely rotate/scale the paths, it seems to just be a Windows issue.

**Comment by SmithTom6304** [comment]
@caitlinrmcintyre Believe there might be a couple things happening here:
- From the on screen keyboard in the video above it looks like the shortcut keys are being momentarily released and then re-held without releasing the mouse, causing the path movement to end. This makes sense to me functionality wise, as `R`/`T`/`S` are modifier keys to `Lmb` - to open a file with `Ctrl` + `O`, `Ctrl` must be pressed first and then `O`
  - Speaking of, is releasing the `R`/`T`/`S` keys intentional in the video above? The keys seem to toggle really rapidly at points, which makes me think if theres a key issue causing the bahviour to appear strange if releasing the keys wasn't intentional
- When `T + Lmb` is pressed (but not `R` or `S`) the first node in the path is selected. This means that if `Lmb` is released, the node begins being dragged around as an individual. This certainly seems like a bug to me, as it doesn't match the behaviour of the other two keys.

**Comment by caitlinrmcintyre** [comment]
@SmithTom6304 I'm not entirely sure why the onscreen keyboard shows the keys toggling as I'm holding the shortcut keys down. For example, I'll hold R+LMB while trying to rotate but the path doesn't appear to move at all

**Comment by SmithTom6304** [comment]
@caitlinrmcintyre would you be able to try this on another keyboard (if you haven't already)? I'm wondering if it's actually being caused by the keyboard keypresses not being constant, causing the shortcut to exit early (which might explain the on-screen keyboard flickering)
(The second point above is still a bug with the IDE, so will need fixed even if there are keyboard issues happening here)

**Comment by caitlinrmcintyre** [comment]
@SmithTom6304 I've just tried using one of the logitech keyboards in office and the shortcut keys are working as expected

**Comment by SmithTom6304** [comment]
That does seem like its a keyboard issue then, rather than a bug with the IDE.
I've fixed the translate issue above:
> When T + Lmb is pressed (but not R or S) the first node in the path is selected. This means that if Lmb is released, the node begins being dragged around as an individual. This certainly seems like a bug to me, as it doesn't match the behaviour of the other two keys.

The translate tool should now behave the same as the scale and rotate tools, and stop if `T` is released.
