### ISSUE TITLE
In-Game: [non-HTML5] array_sort() will sort float values before integer numbers with the same base

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#2252]
### Description

When looking into #191 I realised that the second part of the original report still occurs in Nov23 Betas.

The sample shows that if your array contains values with floats in them, then they will appear in the results before numbers starting with the same integer number - so, in the sample attached, 2.4 appears before 2(.0):

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/9c66fa6b-8217-4369-abbd-207d9dca84ec)

Whereas HTML5 is correct:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/08e6af26-b60d-497e-bd03-eb0680428d08)

[contact-us.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13427927/contact-us.zip)

### Expected Change

2.4 comes after 2, as it does on HTML5

### Steps To Reproduce

1. Start GameMaker and import [sortest-Dan.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13427213/sortest-Dan.zip)
2. Run the attached project for Windows
3. Notice the bottom two lines are consistent, but wrong in sorting 2.4 before 2

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly), Beta (Please put the exact version number in your Description), Other Release (Please put the exact version number in your Description)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
OK so this is not strictly a bug, GML rules on subtraction between integer and real will depend on what comes first if the left hand side of the '-' if it is an integer then the right hand side value is converted to an integer as well, if the left hand side is a real then the right hand side is converted to a real. That rule is causing this behaviour, this is because the array is created with like this

```
var array3 = [
	[ 100, 1 ],
	[ 200, 2 ],
	[ 240, 2.4 ],
	[ 300, 3 ]
	];
```

The values that have no decimal component are integers (this is an optimisation to reduce the size of the code).

If the array is declared as  below then all values are now `real`

```
var array3 = [
	[ 100, 1.0 ],
	[ 200, 2.0 ],
	[ 240, 2.4 ],
	[ 300, 3.0 ]
	];
```

an alternative would be to change how the sort is done, currently the function is 

```
mymethod = function(a, b) {
	return a[1] - b[1];
}
```

if it was written like below then the comparison would always be consistent

```
mymethod = function(a, b) {
	return real(a[1]) - b[1];
}
```

The inconsistency with JavaScript is because JS does not have integer values in the same way, this leads to the array not being initialised in the same way so it sorts correctly as everything is a real.
