### ISSUE TITLE
renaming/creating/deleting assets one after another can cause freezing

### ISSUE THREAD

**Issue by jack27121** [YoYoGames/GameMaker-Bugs#2283]
### Description
if you create an asset and right after rename it before analyzing has finished it can cause gamemaker to freeze and need a restart
same if you delete multiple things and so on.

Also analyzing the project takes a pretty long time even when just renaming one single asset

[75da67ea-aef6-4d39-88f4-8e1fd0bc4dde](https://api.gamemaker.io/api/github/downloads/75da67ea-aef6-4d39-88f4-8e1fd0bc4dde)

**Comment by zreedy** [comment]
Cannot reproduce, but I did add a timeout on the Abort Project-wide Parse loop since it blocks the UI thread. Perhaps there's some condition which I could not trigger where the UI thread is what's processing the Project-wide Parse (this would be a bug in the Feather Plugin runtime).

**Comment by zreedy** [comment]
Reproduced in the attached project. If you wait the UI thread unblocks and the IDE will unhang. The issue is that the Remove event triggers an abort on the Project-wide parse but this flag is only checked at the UI layer, and implementation at the Logic layer is not feasible. There are project-wide directives which cause a very slow Rediscovery prior to the project-wide parse, which means the UI thread is delayed until Rediscovery can complete and the abort request can be fulfilled.

Future improvements to this would be the removal of project-wide directives and instead using per-project Feather settings that way Rediscovery does not need to reparse the entire project due to the discovery of a project-wide directive.

**Comment by zreedy** [comment]
Current workaround to keep the Logic and UI layers divided is to time out the thread block to 1/4th of a second. This does mean that Feather project state becomes stale but the issue resolves if the asset's contents are modified or the asset is renamed. This is not a fantastic solution but there is no way to trigger for an action to occur in the UI layer from the Logic layer without also breaking the LSP implementation.
