### ISSUE TITLE
None of the windows_ commands appears in the index search

### ISSUE THREAD

**Issue by Heathenlamb** [YoYoGames/GameMaker-Bugs#2403]
### Description

Hi folks,

Back again for the 3rd report of this ... it has been quite a long time since I first reported this, and the commands are still not there.

None of the windows_ commands appears in the index search, in the manual. This is a massive PITA for me as the index search is specifically where I search and get info about the commands. Can we PLEASE get this looked at.

Thanks .. Mick

### Manual Link

The Index search

**Comment by gurpreetsinghmatharoo** [comment]
Fixed. Starting with the next manual release the window_ functions should appear in the index again.

This was a case-sensitivity issue. The folder for these functions was The_Game_Window on my PC, as I had renamed it from The_Game_WIndow previously (which was a typo). However this change never reflected in git because only the case was changed, which didn't register. I've fixed its name in git now.

Thanks for the report!
