### ISSUE TITLE
When enabling/disabling Windows Sonic, audio stops to play; it sounds low-passed when enabled

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#2424]
### Description

On Windows 11, if I change "Windows Sonic"* setting in mid-game, audio would stop to play completely until running game again.

To enable Windows Sonic, click on "speaker" in taskbar, then on output selector right to volume settings:
![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/38c2c652-7e15-4e67-a3f6-8b6b385c0c06)
and it should be between output devices and app volume settings.

Also, when Windows Sonic is enabled, sound compressed, similar to bitcruesher or low-pass filters in GM. What's interesting, this **effect is not applied when playing sound from IDE** - it's only applied in game. Also, when changing Windows Sonic setting, music still plays in IDE and stops/have different quality only in game.

[bug_windows_sonic.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13620532/bug_windows_sonic.zip)

### Steps To Reproduce

1. Start game
2. Change Windows Sonic setting
3. Music stops to play
4. Run game again while Windows Sonic is still enabled
5. Music sounds different now (compared to previous run and IDE)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

~2023.8.2~ 2023.11.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Project Added?

- [X] I have included a small sample project

**Comment by L-Clouds** [comment]
Please try also in 2023.11 - I suspect the part where audio stops playing is the same as audio stopping when changing output device, which GameMaker couldn't handle until 2023.11 when support for that was added: https://github.com/YoYoGames/GameMaker-Feature-Requests/issues/1382

**Comment by gnysek** [comment]
That was in 2023.11, bug reporting form didn't have it yet to choose :) I'm fixing report info.

**Comment by toby-yoyo** [comment]
For triage: I think I've found the cause of this already, so we should give it a milestone.

**Comment by toby-yoyo** [comment]
Changes to system effects, the device formats and other OEM properties of the current device will notify the engine of a device update.

@gnysek Regarding the difference in quality with Windows Sonic enabled - I believe this is because the audio file (originally stereo), has been mixed down to mono (due to the settings in the sound editor) before then being mixed back up to 7.1 in the engine (to meet the requirements of Windows Sonic).

There are two problems with this:
- We lose distinct channel data when downmixing. Mono sounds will receive only the most basic upmix because you cannot create 8 distinct channels from 1. The extra channel in a stereo sound makes a big difference to the result of an upmix.
- Previously distinct channel data 'pollutes' all channels when upmixing a previously-downmixed sound. This is important because while it is not exactly known how Windows Sonic works, it is likely that at some stage there is an inter-channel delay applied. This will cause the 'pollution' to then manifest as phase distortion. I believe this is what you are hearing when playing with Windows Sonic enabled.

If you set the asset in the IDE to be exported as stereo (remember to clean), no information is lost to downmixing and the upmixing process will yield a better result. So the output should sound much nicer after being remixed by Windows Sonic.

**Comment by gnysek** [comment]
Thanks for taking a look!

**Comment by toby-yoyo** [comment]
For QA: 
These changes concern the the 'Audio Enhancements' and 'Spatial Sound' settings (shown below) in Settings -> System -> Sound -> (Your Device) 
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/98745055/5bcf9382-0886-410e-862f-d4ec7ec13a69)

Tweaking these settings should no longer cause audio output to stop, as seen in the example project.

From 2024.2, the IDE and the runtime will be using the same audio engine, so the behaviour between the two should be similar.
