### ISSUE TITLE
Game doesn't load on clicking the play icon

### ISSUE THREAD

**Issue by Chickendude12** [YoYoGames/GameMaker-Bugs#2441]
### Description

"C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.0.157/bin/igor/windows/x64/Igor.exe"  -j=8  -options="C:\Users\Chase Taylor\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- OperaGX Run

The application to execute does not exist: 'C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2023.11.0.157\bin\igor\windows\x64\Igor.dll'.
elapsed time 00:00:00.1046237s for command "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.0.157/bin/igor/windows/x64/Igor.exe" -j=8  -options="C:\Users\Chase Taylor\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- OperaGX Run started at 12/10/2023 20:55:14
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.

Project file:
https://drive.google.com/file/d/1D8sGQWgsQm2R2LrHa9t_RF66fIOi70No/view?usp=sharing
[project.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13630439/project.zip)

### Expected Change

That people will be able to test out their games

### Steps To Reproduce

1. Start GameMaker
2. Open or create a game in GameMaker
3. Click play / run project
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by tucanobrasileiro** [comment]
my game meker doesn't want to start the project

It's your problem

**Comment by YYDan** [comment]
Apologies this has gone so long without an answer. I can see from your error that the problem is very simply that either your antivirus client is blocking GameMaker's runtimes folder (the most likely reason) or your runtimes install is incomplete (less likely, and would itself suggest a permissions problem).

Suspect you're hitting the McAfee protection rules.

Assuming you still have this problem, please see the permissions FAQ we link to in every release notes, on the Help menu inside GameMaker itself, on all our setup guides, and here on the readme for this bug-submission system, and then you will be able to configure your protection software just fine ;)
