### ISSUE TITLE
Room Editor: Pressing X/Y keys to flip tiles only works intermittently in 2023.11.1, have to click the IDE button after each press to "reset" the key combination

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#2520]
### Description
The keybinding for X and Y to flip/mirror tiles in the room editor is broken

### Steps To Reproduce
Select a tile, move mouse cursor in the room editor on a tile layer. Attempt to flip or mirror using X and Y

[9a908218-86d2-4711-968f-fbaea42cbd02](https://api.gamemaker.io/api/github/downloads/9a908218-86d2-4711-968f-fbaea42cbd02)

**Comment by nullbunny** [comment]
Got an update for this bug.

If you flip a tile using a button, then place that flipped tile, you can then use the keys again.

1. Select a tile.
2. Press IDE button for flipping the tile
3. Place tile in the room
4. Check that the "X" key is working again

**Comment by YYDan** [comment]
@nullbunny I can see that the contact us package and the bug report came when using 2023.11.1, but I would have hoped this was fixed in the .1 release and indeed I cannot recreate any issues with this when using .1. Any chance this was something you saw in 11.0 and is actually already fixed in .1? If not, can we get more info, please.

[TestTileRotationBreaking.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13785888/TestTileRotationBreaking.zip)

I am:

1. Opening the room
2. Selecting the tile layer (if it is not already).
3. Either clicking anywhere on the canvas and then pressing "S" or clicking the "Tile Edit" button on the toolbar to enter selection mode.
4. Press X or Y twice and see the tile rotates each time.
5. Use the mouse to select a different tile.
6. Repeat step 4.

I can keep doing this without any problems.

**Comment by SmithTom6304** [comment]
Fixed - tile layer shortcuts are "gadget" shortcuts, and so when registered with the shortcut manager were only being checked when the gadget had focus.
I've updated this so that these shortcuts are now being handled by the RoomEditor itself, which will check it's active tool (ie. Tile Layer) shortcuts before checking it's module-level shortcuts. This means that these tool shortcuts are now checked no matter what section of the RoomEditor has focus.

**Comment by SmithTom6304** [comment]
Fix has had some unintended consequences (RoomEditorModule is now taking priority over other hotkeys, like Delete and Rename). Changes have been reverted, so re-opening this.

**Comment by SmithTom6304** [comment]
Additional fix has gone in - RoomEditor shortcuts now only execute after the KBSM execution step _if_ no other shortcuts were executed, and only if the RoomEditor has focus.
We have some work going in for 2024.04 that improves on this, but we want this fix in for 2024.02 and so a temporary solution has gone in. Because of this, this will likely need re-tested for 2024.04.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.200.0.495  Runtime v2024.200.0.512, thanks.
