### ISSUE TITLE
HTML-Crash in vertex submit in 2023.11

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#2532]
### Description
Hello there,

I tracked this one down with the open-source runtime, current dev branch and used the git blame tool to find, which changes where made to the yyVBufferBuilder.js file in 2023.11

Thing is, the vertex_submit function crashes when using it due to a newly introduced check in lines 371 and 387 (according to the blame tool).
These two checks are new in this place for 2023.11, they weren't there in 2023.8

When I remove them, everything works as intended.
See attached a small project that bakes a font through scribble at runtime, which crashes, while these checks are in place.
if you remove them (or set the runtime to 2023.8), everything runs as intended.

Please re-question the mentioned checks what purpose they fulfill here?
and check the `WebGL_IsTextureValid` function, maybe, the problem is there? It's a huge complicated `if` beyond my knowledge, maybe there's a glitch in it?

anyways, please find and correct the problem.

thanks, Gris

### Steps To Reproduce
* Open the attached project
* Set target to windows -> hit F5 -> works
* Set target to html -> hit F6 (for console) -> crash

[0a36126b-2fed-4afa-89c9-80b40255e8a1](https://api.gamemaker.io/api/github/downloads/0a36126b-2fed-4afa-89c9-80b40255e8a1)

**Comment by JonnoRobson** [comment]
The issue was caused by a new check that was added to catch certain cases where `vertex_submit` could be called with an invalid texture reference ( for example passing the texture handle from a surface that was freed after storing the texture handle). I've modified the check to avoid false positives such as in this case while still catching cases where an invalid texture reference was passed in to `vertex_submit`.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.478  Runtime v2024.200.0.493
