### ISSUE TITLE
Code Editor: Repeated fairly-fast keystrokes can lead to some being dropped

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#2545]
### Description
When typing certain keystrokes, such as repeatedly moving the cursor with the arrow keys and entering text after each cursor movement, sometimes keystrokes get dropped.  For example, so you want to insert a space before each line in a comment and you repeatedly hit the following keystrokes to get that done: SPACE, DOWN, LEFT, SPACE, DOWN, LEFT, etc. some of those keystrokes randomly get lost.  Please see attached video demonstrating the issue.

### Steps To Reproduce
(1) In the code/script editor, paste in some text.  Such as this text here:

// Key strokes test.Adding a space after the period.
// Key strokes test.Adding a space after the period.
// Key strokes test.Adding a space after the period.
// Key strokes test.Adding a space after the period.
// Key strokes test.Adding a space after the period.
// Key strokes test.Adding a space after the period.
// Key strokes test.Adding a space after the period.

(2) Position the cursor after the period on the first line.
(3) Now, use your keyboard to quickly insert a space after each period on each of those lines.
(4) Notice how sometimes, a keystroke won't work.  And you don't have to be very quick with your keystrokes to make it happen.

[41d31fba-2a5b-4a99-b68b-606eb4d755cd](https://api.gamemaker.io/api/github/downloads/41d31fba-2a5b-4a99-b68b-606eb4d755cd)

**Comment by PrismaticRealms** [comment]
> Notice how sometimes, a keystroke won't won't.

Correction:
Notice how sometimes, a keystroke won't work.

**Comment by nb109** [comment]
Worse than that, input will happen in the wrong order or with 0.15-0.25 second delays.
I'll be at the end of a line, for example: hit right, hit enter. Instead, the enter will register first, causing the semi-colon at the end of the line to break to the next line, instead of moving the carriage to the right, first, then dropping to a new line.

That's just one arbitrary example, but this stuff happens to me all the time in the IDE. It's super frustrating because I'm used to working fast on the keyboard in console/ JetBrains IDEs/etc and it's jarring to have your workflow constantly slowed down or having to backspace/CTRL+Z super frequently.

This is on my main workstation, by the way; not some laptop.

**Comment by PrismaticRealms** [comment]
> Worse than that, input will happen in the wrong order or with 0.15-0.25 second delays.

This is also happening to me.

**Comment by caitlinrmcintyre** [comment]
Verified fix in Beta IDE v2024.200.0.494  Runtime v2024.200.0.511, thanks.

**Comment by PrismaticRealms** [comment]
Unfortunately, this does not appear to be fixed in v2024.2.0.132.

**Comment by stuckie** [comment]
Was it fixed for you during the betas?

**Comment by PrismaticRealms** [comment]
> Was it fixed for you during the betas?

I did not verify the fix in the Betas.

**Comment by PrismaticRealms** [comment]
Ok, new bug report opened.  See Bug #4941.
It contains pretty much the same kind of video that I originally attached to this issue, showing keystrokes being dropped.
