### ISSUE TITLE
Where is the "uninstall.exe" in my gamemakerstudio2-LTS folder

### ISSUE THREAD

**Issue by this-user-exists-lol** [YoYoGames/GameMaker-Bugs#2617]
### Description

so basically, I tried re-installing gamemaker since I wanted to move to a more recent version (IDE and runtime purposes). But when I click "OK" it just closed out and did absolutely nothing. My next thought was, "ok so that didn't work. maybe if I just uninstall it and then re install it????" and when I tried to uninstall it through my settings app, it ended up with an error stating, "yo you don't have the unistall.exe homie" or something like that. What??? I could've swore I had it before. Now it's just, GONE???? Just like that?? I basically don't have a choice to uninstall it because if I try to download a previous / recent version (yes I tested it with a older version), nothing happens. And when I try to uninstall, I can't since the thing that's supposed to uninstall the damn thing just decided to NOT exist anymore because I tried to install a newer / older version. Like wtf gamemaker???

(also Idk how to add the contact us .zip thing-a-majig lol)

### Expected Change

just give me the damn uninstall.exe already man

### Steps To Reproduce

1. read the description

### How reliably can you recreate this issue using your steps above?

Most Times

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by scott-dunbar** [comment]
Hello

Please see the following FAQ that contains a section on "Unable to install again because windows says GameMaker is still installed", this details how to fully uninstall.

https://help.gamemaker.io/hc/en-us/articles/115002062812

As the guide states, unfortunately, we cannot provide much more support than this as we are not able to directly monitor or use your machine to see where the issue lies. Be aware of Anti-Virus programs that often interfere with this process and indeed can remove executables incorrectly.
