### ISSUE TITLE
Game Maker begins to stall and run very slow after a few hours of use.

### ISSUE THREAD

**Issue by TheoryGeorgiou** [YoYoGames/GameMaker-Bugs#2619]
### Description

IDE when closing asset window, while typing code, opening preferences menus, etc stutters and stalls with every line of code or action taken. This may only happen on larger projects with many assets, and could be related to the temp folder growing large I've seen my temp folder grow to 75mb after a few hours of using game maker.

I have a very very high end development workstation and use a plethora of high resource using software daily and yet Game maker Studio is the only software that runs like absolute garbage after only a couple hours of being open. Any fixes to get it to run smoothly, I already do the following:

Feather is disabled.

Only keep a few asset in the workspace open at a time.

Only use 1 workspace at a time.

Keep the inspector closed at all times.

Keep rooms closed when not editing.

Limit undo count to 100.

Have code checking set to default 250ms

Running a 5800x3D with 32GB of ram and Samsung Evo 970 with 25%+ free space. Point being it is 100% percent not a hardware issue as i have no issues running nay other software.

It is not project related as this issue has been around since I can remember and I've worked on numerous projects where this is still an issue, I also experience this issue on my laptop more evidence this is not hardware or project issue, it's an issue with game maker. 

### Expected Change

No more stalling when editing code.

### Steps To Reproduce

1. Start GameMaker
2. Work on your poroject for 3+ hours
3. Witness how vastly game maker slows down when trying to perform any action or write code.
[contact-us-package.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13795654/contact-us-package.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1.129 

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by NanoSharkGames** [comment]
This same issue is still happening to me as well on my Apple Silicon Mac. I am on the latest monthly version: 2023.11.1

[ui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/13825332/ui.log)

**Comment by shamusl** [comment]
I am also having this issue. It is extremely frustrating. The above commenter is correct, this problem is even worse on Apple Silicon. This needs to be a top priority. The IDE is barely usable at all with large projects. 

I regularly see more than 20GB of RAM taken by the IDE and sometimes it can take 0.25 to 0.5 seconds between clicking with my mouse and the IDE responding. The rest of the system is running smooth and fast, reporting 90% idle.

**Comment by muddrox** [comment]
YES!  I am so glad I am not the only one who is dealing with the ridiculous amount of slowdown with the GameMaker IDE as of late.  I started noticing this being a pervasive issue after the last update or so.  These persistent hiccups/slowdowns with the IDE have made it difficult to write code since the code editor struggles to keep up with my typing speed and I'm not a fast typer...

I went into more detail about this issue in my earlier post on game maker forums.
https://forum.gamemaker.io/index.php?threads/game-maker-ide-running-slower-now.108478/

**Comment by Retrific** [comment]
Related: https://github.com/YoYoGames/GameMaker-Bugs/issues/2528

**Comment by TheoryGeorgiou** [comment]
> Related: #2528

Subscribed. Thanks.

**Comment by YYDan** [comment]
Yeah, as mentioned above, this issue is being tracked in https://github.com/YoYoGames/GameMaker-Bugs/issues/2528 - we'll of course check your logs here as part of investigating that one, but I will go ahead and tidy this one up just now so we can focus the conversation on that one issue.

Thanks!

**Comment by brentbro** [comment]
This has been happening to me for years.
I've been developing on both PC and Mac M2 pro Max Mini.

I'm glad someone has reported it. Although has there been any recommended fix?

**Comment by CressoTheGrey** [comment]
My project has barely anything at this point but it already seems to be running into this issue. When I test the game and exit the test the IDE completely freezes for like 5 minutes. And the image editor is absurdly slow. No idea what could be going wrong here.
