### ISSUE TITLE
The Linux IDE's run pipeline should NOT use AppImage stuff at all

### ISSUE THREAD

**Issue by nkrapivin** [YoYoGames/GameMaker-Bugs#2668]
### Description
The way the current Linux IDE beta runs projects is horribly inefficient,
first it writes all game assets into a zip, then extracts said zip only to run
linuxdeploy & appimagetool on it, only to then extract the appimage into a temp folder again...
Why? Isn't it possible to directly build the entire game into a folder, then call chroot for steam-runtime and run the executable as-is?
Even worse, because of these zip shenanigans,
appimagetool fails to properly handle a Steamworks.so dependency on libsteam_api.so (because libsteam_api isn't a system library) and the entire project fails to run.
When I copy libsteam_api.so into /opt/steam-runtime/usr/lib/x86_64-linux-gnu (which nobody should do anyway) it still doesn't work because appimagetool will MOVE the library for whatever reason.
Then the runner will fail to load Steamworks.so because of a missing dependency... because Steamworks.so has a custom RPATH set.

Ideally, the entire appimage pipeline shall be an extension rather than an Igor thing, but that's something for a feature request.
Anyway, the impact of this weird pipeline is pretty huge, as no Linux IDE users can use the "Run" button to debug their Steamworks game, requiring them to build as a zip (which is not intuitive).

### Steps To Reproduce
Try to build the attached project
It's my GMEXT-Steamworks build but with SDK v1.58a instead of v1.55
(so yes you will need to point it at SDK v1.58a instead of v1.55!)

[62ec3105-85c8-449c-99d9-713a9e713405](https://api.gamemaker.io/api/github/downloads/62ec3105-85c8-449c-99d9-713a9e713405)

**Comment by yoyo-danielc** [comment]
There is room for improvement in how we handle AppImage builds (further discussion welcome), but there is method behind the madness of the build-an-AppImage-then-extract-it-then-run-the-inner-AppRun dance we do:

If we skipped the linuxdeploy/appimagetool steps and ran the game exe inside the Steam Runtime chroot, it wouldn't have access to the host filesystem, in particular there wouldn't be anywhere for the game to write saves/etc to, there wouldn't be access to any pid files/sockets/etc that might be needed by X11 or any other libraries that get loaded and the runner wouldn't be able to load special host libraries (e.g. we load ffmpeg at runtime for video playback when a compatible version is detected).

Some of that could be circumvented by adding bind mounts all over the place inside the chroot, but that's additional directories which need creating inside the chroot, more mounts to create/remove and more ways for upstream changes or different configurations (e.g. Wayland) to break things for what is essentially a build time optimisation.

Originally we just ran the generated AppImage directly rather than unpacking it for parity with how users would run the game, but that was changed to `--extract-and-run` during run specifically because the Steam libraries need to write to the working directory (i.e. `AppDir/usr/bin/`) when running development builds.

FYI I haven't had a chance to look into your project yet, just wanted to explain the background for why we do what we do. There are some other issues around extension library loading on Linux which are currently being investigated/fixed too.

**Comment by DiasFranciscoA** [comment]
After some recent changes that where causing problems with DLL case-sensitivity and case sensitive OSs, this bug seems to be fixed. Please do wait for the Feb24 release this should have all the fixes in and should correctly load steamworks and other extensions and play them correctly from the IDE.

**Comment by yoyo-danielc** [comment]
Closing this since the original issue appears to be resolved. We will probably revisit AppImage and make some improvements around how it integrates in GMRT.
