### ISSUE TITLE
AudioEffect Struct page, vague wording and lack of references

### ISSUE THREAD

**Issue by JeffJ89** [YoYoGames/GameMaker-Bugs#2669]
### Description

> This is a built-in struct, and as such GameMaker has more control over its contents. This means access to its members is limited and some values may change automatically if invalid values were assigned. You may also have to create and destroy this struct through built-in functions provided by GameMaker instead of the new and delete operators.

1: _You may also have to create and destroy this struct_
May? Under what circumstances? Vague wording.

2: _Through built-in functions provided by GameMaker instead of the new and delete operators_
What built-in functions? No further mention of or reference to these mentioned functions.

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Audio/Audio_Effects/AudioEffect.htm

**Comment by gurpreetsinghmatharoo** [comment]
Thanks, it's fixed. That line has been removed as it was unnecessary and part of the "shared note" which is why it was intentionally vague, however the pages where the shared note was used already have all necessary information (e.g. AudioEffect struct has to be created with audio_effect_create() is mentioned).

Cheers
