### ISSUE TITLE
Compress tilemaps within Rooms

### ISSUE THREAD

**Issue by rwkay** [YoYoGames/GameMaker-Bugs#2836]
### Is your feature request related to a problem?

Tilemaps are stored as one 32bit integer for each tile, for large rooms this is a lot of memory and due to the nature of tilemaps they tend to have the same or very similar values, this takes up extra load time and sits in memory all the time bloating things at runtime.

### Describe the solution you'd like

Add a simple compression scheme like RLE to keep decompression fast but slims down the memory size.

### Describe alternatives you've considered

just doing a decompress / compress zlib calls on the data - generally these will be slow though, RLE is probably the better algorithm to go for.

**Comment by Shibohi** [comment]
> Fixed in `develop` with pull request [#3165 ](https://github.com/YoYoGames/GameMaker/pull/3165)
> 
> To Test build the WindyWoods template project on 2023.8 and it the WAD (.win file) around 12.5Mb, build with `develop` and size is reduced by around 150-200Kb, similarly HTML5 exports are reduced by around 60-70Kb

Hey, i dont know but a reduction about 150-200kb is not much... compared to the full size of 12,5MB
For me the problem is not to compress it. the int array should be a key value pair and only the tiles which are set should be saved.

eg:

tile 0-9 are empty and the 10 is set.
just save keyValue[10] = tileIdx.

all empty tiles would be gone. most of the layers are empty so this would be a much better approach than compressing it.

sorry for my bad english.

**Comment by rwkay** [comment]
The tilemap does not take 12.5mb (that is mainly textures) the Tilemaps were only around 300Kb so the tilemap size has dropped considerably.
