### ISSUE TITLE
Project Saving: Expand "unsafe directory" warning to cover OneDrive/Dropbox/iCloud/Google Drive and other cloud sync drives

### ISSUE THREAD

**Issue by dicksonlaw583** [YoYoGames/GameMaker-Bugs#2859]
### Is your feature request related to a problem?

Both the GMC and the helpdesk are still frequently getting tickets about disappearing resources and corrupted projects caused by file access conflicts with cloud sync drives, particularly OneDrive. If the IDE can pre-emptively warn users against putting projects in synced locations, this would help safeguard novices from unexpected data loss and cut down on the amount of explaining that responders need to do.

### Describe the solution you'd like

The IDE should show a warning when a project is saved somewhere containing these terms in the path:

- `OneDrive`
- `Dropbox`
- `com~apple~CloudDocs`
- `Google Drive`

Example Message:

```
This project is saved in a location managed by a cloud storage service:
C:\Users\dev\Dropbox\MyProject
Automatic sync with cloud storage is known to cause unexpected data loss. Please ensure automatic sync is OFF while the IDE is open, or move the project elsewhere.
```

### Describe alternatives you've considered

GMC responders have repeatedly responded to threads advising against saving working copies in cloud sync drives, but the message simply aren't reaching novices. They are still saving projects in cloud sync drives thinking that it protects their data by backing it up, rather than destroying their project through file access conflicts.

### Additional context

This kind of message already shows up when you try to save a project in TEMP, so it is not entirely novel. It should be a relatively quick addition to existing functionality.

**Comment by ParodyKnaveBob** [comment]
Due to Windows just loving to set OneDrive folders for defaults, might I add to the feature request that a warning directly advise to change the IDE Preferences when relevant:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/16678418/1a37396e-da9c-4c8f-856b-8595628d3efb)

**Comment by CalumLaverock** [comment]
This has been done by adding checks when you try to create a new project (a warning asking if you're sure will show if you try to create a project in a cloud storage drive), try to Save As a project (same warning will show), and a warning will be shown when you open a project that is saved in a cloud storage location. The default "My Projects" path has also been set to be within the user profile folder rather than within MyDocuments as OneDrive likes to take over MyDocuments now as per https://github.com/YoYoGames/GameMaker-Bugs/issues/4372, and a warning will be shown on startup if you have your "My Projects" folder within a cloud storage location.

**Comment by YYBartT** [comment]
Warning notes have now been added to the manual.
