### ISSUE TITLE
constructor_call and is_constructor

### ISSUE THREAD

**Issue by Alphish** [YoYoGames/GameMaker-Bugs#3055]
### Is your feature request related to a problem?

Sometimes it would be useful to dynamically create a new struct from a constructor using an array of parameters, just like you can do with `method_call` or `script_execute_ext`. Additionally, one might want to tell a constructor function apart from non-constructor ones, to make the correct type of call (`new some_func()` for constructor vs `some_func()` for non-constructors).

### Describe the solution you'd like

I would like new functions: `constructor_call(ctor,args)` and `is_constructor(func)` to handle the scenarios described above.

E.g. `constructor_call(Foo, ["bar, "baz"])` would be equivalent to `new Foo("bar", "baz")`. This would contrast with `script_execute_ext(Foo, ["bar", "baz"])` which would be equivalent to `Foo("bar", "baz")` instead.

Example code using these:
```gml
function create_generator_callback(_func, _args) {
    return method({ _func, _args }, function() {
        if (is_constructor(_func))
            return constructor_call(_func, _args);
        else if (is_method(_func)
            return method_call(_func, _args);
        else
            return script_execute_ext(_func, _args);
    });
}
```

**Comment by Hyomoto** [comment]
I imagine there was more internal discussion over how to approach this, but I think it's still very much worth considering.  One of the unusual bits about the constructors in GM is that they function as both functions and constructors depending on whether or not 'new' is used.  I have attempted to find places where this quirk is useful but seems mostly to be an odd "gotcha" case in the language.

I think it's arguable a new function shouldn't be needed at all as one could reasonably expect *calling* a constructor to fulfill it's intended purpose and this would just allow using method_call.  I'm don't know if this is too mired in the language the be corrected now, but that gives two vectors to addressing the issue: either have constructors be an identity of the function that affects its result, or "functional parity" between functions and constructors by providing independent functions.

For the sake of discussion I think the former is better in terms of upkeep and accessibility.  There may be some condition whereby the context of the constructor is useful, but generally one would expect a constructor to behave *as* a constructor, otherwise the constructor keyword is superfluous since the `new` keyword should address the utility of the call.  I know the approach is to not break existing functionality as often as possible, but it seems at least worth considering whether or not this quirk needs to be preserved.  Much as the `delete` keyword is pretty much cosmetic, `new` could be depreciated by patching the hole and letting `constructor` properly inform the intent of calling the function thus avoiding adding more functions for constructors/methods/script functions with varying scope as has generally been the case.

Either way the function is desirable even if only to achieve functional parity.

**Comment by Totobal5** [comment]
will this be added?

**Comment by tabularelf** [comment]
We have a form of `is_constructor` that we can apply with the current runtime via tags, so `is_constructor` is at least not as high of a priority. But as of this https://github.com/YoYoGames/GameMaker-Bugs/issues/7690, this will subsequentially kill off any means of using a specific `constructor_call`-like function that the community has developed, in order to allow passing in an array of arguments to **any** constructor function, whether made by a library developer or not. Which is very unfortunate, as `method_call` and `script_execute_ext` both exist and can provide an array of arguments with ease.

**Comment by sofycat** [comment]
this would be incredible to have as I legit was just struggling with this last night!

**Comment by tabularelf** [comment]
Adding onto this from a Discord message I've left. There's already decent ways of going about `constructor_call` in GameMaker, just needs the underlying functionality to be exposed as a function. i.e.

```gml
function ItemBase(_name, _maxStack) constructor {
    static type = "base";
    name = _name;
    maxStack = _maxStack;
}

function ItemBurnable(_name, _maxStack) : ItemBase(_name, _maxStack) constructor {
    static type = "burnable";    
}

// constructor_call(constructor, array_of_arguments, offset=0, length=array_length(array_of_arguments))

global.items = [
  constructor_call(ItemBurnable, ["Stick", 64]),
  constructor_call(ItemBurnable, ["Oak Log", 64]),
];
```

**Comment by tinkerer-red** [comment]
It's not great... but its **_A_** solution
https://gist.github.com/tinkerer-red/c63ddc0d98eb8de4a09d84a4600fc5a6

**Comment by Alphish** [comment]
@tinkerer-red Putting aside pyramid of doom is specifically what we want to avoid...
...why use a struct, where you could just use an array instead? >.<

**Comment by tabularelf** [comment]
Yeah, look at this point all I can say is at least for **current runtime** we have a completely valid and non-broken solution for 2024.11. https://gist.github.com/tabularelf/4ff22cac65f39c57cf4d457d4f6d6e81.

Til we actually get a valid `constructor_call` function.

**Comment by tinkerer-red** [comment]
@Alphish honestly it's just some hold over code from a test project, it's really not thought out or a valid solution, if anything it goes to show the absurdity of the issue.

**Comment by rwkay** [comment]
You can now use (as of 2024.11) `script_execute` and `script_execute_ext` to call constructors explicitly.

And you can use tags to find constructors.

**Comment by rwkay** [comment]
The documentation are getting worked on just now - you can see the beta manual at https://manual.gamemaker.io/beta/en/#t=Content.htm 

When you use `script_execute` it does not create a new object so it will use the current `self` and make that one an instance of the type - it will keep any extra fields that were in there and `instanceof` and `is_instance` will work as exepected for the type that you called the constructor of.
