### ISSUE TITLE
Preferences: Disable Feather rule GM2017 (Inconsistent Naming) by default

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#3084]
### Is your feature request related to a problem?

This particular suggestion is annoying to many existing users and confusing to new users.

ETA: I have seen multiple new users think that the naming suggestions are an actual error that will prevent their game from compiling. I also know many many people who turn feather off entirely due to being annoyed by this particular suggestion, even when told they can turn off this specific one.

### Describe the solution you'd like

As said in the title, I think GM2017 should be set to ignore by default, so people who want it can opt-in, but it doesn't cover everyone else's code in squiggly lines. I've seen many many people asking how to turn off this particular suggestion since feather was changed to be enabled by default.

**Comment by gojirra55** [comment]
Scaring the shit out of noobies with arbitrary coding style rules is absolutely whack af GM.

**Comment by RainyRainbows** [comment]
GRAAAAAH!

**Comment by KormexGit** [comment]
While browsing the manual, I discovered that the docs think that GM2017 is already disabled by default, even though it isn't
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/36b45486-cadf-4d27-a9bc-a9f7ad7bd3cd)

**Comment by thennothinghappened** [comment]
This has come up again with someone who doesn't know how to turn it off having issues with it. In the long term, Feather needs a proper explanation and major improvements to its configuration by "massive list of rules and dropdowns in a scrolling list", but in the short term Feather needs to be setup in a way that will give the most value to people without needing to be customised.

The ability to have a naming rule option is great, but when it is on by default and having Feather on bombards people who are totally unfamiliar with it with a heap of warnings about something that's really just a nitpick for their _naming choice,_ that's terrible UX. This should just be one flick of a switch to set this off by default. There's a lot of people who've lost out on Feather's capabilities because their first experience with it was a cascade of useless messages about how Feather doesn't agree with their case choice. Not knowing how to turn this off - even if it is actually pretty simple to do - people then just assume Feather's here just to judge their style choices, turn Feather off completely, and move on without it.

**Comment by YYBartT** [comment]
No change needed to the manual (which before did incorrectly state that GM2017 is disabled by default, this is now correct).

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.681  Runtime v2024.1100.0.703
