### ISSUE TITLE
Add linux IDE support

### ISSUE THREAD

**Issue by Shadowblitz16** [YoYoGames/GameMaker-Bugs#3204]
### Is your feature request related to a problem?

Please release game maker studio ide for linux.

### Describe the solution you'd like

Release linux compatible gamemaker IDE that allows linux users to make games.

### Describe alternatives you've considered

I have tried using the beta version of the ubuntu editor but it doesn't work
I have also tried using steam proton

### Additional context

Consider using app image or official ppa to bundle it.
we want the dependencies to be able to be used on distro's that aren't strictly ubuntu <version here>

**Comment by stuckie** [comment]
I believe you are being a little bit unkind here.
The IDE works on Linux.. and we already have a guide for setting up Ubuntu for the runner: https://help.gamemaker.io/hc/en-us/articles/235186168-Setting-Up-For-Ubuntu which will give you the same dependencies. 
Which can be easily adapted to your own distribution as required since I have personally ran the IDE on Fedora and on the SteamDeck - which is more or less Arch - as well as various Chromebooks and Raspberry Pis.
That and there are tools such as alien - or simply extract the deb archive itself - to be able to install the current .deb on whatever you are using.
Additionally, we *do* fix bugs with the Linux IDE and Runner and provide quick workarounds where available while we find the time to investigate; see #4327 for a recent example - which is technically not even our officially supported platform of x86_64 Ubuntu.

If you have issues with the IDE on your distribution, then by all means submit them as bugs and we will take a look.
A lot of effort goes into each release by everyone on the GameMaker team, there is only so many hours in a day to work on the multiple platforms we support, and at the end of the day, we can't fix bugs we don't know about anyway.
