### ISSUE TITLE
Building Projects: Add a Game Option for controlling whether unused assets should be excluded from builds

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3597]
From ticket: Ticket #169020

"I have a room that has a lot of objects that I only need when developing the game but the player will never get to see the room, I dont want to have it in the final executable as it takes a lot of time to process all the objects in the room when compiling with YYC and it also increases the executable size unnecessarily."

This could be done with the configs system already in place or simply a toggle on assets to have them excluded during a final build

**Comment by YYDan** [comment]
This has actually been in progress for a long time and is finally exposed for use in the 2024.11 release, so I have tagged and updated the issue now.

The final direction has been much the same as the second comment above: a new Game Option (in the Main section) has been added for saying whether to strip assets which are not used in-game or not.

**Comment by rwkay** [comment]
Please NOTE this has been added at the compilation stage so the assets are only stripped from the final built game, it does NOT strip them from the project file at all.

It still has to load all the projects and assets to determine if an asset (and / or children of that asset) are used or not.

**Comment by rwkay** [comment]
1. Yes all assets are considered
2. references are considered USED before optimisation - this is by design so that the code for the reference does not need to be actually in the final output file. 
3. currently there is an output line for each asset stripped in the output window
4. all rooms are left intact - there is no safe way to assume they are unused

**Comment by kburkhart84** [comment]
1.  That's good (except for rooms, which I understand since they can be referenced indirectly as I mentioned).
2.  So I guess this means we will continue to have to use configurations to mark certain things to be included/excluded in cases where we use images either for room editor only, or for debugging.  I was thinking if the check for this happened AFTER the code was optimized (where it would remove if(false){} statements) then we could save that bit of time but it isn't a big issue as long as it's documented.
3.   That is acceptable, at the least to start with.  It might be nice to have something set up where it separately logs it so it's easier to copy/paste then having to mess with the output window.  But the feature is just getting started so things can only get better from here.

Thanks for adding this feature in.  It is one of the things that will take Gamemaker to the next level.

**Comment by ok4pi** [comment]
If the game doesn't use the relative room functions like room_goto_next(), room_next(), etc. can't you assume that all rooms are directly referenced and remove those which aren't? I think I saw "feature flags" like that decorated around the HTML5 runner.

Also how does this work with assets that are looked up dynamically through i.e. asset_get_index()?

**Comment by DragoniteSpam** [comment]
yyg successfully obsoleting another one of my [old toy projects](https://github.com/DragoniteSpam/GameMakerOrphanedFiles), which admittedly I haven't thought about in several years... hooray

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.685  Runtime v2024.1100.0.707

**Comment by mgeddesGM** [comment]
tested with [testStrippingArrayInstances.zip](https://github.com/user-attachments/files/17751357/testStrippingArrayInstances.zip)
