### ISSUE TITLE
[iOS] Please stop auto-installing Ruby environment

### ISSUE THREAD

**Issue by caroparo** [YoYoGames/GameMaker-Bugs#4359]
### Is your feature request related to a problem?

I have rvm and Ruby installed, but the newer monthly GM IDE versions are constantly trying to install rbenv and whatever ruby version it wants. This is awkward and unnecessary. Please stop doing things like this. 

### Describe the solution you'd like

Remove unnecessary, unprompted, forced installations of rbenv/Ruby/CocoaPods by scripts. Describe the required installations in related setup / documentation pages instead.

**Comment by caroparo** [comment]
Alternatively, please add options to disable said behavior, or specify installation paths.

**Comment by DiasFranciscoA** [comment]
The asset compiler's behavior is contingent upon the availability of the `pod --version` command. Initially, it attempts to execute `pod --version`. If this command fails — indicating that CocoaPods is not installed — it proceeds to check for the presence of rbenv by executing `rbenv --version`. Should rbenv also be found missing, the compiler will install it. Following the successful installation of rbenv, the compiler then installs CocoaPods and configures the environment accordingly to ensure that all necessary components are in place, negating the need for future installations.

If the process is installing it is because pod is not accessible to the asset compiler. If you are not using extension that require installing cocoapods then simply disable the cocoapods installation in the IDE.

<img width="604" alt="image" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/85873067/6f53b36a-6d43-4671-bc2c-d96a1e84e52d">

Let us know if this solves your problems.

**Comment by DiasFranciscoA** [comment]
> [!NOTE]
> If you have your own setup for ruby and `rvm` then make sure cocoapods are installed in your setup following a **sudoless install**. Meaning running `pod install` and other commands shouldn't require sudo mode otherwise the compile process will be  unable to properly build your game.
