### ISSUE TITLE
Search & Replace: F3/Shift+F3 to jump to neighbouring results do not work globally, have to click the code editor window first

### ISSUE THREAD

**Issue by DaveInDev** [YoYoGames/GameMaker-Bugs#4371]
### Description

When the user
- type Ctrl+F to open the search field, 
- type a word to search for
- type ENTER
 
-> The cursor highlight the next matching word, as intended.

But the user cannot directly type F3 to jump to the next occurence.
He has to click first in the editor window, which is not natural in a text editor.

The use of F3 and shift-F3 should be available from the search field.

### Expected Change

One click less, for a quicker search action.

### Steps To Reproduce

described above.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
Seems that hotkeys for _local_ search and replace works correctly, but _global_ search and replace (Ctrl + Shift + F) does not have hotkey support for `Find Next` / `Find Previous`.

Because global search focuses the local window when navigating through results, we'll require different keybinds for the global hotkeys (else the local ones will take over as soon as a code editor gains focus).

Since global search and replace is opened with `Ctrl + Shift + F`, I'll bind global `Find Next` / `Find Previous` to `Ctrl + F3` / `Ctrl + Shift + F3`. `Ctrl` will be replaced with `Command` on Mac.

**Comment by mgeddesGM** [comment]
IDE v2024.800.0.590  Runtime v2024.800.0.614 local f3 and global ctrl+f3 for next are are not working in CE3

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.800.0.597  Runtime v2024.800.0.620
