### ISSUE TITLE
Preferences: [Win IDE] Change "Paths" defaults to avoid OneDrive, now that Windows puts My Documents inside OneDrive

### ISSUE THREAD

**Issue by dicksonlaw583** [YoYoGames/GameMaker-Bugs#4372]
### Is your feature request related to a problem?

This is a continuation of #2859. I noticed that on a fresh Windows install, the "My Projects" and "Templates" paths default to a subdirectory of My Documents. When OneDrive is enabled, its default behaviour is to take over the My Documents directory, which will inevitably default new users to sync-induced file loss (or at least the warning message once 2024.2 is released).

### Describe the solution you'd like

On a fresh Windows install, I would like to see the default "My Projects" and "Templates" paths set to a subdirectory of the user's home directory (which OneDrive **does not** take over by default), rather than the user's My Documents (which OneDrive **does** take over by default). Example with a default C: drive setup:

- New default: `C:\Users\<username>\GameMakerStudio2`
- Old default: `C:\Users\<username>\OneDrive\Documents\GameMakerStudio2`

### Describe alternatives you've considered

GMC responders have repeatedly responded to threads advising against saving working copies in cloud sync drives, but the message simply aren't reaching novices until it is too late. We could warn users against storing working copies in cloud sync drives (#2859), but if the defaults have a potential to start users off storing projects into OneDrive, that would doom novices to a bad start.

**Comment by YYDan** [comment]
Thanks for flagging this one.

**Comment by CalumLaverock** [comment]
The default "My Projects" and "Templates" paths have now been set to be within the user profile folder rather than within MyDocuments and a warning will be shown on startup if you have your "My Projects" folder within a cloud storage location. Also, as per https://github.com/YoYoGames/GameMaker-Bugs/issues/2859, checks have been added when you try to create a new project (a warning asking if you're sure will show if you try to create a project in a cloud storage drive), try to Save As a project (same warning will show), and a warning will be shown when you open a project that is saved in a cloud storage location.

**Comment by YYBartT** [comment]
Documented the new paths in the manual.
