### ISSUE TITLE
exception_unhandled_handler not working in HTML5

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#4437]
### Description
Hey there, I attached a small project to reproduce the bug.
The unhandled-handler is not usable in HTML5 because the exception object contains nothing.

Please fix! Error reporting is especially important on the HTML side!
Thanks, Gris

```
/*
    Demonstrate the failure of the unhandled handler in html
	
	Just start the game
	The script registers an exception_unhandled_handler and then crashes
	
	Windows: All is good
	HTML5:   The exception is an empty object
	
	I can not dump to localStorage on error in HTML, to submit to my server on next start, because there's no data.
*/

function on_unhandled_exception(_ex) {
	
	// I just write to the log.
	// In windows, you see the stacktrace and all
	// In Html, you just see an error, because _ex has no properties, it is... unusable
	
	/*  *** THIS IS HTML OUTPUT ***
		------- ERROR INFO FROM UNHANDLED HANDLER --------
		html-unhandled.js?cachebust=1744220230:838 {  }
	*/
	show_debug_message("------- ERROR INFO FROM UNHANDLED HANDLER --------");
	show_debug_message(string(_ex));
	
}

show_debug_message("Registering handler...");
exception_unhandled_handler(on_unhandled_exception);

show_debug_message("------- CRASHING NOW --------");
not_existing_object.not_existing_property = you_crash.now;

```

### Steps To Reproduce
* open the project
* Set target Windows
* Start it
* See the error in the Output window
* Set target HTML5
* Start either with F6 for a console window or F5 and open console in browser
* You see an endless loop of the crashing handler because the _ex received is dead

[0012afc2-ee06-4f06-82ef-7f344f7fcf67](https://api.gamemaker.io/api/github/downloads/0012afc2-ee06-4f06-82ef-7f344f7fcf67)

**Comment by Emc1923** [comment]
Verified fixed, closing.

**Comment by edcasillas** [comment]
Having a very similar issue as described in more detail [here](https://forum.gamemaker.io/index.php?threads/empty-exception-data-in-exception_unhandled_handler.116146/#post-689145).

Testing with an intentional exception like `var str = "forced" + 5;`, if I do not implement `exception_unhandled_handler` I will see an error like `Unhandled Exception - Uncaught { message : "unable to add string to number"...` on HTML or `DoAdd :: Execution Error` on Mac.

However when I implement `exception_unhandled_handler` with a very simple implementation like the following:

```
exception_unhandled_handler(function(_ex) {
    show_debug_message( "Unhandled exception " + string(_ex) );
});
``` 
I get:
- `Unhandled exception { message : undefined, stacktrace : undefined }` on HTML5
- `Unhandled exception` on Mac
