### ISSUE TITLE
Code Editor: "instance.MACRO" and "variable:MACRO" don't highlight using the correct colour for macro names

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#4468]
### Description

Using dot notation for macros (`instance.MACRO`) will make them appear the same colour as variables. EG:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/40671879/83b14a2a-1675-4f39-832b-ffb54a5270d7)

This also occurs when creating structs, ie `struct = {variable:MACRO}`

### Expected Change

Highlight macros with the correct colour, even if dot notation is being used

### Steps To Reproduce

1. Start GameMaker
2. Create a macro (EG: `#macro macro image_index`)
3. Write `self.macro` and `macro` separately
4. See the issue

[Macros.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14027476/Macros.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by YYDan** [comment]
Strange coincidence, as I was just gathering my evidence and about to report something very related: that configname:MACRONAME colours that definition properly, but then uses a user variable colour for all subsequent MACRONAME appearances.

**Comment by zreedy** [comment]
This is fixed in the new Code Editor, the Legacy Code Editor does not have a facility to determine enough information about the context to solve this issue.

**Comment by Emc1923** [comment]
Verified fixed internally in CE2 as of  IDE v2024.400.0.526  Runtime v2024.400.0.547

**Comment by attic-stuff** [comment]
> Verified working internally in CE2 as of IDE v2024.400.0.526 Runtime v2024.400.0.547

i cannot get this working in 2024.4. in code editor 1, to dot access fields that are macro based you have to put a space in there to retain the macro syntax color because of the limitations mentioned by zach. that looks like this:
![A](https://github.com/YoYoGames/GameMaker-Bugs/assets/44242527/a46082d7-f88c-4a35-bdc1-9f2de03c1084)

in ce2, that same file doesn't even color the macros correctly with the space:
![B](https://github.com/YoYoGames/GameMaker-Bugs/assets/44242527/6246726a-b366-42bb-bf53-ace3309b35a4)

or without the space:
![C](https://github.com/YoYoGames/GameMaker-Bugs/assets/44242527/13e52e92-2a27-4495-aeb7-ec94dfdcb442)

**Comment by Emc1923** [comment]
Reopening as variable:MACRO doesn't seem to be working reliably in CE2 (only works sometimes) - This only seems to be affecting code colouring, tooltips are correct when hovering over.
