### ISSUE TITLE
[Manual] Polish version got translated function names

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#4498]
### Description

Since this commit https://github.com/YoYoGames/GameMaker-Manual-PL/commit/d9aa3405650efe2e858e297035a1ffb6591acde5 lot of functions names in Polish version of manual is translated. An example is `vertex_colour` which became `wierzchołek_kolor` now, but I believe there's more than 100+ functions which are translated in headers and in manual index, which makes them looking funny now.

### Manual Link

https://manual.gamemaker.io/monthly/pl/GameMaker_Language/GML_Reference/Drawing/Primitives/vertex_colour.htm

**Comment by LukeBrownYoYoGames** [comment]
Looks like this arose when @ksuchitra532 manually attempted to resolve an issue where github force pushed a merge from the upstream en repo, by removing and pasting over old files. in the process resurrecting some now deleted files and missing some changes which were made in the interim. 

Luckily, it appears the changes here were minimal given that the turnaround time was pretty short, but there are likely a couple of issues like this which may have regressed due to this step.

The original issue that led to Suchitra needing to make these changes is no also longer possible due to us not relying on github to handle this automatically (and therefore not force pushing anything)
