### ISSUE TITLE
Huge black bar on bottom of GMS - can't be removed (see image)

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#4524]
### Description
Hey there,
I am not 100% sure, how to reproduce that one, but it has to do with "opening a project from recents list when you already have a project open"

The black bar you see in the attached image can't be collapsed, can't be moved, can't be hidden...
it just eats up like 25% of my screen height.

### Steps To Reproduce
I try to explain - i THINK, it has to do with this:

* You need a system with at least 2 screens
* open a project and create a 2nd workspace on the other screen in the same project
* then move your docked windows on bottom (search result, output, etc) to the second workspace
* save your project
* now choose a project from your recent list that does NOT have that second workspace, some single-screen project
* now open your two-screen-project again
* bam! the black is here (sometimes)

it's a combination of opening single- and dual-workspace projects in the same session of gamemaker
but i couldn't figure out a stable way to reproduce it so far

thanks for reading!
kind regards, Gris

[6d1c6499-6251-4a6f-883f-181f54722646](https://api.gamemaker.io/api/github/downloads/6d1c6499-6251-4a6f-883f-181f54722646)

**Comment by yyalansavage** [comment]
Was able to repro first time following the excellent steps above (on both IDE v2023.11.1.129, beta IDE v2024.200.0.493); only happens from a fresh IDE launch. I notice the detached workspace also does not restore on loading that project.
All fixed by above commit, looks like this will be too late for next release however. Only workaround i can see atm, re-loading the project again will remove the "black bar", although the detached workspace won't appear

**Comment by sihammill** [comment]
Verified in IDE v2024.400.0.533  Runtime v2024.400.0.552
