### ISSUE TITLE
Building Projects: [Ubuntu VM] Building can either crash GM IDE or results in audio assert error

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GameMaker-Bugs#4601]
### Description
Whenever I launch a build (VM), it doesn't go through. Either the IDE will crash or I will get the following error :
AL lib: (EE) alc_cleanup: 1 device not closed AppRun: ./Alc/ALc.c:800: LockLists: Assertion `ret == althrd_success' failed.

### Steps To Reproduce
Launch the build via the run button

[6a29f85a-d15d-4e23-be8f-d4a7aa12a6ca](https://api.gamemaker.io/api/github/downloads/6a29f85a-d15d-4e23-be8f-d4a7aa12a6ca)

**Comment by patchuby** [comment]
@toby-yoyo  No this was built on a 2020 mac mini with a M1 chip.

**Comment by patchuby** [comment]
@toby-yoyo Yes I think the title of this issue got confused with another issue I posted around the same time for the macOS IDE -> https://github.com/YoYoGames/GameMaker-Bugs/issues/4600
This is indeed a bug report for the Linux IDE.

**Comment by toby-yoyo** [comment]
I've tried to reproduce a build error on both the reported version Beta IDE 2023.1100.0.450 Beta Runtime 2023.1100.0.459 as well as the latest beta version Beta IDE v2024.200.0.494 Beta Runtime v2024.200.0.511, but the project seems to consistently build on both versions. However, it does run into an in-game error shortly after launching. Aborting the game from here leads to the error message in the description being printed to the IDE console.

That error comes from a system-level library (used only at runtime on the reported version) and is caused by a device handler not being detached when the game aborts unexpectedly. That handler should now be detached properly and so the library should no longer print that error.

**Comment by Emc1923** [comment]
Verified assertion fixed with a test sample in Beta IDE v2024.200.0.499 Beta Runtime v2024.200.0.516
