### ISSUE TITLE
Manual Integration: Pressing F1 to open the Manual does not work 

### ISSUE THREAD

**Issue by alicemoretti** [YoYoGames/GameMaker-Bugs#4675]
### Description

Pressing F1 does not open the Manual. 

This only works in the GML Code code editor due to [this](https://github.com/YoYoGames/GameMaker-Bugs/issues/1933). It should work everywhere in the IDE including the GML Visual editor. 

### Steps To Reproduce

1. Open or create a project 
2. Press F1 
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly), 2022.0.2 (LTS), 2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
Fixed - callback was not being setup properly.
Now when pressing F1, all selected nodes will open their manual pages.
This is still broken when selecting nodes via the story entries menu on the left, due to an issue with the KeyboardShortcutManager ignoring keypresses for certain InputGadgets. This will require a fix that will require testing of various input gadgets, so I'll be putting that in for 2024.04 instead (see #4697)
Note that this also does not fix #1933, although thats specific to the Code Editor.

**Comment by alicemoretti** [comment]
This is partially fixed on IDE v2024.200.0.499  Runtime v2024.200.0.516. 

F1 now works in the visual editor, however, it still doesn't work in the workspace or the start page. Reopening the bug, thank you.
