### ISSUE TITLE
foreach - to iterate over items in array, map and list

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#4765]
### Is your feature request related to a problem?

Recently GM introduced `ref` types, so runner is finally able to find out type of given argument (previously all resources would be rather detected as integer/real). While we got `array_foreach` function already, at that time it wasn't possible to iterate over other types, as that would require passing their type as additional argument, so proper functions could be used to iterate over.
An example of such foreach: https://gist.github.com/gnysek/cdea64d18c10daf344fd2d1084f7baaa .

However, now ds_map, ds_list and others are refs, so when passing into function, runner is able to tell it's not an integer, but such type. While we have `array_foreach` we don't have `ds_map_foreach` or `ds_list_foreach`.

It would be nice to get one common function to iterate over every structure that could be iterated. For sure those are `array` `map` `list`, maybe `struct` (iterating over what `struct_get_names` items) and `grid` (however here it's hard to say which direction should be incremented first - `x` or `y`)

### Describe the solution you'd like

```gml
foreach (var item in array) {
  ...
}
```

```gml
var map = ds_map_create();
map[? "key"] = "foobar";

foreach (var item in map) {
  ...
}
```

```gml
var list = ds_list_create();
list[| 0] = "foobar";

foreach (var item in list) {
  ...
}
```

### Describe alternatives you've considered

If not foreach, then maybe new functions:
`ds_map_foreach`
`ds_list_foreach`

**Comment by ParodyKnaveBob** [comment]
Good news, `struct_foreach()` already exists. $;^ J

This new feature could be excellent for quickly handling a DS List filled from various collision functions.

If `foreach()` were to be a function and not a new keyword construct/loop, though, it should follow GML precedent:
```
var list = ds_list_create();
list[| 0] = "foobar";

foreach(list, function(element, index) {
    ...
});
```
DS Grids, however, would probably need their own `ds_grid_foreach()` function due to `index` not covering row,column coordinates. In fact, DS Grids might do well to either get an extra argument to enumerate the mode (row, column, all) or extra functions. I know Grids are excellent for handling 2D regions, but I've mostly found them useful for handling a row or column at a time myself -- 1D-region operations. On that note, `ds_grid_foreach_region()` might very well be desirable, too -- and *"le sigh"* I suppose that could replace a need for adding specifics for row or column.

Next, I wonder how feasible it would be to include the other DSs -- Queues, PQs, and Stacks. I suppose one should just use a List in those cases, eh? $F^ J

**Comment by Alphish** [comment]
Potential duplicate of this one, maybe? #3203
(regarding the `foreach` language construct itself, rather than taking advantage of typed refs to decide how to iterate through which structures)

**Comment by gnysek** [comment]
As there's very similar FR, and new runtime seems to offer something close to that request, I'm closing it for now, in favour of #3203.
