### ISSUE TITLE
Warning message ?? : the type 'Id.Instance' appears where the type 'Id.Sound, Asset.GMSound' is expected

### ISSUE THREAD

**Issue by galban83** [YoYoGames/GameMaker-Bugs#4833]
### Description
Hello

GMS 2 display this warning message 

E GM1041 The type 'Id.Instance' appears where the type 'Id.Sound, Asset.GMSound' is expected for audio_is_playing(nSndStone)

But i don't undersand why i have this message, i want to test the instance of my sound, not all the sound Snd_Rockslide_Small

		if (audio_is_playing(nSndStone)==false) 
			nSndStone=audio_play_sound(Snd_Rockslide_Small, 10, true);

### Steps To Reproduce
if (audio_is_playing(nSndStone)==false) 
			nSndStone=audio_play_sound(Snd_Rockslide_Small, 10, true);

[31087838-d7b6-46b6-99db-968b95afe137](https://api.gamemaker.io/api/github/downloads/31087838-d7b6-46b6-99db-968b95afe137)

**Comment by DiasFranciscoA** [comment]
Hello @galban83,

There is no attached project file in the provided issue report so we cannot properly identify the problem.

You say that the problem is here:
```
if (audio_is_playing(nSndStone)==false)
```

what is `nSndStone` set to? My guess based on the warning would be that you are setting the variable to `noone`, and `noone` is of type Id.Instance so that could cause the issue. You should make the variable into `-1` (initial value) or undefined if possible, `noone` will still work. You are not getting an error is just a warning, but you should probably avoid using `noone` as it could break eventually in the future.

If this doesn't fix the problem please reopen the issue.
