### ISSUE TITLE
Local Package Integration: Allow being able to turn off the inheritance chain safety check added in 2024.2

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#4875]
### Description
Hello there,

while all-in-all for some cases it is a really good addition, that you now add the entire inheritance chain of objects to local packages, this feature causes lots of trouble!

See attached an image of one of my packages, where I ONLY ADDED the api_talk.
Now, the entire inheritance chain of the single object in api (the request_runner) is also part of the package!

These are the problems, I do have now:
- This package DESTROYS the target project, if it contains another version of raptor then the one I had in the project when i created the package
- The chain contains like 5 of over 300 raptor-files - this is highly incompatible

So far, I could import the api package to ANY old game, no matter which raptor version it had. - and it worked.
The api has its own development cycle, the api talk gets updates independant of raptor, but still uses some of its base objects.

In the old system, because after import, the references/parents were found, all was good - raptor core was not modified

NOW i need to be EXTREMELY CAREFUL that I only select this one api folder and not the entire package upon import.

Please, at least make this selectable when creating a package, whether gamemaker should add the inheritance chain or not!
**(And default it to "off", so by default, GameMaker creates the same packages as it did with previous versions!)**
  
 In fact, now all packages out there, that build "add-ons" for other libraries now will contain all the references and nail the importers to one specific version OR you have to write lots of extra-documentation and explanation, why "please only select the first and third folder" is important...

I must be able to turn off that auto-adding of inheritance objects.
I have good reasons, why I put only those parts into a package!

Thanks for reading,
Cheers Gris

### Steps To Reproduce
* Open a project that contains inherited objects
* If you don't have one at hand, clone my https://github.com/Grisgram/gml-raptor
* Click on Tools -> Create local package
* Pick an object that has parents (in case, you cloned raptor: for instance, add "_gml_raptor_/UI/controls/RaptorWindow" to the package
* Create the package
* Now click on Tools -> Import local package and pick the package you just created
* You seen, not only the Window, but also all parent objects have been added silently to the package
* If you import this package to a project containing an older version of raptor, the entire project breaks due to this partial import

Adding the chain is not a good idea. It is ok only from a point of view of this one added object, but what with the other 100's of objects in the target project, that _also_ depend on the parents that have been added silently?
They now run code, they never had (or miss code, that has been removed in newer versions). It simply no longer compiles, while a solo-import of only the window-object would not have broken anything.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[2d30d243-e4b8-4365-8820-ea0db3de5e18](https://api.gamemaker.io/api/github/downloads/2d30d243-e4b8-4365-8820-ea0db3de5e18)

**Comment by shdwcat** [comment]
I can see where this would help prevent mistakes but I think there should be a setting (ideally as a checkbox in the UI) to enable/disable this for folks who want more control.

**Comment by tabularelf** [comment]
It really should've had been an option for local packages!

**Comment by KormexGit** [comment]
I just did a test, and the extra assets added to the package are not shown when creating the package, they get stealth added with no notification. 

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/c5b560f6-8cde-4c10-8b00-fbe32c6f5d32)

**Comment by stuckie** [comment]
This was reliant on undefined behaviour where the project that was being exported was not solid - it did not have all the references within itself to be able to be loaded up separately.

As we are going towards Prefabs, this becomes a problem as, similarly, they are simply projects at the base level. The problems get worse when these are projects that are potentially shared amongst many other projects, so they have to be self contained as any bad references cannot be expected to be resolved by the user's project, as we don't necessarily know what they will be including until they import something.

And then, what happens if you update a Prefab that then adds or removes an expected reference to resolve that one of the user projects may or may not have? Just typing that is terrifying to me with the amount of unknowns and framework required to figure out what the importing project is wanting, and what the host project has, and then handle clashes; presenting that to the user to resolve where we ourselves don't have the context beyond "this thing is expecting that thing named as this... it doesn't exist/you already have one of a different type" - as then, you have to give the user the option of just bailing at that point, or having to ask for replacements for each missing reference, for each and every host project that is trying to use that Prefab.

You've already noted that the behaviour does still exist for importing, in that you can import part of the project and there are dialogues for replacing and using existing resources as required.
However, we are not intending to create packages which cannot be opened as standalone projects, as this technically was a bug in itself. If you are looking towards functionality like this, then the upcoming Prefabs feature may well be what you are looking for, as this is designed to only pull in the resources required, display only the parts that the Prefab author wants to show, and allow reuse across projects from a single source.

That said, there definitely is an issue in that we should also be displaying the dependencies that are being pulled along with the project as well; that will be fixed.
