### ISSUE TITLE
Put bugs that are specific to a beta release in a different milestone, to improve release note readability 

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#4921]
### Is your feature request related to a problem?

Since the swap to having release notes on github, readability of the release notes has gone way down. It's quite difficult to quickly skim through and see what changes were made when you open it up and are presented with 250+ github issues with inconsistently worded titles. You also are shown a bunch of beta specific bugs - bugs that came into existence during beta and were fixed during beta - that are irrelevant to anyone who wasn't actively using the beta.
For example, opening up the 2024.2 milestone, 5 or 6 of the 7 bugs at the top are all specific to the 2024.2 beta.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/ed98759d-f9e2-4366-845a-f26046c6d3f6)

### Describe the solution you'd like

Instead of putting beta only bugs into the main milestone (ie 2024.4) put them into a separate beta milestone, like "2024.4 Beta" or some such. This keeps those bugs out of the main release notes milestone and makes it easier to see what's actually new.

### Describe alternatives you've considered

Honestly the ideal solution would be to go back to manually written release notes, but if that's not gonna happen then what I proposed above will at least help some. I also did a request for fully reverting to manual release notes here #4923

**Comment by DragoniteSpam** [comment]
Copying what I wrote on the forums:

From the "an update is available" page, you have to click on three and a half separate links to actually see the release notes:

1. The release notes themselves - https://gms.yoyogames.com/ReleaseNotes.html
2. The link to the Github milestone - https://github.com/YoYoGames/GameMaker-Bugs/milestone/7?closed=1
2.5. The "show more" in the Github milestone
3.5. The link to the GMLSpecChanges - https://github.com/YoYoGames/GameMaker-Bugs/blob/main/GMLSpecChanges/2024.2.md

Nobody who isn't a power user is going to see those. Finding the release notes shouldn't feel like a job. The Spec Changes should be front and center on the release notes, the way they used to be. I have no idea why things stopped being done this way because telling people what you changed has got to be the least difficult part of making a game engine.

It also wouldn't hurt to link [the normal English version](https://gamemaker.io/en/blog/release-2024-2) somewhere in the release notes, too.

See also #4506 though I still disagree that automatically copying the commit messages would make things any better.

**Comment by stuckie** [comment]
This is not something we are planning.
