### ISSUE TITLE
Code Editor 2: UX issues with Split View Button

### ISSUE THREAD

**Issue by attic-stuff** [YoYoGames/GameMaker-Bugs#5235]
### Description

in code editor 2, the split view button has no mouseover feedback and the button is horizontally aligned where it should be vertically aligned. also, you should be able to click it to split the view in the middle without having to drag the button.

![Capture](https://github.com/YoYoGames/GameMaker-Bugs/assets/44242527/9c067474-5379-4998-881b-2233e0d48559)

### Expected Change

button should highlight/outline like the others, and have a vertical icon

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by skud92** [comment]
Agreed we can improve UX of the split icon.

We should have feedback but not similar to other buttons/icons in the IDE - this is because it uses a click and drag functionality.

I agree a single click should split the view 50/50 horizontally in the centre.

Icon is correct, it reflects the view created when in use.

**Suggested rework:**
Tooltip on hover - "Horizontal split - Drag or click to split editor view"

Hover cursor - Split cursor icon to be used on hover (see video example from sequences dope sheet resizing, this is also used in Room Editor rulers/smart guides.) 
_Example uses resize - we should use the split icon used in the code editor frame._ 
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/42850338/9a588db8-d21e-4bdf-82d9-ae94cb31de96)

https://github.com/YoYoGames/GameMaker-Bugs/assets/42850338/ce5898b6-e960-4dfc-a261-2343715e0d79

If this needs more feedback we can change icon colour on hover, however, this is inconsistent with the rest of IDE so may need further discussion.

**Note:**
These are small simple changes that improve the UX of the split editor icon, if this still is unclear we can have further discussions and rework the framing.

**Comment by attic-stuff** [comment]
imo the button to split the view should be two rectangles beside each other like vscode; clicking it should split the window evenly each click, and right clicking it should give you the option to split horizontally (changing the icon appropriately) instead. the current icon does not telegraph as a button at all, and looks more like what you'd use to set a ruler or a guide rather than to split the code editor in two. right clicking the code editor window should also have a splitting option similar to code editor 1.

dragging it to split the windows is confusing and unintuitive and introduces some accessibility issues.

**Comment by TheGitMagician** [comment]
"We should add split on RMB."

That would solve it. Then divide into two equal parts and let the user drag the divider.

**Comment by KormexGit** [comment]
Having both a click to evenly split and a drag option would be great, that keeps the convenience of the old CE1 splitting while also having the flexibility of the new drag version

**Comment by zreedy** [comment]
Fixed.
- Tooltip added
- RMB splits horizontally
- Icon's color changes when moused over

**Comment by caitlinrmcintyre** [comment]
Verified fix in Beta IDE v2024.800.0.618  Runtime v2024.800.0.642, thanks.
