### ISSUE TITLE
Evaluation Order of Array/Struct creation

### ISSUE THREAD

**Issue by zzhamzz** [YoYoGames/GameMaker-Bugs#5369]
### Description

The manual states function parameter evaluation order is platform dependent/undefined.

However, it doesn't explicitly mention Arrays or Structs in the discussion.

e.g.  All three of the following parametered lines have right-to-left evaluation order on Windows platform. And left-to-right on HTML5.

```
var _n = 0;

//functions
someFunction(_n++, _n++);

// structs
someStruct = {a:_n++, b:_n++);

// arrays
someArray = [_n++, _n++];
```

Consider explicitly documenting the parameter evaluation order for implict array creation and anon struct creation.  Defining a platform agnostic evaluation order would be ideal but at least document that they are currenlty undefined/platform dependent.

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Overview%2FEvaluation_Order.htm

**Comment by attic-stuff** [comment]
there could definitely be a bit more documentation for this behavior for sure. the evaluation order page should mention this, but the array and struct over view pages should mention it as well. for example structs are entirely unordered, its not a matter of left to right or right to left, the order in which structs populate shouldnt be relied on at all. for arrays i _think_ they populate backwards on windows because that is the memory efficient way to do it. on html5 it is more memory efficient to populate from 0 up. the array page mentions this kind of, but doesnt let you know that the runner does this.

**Comment by zzhamzz** [comment]
@attic-stuff  "or example structs are entirely unordered"

The order that entries are stored in the struct hash are not related to the evaluation order of the parameters passed at the time of struct creation.  The evaluation of parameters is going to occur before the struct is even created.

e.g. if you used a constructor function instead of an anonymous struct construction this should be clear.  Under the hood anonymous struct creation is most likely being passed into an internal function and that is why evaluation order is following the same order as functions.

```
// Consider a struct constructor

// When this function is invoked
// first thing that will occur is the parameters (_a, _b) are going to be evaluated (in some order)

function StructConstructor(_a, _b) constructor {
   // THEN the struct is created if this constructor was called with the NEW keyword

  // Now we start adding entries into the struct hash
  // at this point _a, _b parameters are already evaluated

  b = _b;  // The order we add to the hash has no bearing on the evaluation order of the parameters
  a = _a;  // Nor does the order we add enteries to the hash effect the order they are stored in the hash

}

// An anon struct is going to follow those same steps
var _someStruct = {a: _a, b: _b};

// The above will anon struct is constructed similar to following 
var _someStruct = new StructConstructor(_a, _b); 

// And both have a known evaluation order of parameters. The documentation needs to mention it
```



The order of evaluation is completely controllable by YYG at compile time.  Why they have chosen for it to remain platform dependent is questionable.

But I'm not asking for a platform agnostic evaluation order, even though that would be smart and there is no reason for there not to be a defined evaluation order at GML level (the compiler can do anything it wants at the platform/export level); I'm asking for clear documentation.

In general: 

- Any series of expresssions separated by commas should have the same evaluatiuon order (right to left on windows); functions parameters, implicit array creation parameters, anonymous struct creation parameters.
- Any series of expressions separated by semi-colons should have the same evaluation order (left to right on windows).  
- Any terms of an expression separated by various operators should evaluate depending on operator precedence (again something they could explicitly define to be platform agnostic in GML but choose not to for some reason).

Most of this is documented in the manual except for an explicit mention of evaluation order during array/struct creation.

**Comment by rwkay** [comment]
We are unable to guarantee the order of evaluation on expressions within function arguments because

1. C/C++ makes this compiler dependent and we cannot guarantee it on our YYC compiler across all targets.
2. Anything that we do to guarantee the order of evaluation is extra overhead as we would have to inject extra code and variables that would take extra time away from user code -  we always seek to minimise the overhead (especially in a virtual machine environment), and while desktop computers are generally fast these days we also target low power machines that are not as capable.

This is not something we are planning to do

**Comment by zzhamzz** [comment]
> We are unable to guarantee the order of evaluation on expressions within function arguments because
> 
> 1. C/C++ makes this compiler dependent and we cannot guarantee it on our YYC compiler across all targets.
> 2. Anything that we do to guarantee the order of evaluation is extra overhead as we would have to inject extra code and variables that would take extra time away from user code -  we always seek to minimise the overhead (especially in a virtual machine environment), and while desktop computers are generally fast these days we also target low power machines that are not as capable.
> 
> This is not something we are planning to do

I am not asking you tio gaurantee evaluation order.  I am asking you to document that the evalution order of parameters in array and struct creation are not gauranteed.
