### ISSUE TITLE
Unable to load project

### ISSUE THREAD

**Issue by Chev8703** [YoYoGames/GameMaker-Bugs#5444]
### Description
This actually isn't a GameMaker bug but I didn't know how else to report this. I'm currently unable to load a project I'm working on. Every time I click on it, I get a prompt saying "Unable to load". I have no idea what's wrong and I don't have a backup of my project. I really hope you can help me.

### Steps To Reproduce
I click on the project.
The "Unable to load" prompt appears.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[e72f112e-51c5-4573-abb2-a5cbeb2fd977](https://api.gamemaker.io/api/github/downloads/e72f112e-51c5-4573-abb2-a5cbeb2fd977)

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

You've included a .yyp in the package, but this is not the complete project as it is missing the various .yy files that make up the resources; you will need to zip up the complete directory to send in.
