### ISSUE TITLE
Ellipse collision bbox does not work outside the sprite bounds

### ISSUE THREAD

**Issue by danielpancake** [YoYoGames/GameMaker-Bugs#5468]
### Description
Collision event ignores the part of the ellipse collision bbox outside of the sprite bounds which is not the case for the rectangle bbox

### Steps To Reproduce
Create a sprite and put an ellipse collision bbox outside of the sprite bounds

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[cee9f336-4557-46ca-9f9f-0367465871be](https://api.gamemaker.io/api/github/downloads/cee9f336-4557-46ca-9f9f-0367465871be)

**Comment by jackerley** [comment]
The fix for this was rather complicated. Essentially all precise collision masks have moved over to being stored per sprite bounding box rather than per sprite size. This has impacted a number of functions so I've tested with a number of test projects which I'll attach here. This does have the benefit of reducing memory usage for precise collisions, so has benefits beyond just this specific bug. 
[testprojects.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15414990/testprojects.zip)

**Comment by mgeddesGM** [comment]
verified as of  v2024.600.0.568  Runtime v2024.600.0.595
