### ISSUE TITLE
GPU Hardware Texture Compression

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#5495]
Texture Compression is a way of reducing the memory and bandwidth used for storing and rendering textures on GPU devices. Different methods of texture compression are used on different hardware families - so there is not a simple one solution fits all target platforms, and because each of them are lossy how good they look differs from algorithm to algorithm. 

We have added support for Texture Compression at compile and runtime (currently no IDE support for visualising this).  The UX is very limited just now and it has an impact on build times, but it can improve memory footprint and rendering can be significantly speeded up (we have seen a 10x improvement on some platforms).

Compression happens at compile time and the type of compression (and quality ) are controlled via parameters added to the texture group (so everything has to be placed into a group to control compression).

Compression tools are common and we will be providing a github repo with the project required to setup the tools and all the information required to implement the feature.

On desktop platforms we support Block based textures - https://en.wikipedia.org/wiki/S3_Texture_Compression
On mobile platforms we support ASTC - https://en.wikipedia.org/wiki/Adaptive_scalable_texture_compression
On console platforms we support the local compression methods.

NOTE: Hardware textures are smaller in VRAM but they may be larger than PNG files so the on-disk size may get larger (but runtime VRAM will be smaller and rendering speed will be better)

**Comment by tinkerer-red** [comment]
I have some small concern about that, it says that the textures are compressed at compile time, how ever I'm curious if this acts like yyc compiles where some texture sheets are cached or if this recompresses the texture sheet ever time you compile.

**Comment by gnysek** [comment]
I suspect this might use `post_textures.bat`, but manual doesn't precise if `TexturesDir` contains only changed textures, or all. Aaand there's chance that for this solution, they have added some new variables which are passed to `.bat/.sh` scripts.

Seems we need to wait for repository with extension for compression to see it in action.

**Comment by jackerley** [comment]
Sample project now public at https://github.com/YoYoGames/GM-GPUTextureCompression

**Comment by GameDevTosh** [comment]
Unsure if this is a bug, but, on adding the exe's from the example project to my project and running it, it would NOT run due to the main folder my projects are in having spaces in the name. Saving the project to a folder with no spaces allows it to run.


![Image](https://github.com/YoYoGames/GameMaker-Bugs/assets/85319605/b081b40d-852a-472d-9a60-3508f306d519)

With that said, it works really well. For anyone interested, here's a comparison picture:

![Image](https://github.com/YoYoGames/GameMaker-Bugs/assets/85319605/822993f4-4ef9-49df-b32e-bf81716008a5)

Here is a pic without compression and vram usage:

![Image](https://github.com/YoYoGames/GameMaker-Bugs/assets/85319605/dd6029d0-d797-4ce0-8caa-8f71c1f5a0b8)

As you can see here, ram usage doubles, but vram (memory used in gpu z) is reduced by over 400MB in a visual novel type game with lots of HD texture pages:

![Image](https://github.com/YoYoGames/GameMaker-Bugs/assets/85319605/4bed0188-602c-4a9c-9b3f-3b174401895b)

But this is really the only way that was suggested to me to check vram usage, so I can't really say its completely accurate. A proper way to check the vram usage inside Gamemaker would be great, if it's possible, when this is properly implemented.

**Comment by YYBartT** [comment]
Documented the new settings for texture groups and added a general section on texture compression (both standard and GPU texture compression) on the Textures page. Linked the extension and added a short description of block compression.
