### ISSUE TITLE
Pressing the Delete key in a Room Editor instance field deletes the selected layer

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#5534]
### Description

**Summary**: In IDE v2024.400.0.543  Runtime v2024.400.0.562, pressing backspace in a Room Editor instance field will delete the selected layer.

<img width="1404" alt="Screenshot 2024-04-17 at 14 11 55" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/87641114/784f6a3d-05d3-44dc-91ee-fb0240bf7787">

### Expected Change

Pressing backspace should just delete the text in the textbox

### Steps To Reproduce

1. Start GameMaker
2. Open a room with an object in an instance layer
3. Select the instance layer
4. Double click the instance to open it
5. Select the instances `X` property textbox
6. Press backspace
7. See the instance layer is deleted

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
We also don't have a warning before deleting a layer - we might want a `Yes/No/Remember my choice` popup here

**Comment by 5-0Tree** [comment]
I've experienced this same issue, but I noticed that it only happens if the Layers tab for the room being edited was last selected. For example:
1. I first clicked the layer which contained the object I wanted to delete (to make sure it was selected; alternatively, hold 'P' to select from any layer).
2. I then clicked over to the Asset Browser (or any other non-room editor panel).
3. When I clicked the object to be deleted, it did _not_ delete the entire layer—rather, just the single object.

This leads me to believe that an issue of sorts has arisen with retaining the focus for 'F2' renaming the layer in the Layers tab, rather than the dock tab name (which the opposite is true from before the most recent update, 2024.400.0.543). I think it could have something to do with that, so I'm just throwing it out there.

**Comment by SmithTom6304** [comment]
This should now be fixed. The following changes were made:
- Pressing delete in an instance textbox field no longer causes the selected layer to be deleted
- A yes/no warning is now shown when deleting a layer
- Pressing Delete no longer deletes the layer if the layer was not the last thing selected. Now, delete will only work when the actual layer in the layer menu is the last thing clicked on. This matches the rename functionality

**Comment by caitlinrmcintyre** [comment]
Reopening as I'm still seeing an issue with the layer deleting but only after pressing backspace within the instance textbox field and then closing the instance window. 

1. Double click instance layer (i.e obj_block_coins in rm_level_1).
2. Backspace in X property textbox.
3. Close the instance window and see issue.

https://github.com/YoYoGames/GameMaker-Bugs/assets/131007845/ba37ab4b-4dfb-4348-812d-b6e0a477cbd2

**Comment by caitlinrmcintyre** [comment]
Closing this as we've realized that the layer is not being deleted but instead being moved when I backspaced in the x textbox field which is correct, it just doesn't update immediately until I closed the instance window.
