### ISSUE TITLE
iOS RAM Usage inaccuracy

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#5649]
### Description
For a blank project for iOS export, when using the `debug_event("DumpMemory", true)` function to assess memory usage, the number is much smaller compared to what we see from XCode. 

Can `debug_event()` show a closer number to the actual memory usage?

### Steps To Reproduce
1. Compile the sample for iOS export
2. See that `debug_event()` show the memory usage is only about 15 MB, but the XCode memory view shows the app is using about 150 MB

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.499 Runtime v2024.200.0.516

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[24b78d08-5f81-4a45-9741-cc84edbb1cd4](https://api.gamemaker.io/api/github/downloads/24b78d08-5f81-4a45-9741-cc84edbb1cd4)

**Comment by time-killer-games** [comment]
I wanted to mention that I have written an extension for macOS which also gets ram total/used/free. What Activity Monitor actually shows for RAM usage is not correct, even though that's what Apple gives the user to refer to in the OS for RAM usage, You can see when you compare it with the official OS-level API's they provide for getting RAM usage that the two do not align with each other. Both macOS and iOS share the same Darwin base and XNU kernel, which is probably why your phone or device is not reporting the same RAM usage as GameMaker. There is no obvious means to get a value for RAM usage which would align with what the OS is claiming because the OS-level API's don't report the same thing. I wouldn't call this a bug with GameMaker, but rather, Apple being deceitful for some unknown and strange reason.

**Comment by stuckie** [comment]
This is showing the memory that we are in control of; the operating system may be adding extra overhead which we can't track in a platform agnostic manner.
