### ISSUE TITLE
export problem

### ISSUE THREAD

**Issue by ranvijayshar** [YoYoGames/GameMaker-Bugs#5696]
### Description

i cant export to any of the given platform setting i want to export in html5 but i cant 

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows, HTML5

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by iampremo** [comment]
You can only access Windows and HTML5 exports after you have logged in to the IDE.

If the account icon is grey then you are not logged in, blue is logged in. 
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/16644676/918b3bf1-c0c2-4870-b701-40e4c2ad79ae)

If you are still having issues please submit an issue from within the IDE so that all the relevant log files are attached.
