### ISSUE TITLE
hello my gamemaker isnt working

### ISSUE THREAD

**Issue by insidefeedback** [YoYoGames/GameMaker-Bugs#5702]
### Description

![Captura de Tela 2024-05-01 às 09 14 10](https://github.com/YoYoGames/GameMaker-Bugs/assets/168651084/64c6ee43-5812-4056-843b-0e51be23511d)
![Captura de Tela 2024-05-01 às 09 14 11 1](https://github.com/YoYoGames/GameMaker-Bugs/assets/168651084/2eadfeba-d55d-4b78-9286-ebf762207464)
![Captura de Tela 2024-05-01 às 09 14 11](https://github.com/YoYoGames/GameMaker-Bugs/assets/168651084/9d9874e9-2ff8-4bf7-9097-8c7f508db925)
![Captura de Tela 2024-05-01 às 09 14 42](https://github.com/YoYoGames/GameMaker-Bugs/assets/168651084/d584d951-2c48-4cec-a85d-b0057ec325ba)
![Captura de Tela 2024-05-01 às 09 14 50](https://github.com/YoYoGames/GameMaker-Bugs/assets/168651084/4df8f021-7707-4e69-8683-3b7ce6aff466)

i think thats it can you help me 

also it says
the smal text says ; click open to open the application again click report to see more detailed information and send a report to apple
the big says one :GameMaker has terminated unexpectedly.

**Comment by insidefeedback** [comment]
i have no hope anyomre

**Comment by YYDan** [comment]
Hello,

High Sierra cannot run the current versions of GameMaker (and you would be unable to get a suitable current Xcode version for doing any macOS/iOS development also, so there's nothing we could do there). I am assuming High Sierra from the background pic and also because your logs say iMac 12.1 [and so this is the latest OS version you can apparently use](https://discussions.apple.com/thread/254449305?sortBy=best)

You are welcome to use old versions of GameMaker, but there is no support offered for these legacy releases nowadays and also Apple will not allow you to submit your games to their store.

You would likely need to use GameMaker 2023.4 (or older) and a corresponding old version of Xcode: [https://help.gamemaker.io/hc/en-us/articles/7195454521885-Required-SDKs-For-Old-GMS2-Versions](https://help.gamemaker.io/hc/en-us/articles/7195454521885-Required-SDKs-For-Old-GMS2-Versions)

**Comment by YYDan** [comment]
Correction - turns out I should have linked you to the Mac setup guide directly, as I just noticed that page very clearly says which version is the last one that supports High Sierra ;)

https://help.gamemaker.io/hc/en-us/articles/235186128-Setting-Up-For-macOS

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/98410a99-ada8-4098-914f-c645624c7148)
