### ISSUE TITLE
Docs Integration: Android setup docs should say NDK 26 and SDK 34 work in 2024.4, ahead of Google Play submission minimums changing Aug 24

### ISSUE THREAD

**Issue by AIO1** [YoYoGames/GameMaker-Bugs#5736]
### Is your feature request related to a problem?

Yes in the SDK side since it can be misleading.

### Describe the solution you'd like

I wanted to request an upgrade on the NDK for Android to version 26.3.11579264 (it seems to work now, but at least make it official on the required SDKs page).

Also, I've seend that the required SDKs page indicates to install SDK version 33, while Google is moving on to target version 34 for August. This should be updated to not mislead users into thinking version 33 is the way to go.

The setup guide for Android should be updated accordingly.

**Comment by YYDan** [comment]
We have just added confirmation in the required SDKs FAQ that 2024.4 supports the latest non-beta Android tools (and documented what they are), plus fixed a few bits in the setup guide - mostly to remove mentions of _old_ stuff.

Note that we typically don't update the guides simply because Android have released a new version - we only update when _GameMaker_ requires you to change your tools - but the upcoming policy change you mentioned triggered us to do this now.

However, do you have a source for that policy change in August?

Google's own page does not mention this yet: https://developer.android.com/google/play/requirements/target-sdk?_gl=1*eeotga*_up*MQ..*_ga*OTE4MDMxMTc3LjE3MTQ3NDIzNzQ.*_ga_6HH9YJMN9M*MTcxNDc0MjM3My4xLjAuMTcxNDc0MjQzNy4wLjAuMA.. 

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/9907c049-b6fb-4602-b5c5-b874c2d02105)

Googling shows me a few Stackoverflow threads about developers seeing a warning about 34 after they submit a package, but those same threads say the warning went away a few days later, so not sure if that counts.

https://support.google.com/googleplay/android-developer/answer/11926878?hl=en-GB _does_ tend to agree with you that Google _should have_ already updated the page above and those warnings _should_ have persisted, but hey...

If you can provide the source, then we can add mention of this change into the Required SDKs FAQ also.

**Comment by AIO1** [comment]
@YYDan funny enough, I've noticed this when I went to "Game options" > "Android" if you select something that is not API Level 34.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/17305493/01b92d15-6611-4d46-b361-05578a13e753)

I though this was something that you had included in GMS, but I'm guessing now its not, and that you are fetching this output from the Android build tools?

Researching a bit I've found this:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/17305493/025165a4-c3d2-4a68-ab02-a10ef2b90274)

And [this](https://apilevels.com/) (unofficial)

**Comment by gnysek** [comment]
Whoa, I thought that info about 34+ was added by YYG manually.

**Comment by YYDan** [comment]
Apologies, this was all done in advance of 2024.8, but I missed updating this issue as we had not added it to the milestone.

Closing it now ;)
