### ISSUE TITLE
HTTP default timeout? - Add option to establish timeouts to HTTP calls.

### ISSUE THREAD

**Issue by AIO1** [YoYoGames/GameMaker-Bugs#5744]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

In GMS http don't seem to have a timeout? or at least indicated in the manual that I can find...
It would be nice to have an additional optional argument for all http functions that serves as a timeout.

Basically if no argument is given, the http will end at a default (1 min for example)
If the argument is given, is the time in milis to trigger a timeout if no responde is given, so for example:

http_get("URL", 10000) --> This would mean than GMS will try to wait 10 secs to that (async) and if no response is given, it would then in the networking even, in the async_load map contain a new entry that will indicate that it has been casued by a timeout.

Something like this could be great for making it easier to handle HTTP timeouts. Its a configuration that is set indvidually to each http call done.

Also it could exist a global http timeout that can be modified and it will only affect those http calls that don't have the timeout argument specified.

**Comment by yoyo-danielc** [comment]
There is now a `http_set_connect_timeout(milliseconds)` function on the 2024.08 branch, which sets a global timeout used for the connection phase of any subsequent HTTP requests. If you want to use a specific timeout for each request, the function can be called prior to each `http_get()`/`http_request()`/etc call without affecting the already-created requests.

The timeout doesn't apply to web exports due to limitations of how `XmlHttpRequest` works.

[http_timeout_test.zip](https://github.com/user-attachments/files/16335666/http_timeout_test.zip)

**Comment by cameron-home** [comment]
Verified working in IDE v2024.800.0.598  Runtime v2024.800.0.621 on all platforms. Will move onto Verified swimlane when docs are done.

**Comment by cameron-home** [comment]
A user raised the following: https://forum.gamemaker.io/index.php?threads/2024-800-betas-release-thread.114066/post-680344. After discussions with @yoyo-danielc, we agreed this was the intended behaviour.

The timeout set by the user is an upper limit and the connection may fail earlier. Can you ensure that this is made clear in the documentation please @YYBartT?

**Comment by YYBartT** [comment]
@cameron-home, this note was added to the `http_set_connect_timeout()` manual page: 

![image](https://github.com/user-attachments/assets/9f195ace-eebd-48a2-8cde-2366f4cc2f26)

That should cover the behaviour shown there I think?

**Comment by cameron-home** [comment]
Looks great, thanks @YYBartT ! I'll mark as Verified again.
