### ISSUE TITLE
Add a function to return the sound asset used for a voice index

### ISSUE THREAD

**Issue by JujuAdams** [YoYoGames/GameMaker-Bugs#5861]
### Is your feature request related to a problem?

It is not currently possible to find what sound was played to create a voice index. This can cause friction when using audio to trigger behaviours downstream of audio being played.

### Describe the solution you'd like

`audio_sound_get_index(voice)`, or similarly named function, that takes a voice index and returns the sound resource used to play it. If the voice doesn't exist, the function should return `undefined`.

### Describe alternatives you've considered

Adding voice and sound as a key-value pair to a ds_map, which needs constant maintenance to avoid memory leaks due to monotonically increasing voice index values.

**Comment by toby-yoyo** [comment]
Added `audio_sound_get_asset`, which works as described above. In addition to the above, if the given voice index doesn't correspond to an active voice, `undefined` is returned. An active voice is one that has not yet finished playing.

Test project: [gmb-5861-x.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15415647/gmb-5861-x.zip)

**Comment by gurpreetsinghmatharoo** [comment]
Reopening because of issue - with non-compressed sounds, this function continues to return the correct asset even after the voice has stopped playing.

For @toby-yoyo - test project: 
[Space Rocks Phsycis.zip](https://github.com/user-attachments/files/15612899/Space.Rocks.Phsycis.zip)

Press space to play the main sound, and left-click to see its asset ID in the output plug + whether it's playing or not. Code is in obj_player.

**Comment by toby-yoyo** [comment]
Fixed an issue where voices which had finished playing uncompressed sounds were often still considered 'active'.

**Comment by sihammill** [comment]
Fix verified in IDE v2024.600.0.583 Beta Runtime v2024.600.0.607
