### ISSUE TITLE
Unable to load runtime 2024.4.1.202

### ISSUE THREAD

**Issue by SBogatz** [YoYoGames/GameMaker-Bugs#6022]
### Description
Am able to download the necessary runtime files (zipped.)  Created a file at this location:  %programdata%\GameMakerStudio2\Cache\runtimes\runtime-2024.4.1.202\download.  Placed the 3 zipped files in that location.  Closed and Reopened Gamemaker but  Runtime 2024.4.1.201 remains.  Deleted old Runtime from file location, restarted Gamemaker, and it downloaded old runtime.  Deleted it again fron file location and temporarily stopped internet.  Gamemaker could find no runtime, despite  the 3 zipped files placed in folder %programdata%\GameMakerStudio2\Cache\runtimes\runtime-2024.4.1.202\download.  I also tireld to put the 3 zipped files in that location but minus the download folder.

### Steps To Reproduce
Please see above,   I attached the UI file and a screenshot of the 3 zipped files' location.   Thank you

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Android

[340022d9-bbd6-4336-aa93-e4a1e3e906f3](https://api.gamemaker.io/api/github/downloads/340022d9-bbd6-4336-aa93-e4a1e3e906f3)

**Comment by YYDan** [comment]
Yes. That's all correct and while your ui.log shows lots of frequent starts and evidence of everything you have mentioned here, it doesn't indicate a bug for us to worry about.

Don't delete runtime 201 - that's the one GameMaker is expecting for that IDE release and so it will try to repair your install for you.

Also, even if you have downloaded the runtimes .zip off the website, GameMaker still needs an active internet connection in order to access the runtimes feed and confirm that the files you have downloaded are correct, so the message about your computer being offline and no runttime being installed _is_ correct.

If you leave 201 installed, then 202 will likely be detected just fine (really, it should have worked on a second IDE startup anyway, but I suspect you manually deleting 201 each time meant you never got to installing 202).

202 is only required if you need the fix for https://github.com/YoYoGames/GameMaker-Bugs/issues/5914 - otherwise 201 contains everything else, so you may not even need to "replace" 201 with 202.

I can see your log appears to indicate 201 is downloading and installing okay via GameMaker anyway (when you're online).

**Comment by SBogatz** [comment]
Great!-  thank you so much :)
Steve
    On Wednesday, May 29, 2024 at 06:26:36 AM EDT, Daniel Cleaton ***@***.***> wrote:   

 


I have edited the guide at https://help.gamemaker.io/hc/en-us/articles/115001342672-How-To-Download-GameMaker-s-Runtime-Tools-Without-Using-the-IDE to better explain that this is the case.
