### ISSUE TITLE
Gaussian Blur effect flips game vertically

### ISSUE THREAD

**Issue by Schwarzgamescom** [YoYoGames/GameMaker-Bugs#6113]
### Description
Using the gaussian blur effect on an effect layer causes all layers that are blurred to be vertically flipped. 
Lowering the intensity of the effect shows two separate images, one flipped and one correct.

### Steps To Reproduce
Add an effect layer in your room with the Gaussian Blur effect.
Start the game and all affected layers will be blurred and flipped vertically.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.202

### Which operating system(s) are you seeing the problem on?
Mac 14.5

### Which platform(s) are you seeing the problem on?
Android, GX.games, iOS, macOS

[51fdad87-ea4b-4fb0-8d88-867db75fc0fd](https://api.gamemaker.io/api/github/downloads/51fdad87-ea4b-4fb0-8d88-867db75fc0fd)

**Comment by JonnoRobson** [comment]
This issue is caused by the surface texture contents being flipped on platforms using OpenGL due to differences in texture coordinates. I've modified the effect script and shaders so that the vertical flipping is handled correctly - this fixes the issues and should leave other non GL platforms unaffected.
