### ISSUE TITLE
Keep previous settings when updating extensions.

### ISSUE THREAD

**Issue by Foxtrio** [YoYoGames/GameMaker-Bugs#6174]
### Is your feature request related to a problem?

When updating extensions, their settings are rewritten. This means that I'd need to update all my settings(AD IDs, Firebase configs etc.) - and multiply that if you have multiple Game Maker Configurations in your game.

### Describe the solution you'd like

Simply introduce a mechanism where updating extensions would carry the options from the previous version.

**Comment by stuckie** [comment]
We have Extension Options that should be kept when updating your extension in your project.
Is there a specific extension, or process that you are doing that is causing them to be lost?

Please submit a new ticket with more information of what you are seeing so that we can diagnose what is going on.
Thanks.
