### ISSUE TITLE
font_get_info() omits kerning information for some glyphs

### ISSUE THREAD

**Issue by Mtax-Development** [YoYoGames/GameMaker-Bugs#6278]
### Description

While attempting to write an equivalent of GameMaker `draw_text()` rendering for use through a Vertex Buffer, it came to my attention that it is impossible to exactly replicate its positioning by basing on data returned by `font_get_info()`, as it omits information that is otherwise available in the `.yy` properties file of the font. This appears to be the case only for some glyphs and it does not appear that using a different configuration for the font affects it.

***

Example below illustrates the difference on the "f" glyph (`ord 102`) information for the font Arial Black:

`"kerningPairs"` property in the `.yy` file:
```
    {"amount":2,"first":102,"second":32,},
    {"amount":4,"first":102,"second":33,},
    {"amount":-2,"first":102,"second":44,},
    {"amount":-3,"first":102,"second":46,},
    {"amount":4,"first":102,"second":63,},
    {"amount":-1,"first":102,"second":101,},
    {"amount":1,"first":102,"second":102,},
    {"amount":-1,"first":102,"second":111,},
    {"amount":4,"first":102,"second":8217,},
    {"amount":4,"first":102,"second":8221,},
```

Data returned by `font_get_info()`:
```
    "f":{
      "x":814.0,
      "y":245.0,
      "char":102.0,
      "w":87.0,
      "kerning":[
        0.0,
        0.0
      ],
      "h":241.0,
      "offset":1.0,
      "shift":67.0
    }
```

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

Please ensure you include the font as well.

**Comment by Mtax-Development** [comment]
I originally did not attach any project, because the issue is project-agnostic and it can be replicated by having the IDE create an `.yy` file for the font I mentioned and inspecting its data and data returned by `font_get_info()` for that font.

I have attached project with exactly that done below.

[Example Project](https://github.com/user-attachments/files/15873425/font_get_info.omits.kerning.information.zip)

**Comment by stuckie** [comment]
We request a project to ensure we see exactly what you see, in how you've configured the project. As while we could follow the steps to recreate it, there could be additional settings missed that mean that we create a slightly different project to what you have, and therefore not see the issue you have, or something else.
Additionally, we can get a lot of bug reports, and stopping to create a project reduces our time to actually fix them.
If you have sent us a project, we can immediately test it in our source builds to see if the issue has been fixed, or to immediately hit the issue to fix it. Otherwise, we are needing to install the exact versions you have used, create a project, ensure that it triggers the same issues that you are reporting, and only then can we start work on fixing it.

Thanks!
