### ISSUE TITLE
In-Game: [Android] asset_add_tags() does not add tags onto rooms

### ISSUE THREAD

**Issue by Notlea** [YoYoGames/GameMaker-Bugs#6282]
### Description
I've made a game state machine that checks current room tag on Room Start event and assigns a state variable. I'm assigning that tag in room Creation code. While working fine on Windows target, it doesn't work on Android.  

### Steps To Reproduce
1. Start GameMaker and import [test-asset_add_tags.zip](https://github.com/user-attachments/files/15887999/test-asset_add_tags.zip)
2. Run it for Android and observe when the game is in the menu room (green background) or level room (black background) only garbled text is ever drawn to the screen
3. (Optional) Run the project for Windows VM or YYC and observe this time the proper tags for each room is shown ("Menu Room" and "Level 01").

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Android

[7aeb85b2-5843-4711-b173-95d0d877c66d](https://api.gamemaker.io/api/github/downloads/7aeb85b2-5843-4711-b173-95d0d877c66d)

**Comment by YYDan** [comment]
The bug is not the room creation code not being performed, or even your custom function being called - if you add a simple:

`show_debug_message("Hello from " + string(_room_id));`

into your function, then you will see this is working just fine on Android also (and gets the correct values you're expecting):

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/8c91fe24-fb0c-469b-bfe3-9d5c5d9eb8cf)

**Comment by YYDan** [comment]
The issue is simply the asset_add_tags() function on Android.

**Comment by YYDan** [comment]
Made a small sample which shows this much more clearly: 
[test-asset_add_tags.zip](https://github.com/user-attachments/files/15887999/test-asset_add_tags.zip)

Will edit the title and the steps higher up to account for the correct information.
