### ISSUE TITLE
SDF Fonts and Vertex Batch

### ISSUE THREAD

**Issue by Patchy-DaYo** [YoYoGames/GameMaker-Bugs#6336]
### Description
I noticed that my vertex batch numbers recently increased dramatically and I quickly found out the reason why: each call to draw_text() breaks the batch when using an SDF font.

I display my characters one by one to simulate an animation in a chat (pretty standard stuff). For that reason, if I display 200 characters in a text paragraph, the result is 200 additional batch breaks per frame. I can confirm that simply disabling the SDF option in the font solves the issue, it's not a mater of changing the color, or effects. I suspect that this is simply because SDF fonts use their own shader internally.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.202

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

### Which platform(s) are you seeing the problem on?
Windows

[ccf7c6e7-622c-46fe-a2fd-5b4a88cf6281](https://api.gamemaker.io/api/github/downloads/ccf7c6e7-622c-46fe-a2fd-5b4a88cf6281)

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

Alternatively, you can attach it directly if it's something you are willing to share publicly, or upload via something like Google Drive so we can request access to keep it private. The ticket can then simply be re-opened.

We request a project to ensure we see exactly what you see, in how you've configured the project. As while we could follow the steps to recreate it, there could be additional settings missed that mean that we create a slightly different project to what you have, and therefore not see the issue you have, or something else.
Additionally, we can get a lot of bug reports, and stopping to create a project reduces our time to actually fix them.
If you have sent us a project, we can immediately test it in our source builds to see if the issue has been fixed, or to immediately hit the issue to fix it. Otherwise, we are needing to install the exact versions you have used, create a project, ensure that it triggers the same issues that you are reporting, and only then can we start work on fixing it.

Thanks!
