### ISSUE TITLE
array_sort is broken in gx.games target

### ISSUE THREAD

**Issue by Ailwuful** [YoYoGames/GameMaker-Bugs#6348]
### Description
I'm using array_sort to sort an array that contains structs with a variable called index which holds a number. Using array_sort based on that number works correctly on Windows target, but it's not sorting the array correctly in the gx.games target.
The numbers in index are all integers and it's just trying to sort by highest number.

### Steps To Reproduce
I created an object, I put this in create:
```
array = [
	{
		index : 0,
		name : "Number1"
	},
	{
		index : 1,
		name : "Number2"
	},
	{
		index : 2,
		name : "Number3"
	}
]
```

I tested by doing this in step event:

```
if (keyboard_check_pressed(vk_space)) {
	array_sort(array, function(elem1, elem2) {
		return sign(elem1.index < elem2.index);
	});
}

if (keyboard_check_pressed(vk_backspace)) {
	array_foreach(array, function(_index) {
		_index.index = irandom(10);
	});
}

```
and took a look at the draw with this:
```
var i = 0;
repeat(array_length(array)) {
	draw_text(20,20 + i * 20, [array[i].name, array[i].index]);
	i++;
}
```

the array doesn't get sorted correctly in gx.games

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
GX.games

[018cc542-a025-480b-a44d-bdb98b9e4edf](https://api.gamemaker.io/api/github/downloads/018cc542-a025-480b-a44d-bdb98b9e4edf)

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

Alternatively, you can attach it directly if it's something you are willing to share publicly, or upload via something like Google Drive so we can request access to keep it private. The ticket can then simply be re-opened.

We request a project to ensure we see exactly what you see, in how you've configured the project. As while we could follow the steps to recreate it, there could be additional settings missed that mean that we create a slightly different project to what you have, and therefore not see the issue you have, or something else.
Additionally, we can get a lot of bug reports, and stopping to create a project reduces our time to actually fix them.
If you have sent us a project, we can immediately test it in our source builds to see if the issue has been fixed, or to immediately hit the issue to fix it. Otherwise, we are needing to install the exact versions you have used, create a project, ensure that it triggers the same issues that you are reporting, and only then can we start work on fixing it.

Thanks!

**Comment by Ailwuful** [comment]
So... I made a mistake with the way I used the function in which I was returning a sign(boolean check) instead of math like I intended.
But regardless, in the windows target I did consistently get the results that I expected, and in gx.games it behaved strangely. But probably because of the true/false thing.
So... not as broken as I thought, but still weird.
