### ISSUE TITLE
Code Editor 2: GM freeze when opening a Note if the Inspector is collapsed

### ISSUE THREAD

**Issue by yerumaku** [YoYoGames/GameMaker-Bugs#6356]
### Description

[ui.log](https://github.com/user-attachments/files/15919549/ui.log)

### Steps To Reproduce

1. Start GameMaker
2. Open Project 
3. Enable CE2
4. Collapse right panel with Inspector
5. Open exist note
6. See the issue - IDE freeze

(If you switch to CE1, the inspector behaves in the usual way)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yerumaku** [comment]
It is also annoying that if you close the inspector, it opens again, if you move the inspector to another tab, it constantly opens when opening a file, this prevents navigation through the project files.

**Comment by zreedy** [comment]
Cannot reproduce, please attach a project with the offending Note.

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

Alternatively, you can attach it directly if it's something you are willing to share publicly, or upload via something like Google Drive so we can request access to keep it private. The ticket can then simply be re-opened.

We have requested a project to ensure we see exactly what you see, in how you've configured the project. As while we could follow the steps to recreate it, there could be additional settings missed that mean that we create a slightly different project to what you have, and therefore not see the issue you have, or something else.
Additionally, we can get a lot of bug reports, and stopping to create a project reduces our time to actually fix them.
If you have sent us a project, we can immediately test it in our source builds to see if the issue has been fixed, or to immediately hit the issue to fix it. Otherwise, we are needing to install the exact versions you have used, create a project, ensure that it triggers the same issues that you are reporting, and only then can we start work on fixing it.

Thanks!
