### ISSUE TITLE
The project file does not open if the code editor 2 is active

### ISSUE THREAD

**Issue by yerumaku** [YoYoGames/GameMaker-Bugs#6357]
### Description

[ui.log](https://github.com/user-attachments/files/15919610/ui.log)

### Steps To Reproduce

1. Start GameMaker
2. Enable CE2
3. Open project
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yerumaku** [comment]
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/21119896/af51a3e4-2dba-487e-9f77-e45a5697ff3d)

2024.600.0.562 - The version does not have this problem

**Comment by yerumaku** [comment]
If you switch to CE1 and open project in current session - infinity analyzing:
<img width="550" alt="Снимок экрана 2024-06-20 в 23 32 49" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/21119896/f4230d8b-dadb-4190-821b-eeb480f2e8e6">

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

Alternatively, you can attach it directly if it's something you are willing to share publicly, or upload via something like Google Drive so we can request access to keep it private. The ticket can then simply be re-opened.

We request a project to ensure we see exactly what you see, in how you've configured the project. As while we could follow the steps to recreate it, there could be additional settings missed that mean that we create a slightly different project to what you have, and therefore not see the issue you have, or something else.
Additionally, we can get a lot of bug reports, and stopping to create a project reduces our time to actually fix them.
If you have sent us a project, we can immediately test it in our source builds to see if the issue has been fixed, or to immediately hit the issue to fix it. Otherwise, we are needing to install the exact versions you have used, create a project, ensure that it triggers the same issues that you are reporting, and only then can we start work on fixing it.

Thanks!
