### ISSUE TITLE
gpu_set_zwriteenable not working properly on XboxOne/SeriesX but works on Switch/PlayStation

### ISSUE THREAD

**Issue by DJLink** [YoYoGames/GameMaker-Bugs#6417]
### Description

So we have this game that works ok on Switch and PlayStation, but incorrectly on One/SeriesX. We identified the issue as part of gpu_set_zwriteenable because if we disable those 2 calls on PlayStation we see the same visual artifact, so we are assuing Xbox is not properly doing what it should on those 2 calls

### Steps To Reproduce

1. Start GameMaker
2. Compile game to Xbox
3. Start any track
4. See the issue
5. does not happen on other platforms
![IMG_6630](https://github.com/YoYoGames/GameMaker-Bugs/assets/423769/6b854844-172b-479d-a052-e670f43eb2b5)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

Xbox (GDK)

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DJLink** [comment]
To add to this, I found out that when gpu_set_zwriteenable I also had to call gpu_set_ztestenable. This fixes the issue on Xbox and still works on the other platforms. The odd thing is that gpu_set_zwriteenable alone works on Switch/PlayStation, so while my issue is solved for this, I still think there's inconsistency the way things are working.

**Comment by stuckie** [comment]
Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue to ensure we see exactly what you see and then learn why this problem is caused.

Please report this issue again, but ensure you have a suitable project open at the time you open the bug reporter and that you allow GameMaker to include the project.

Thanks!

[Why Have You Asked Me For A Sample?](https://help.gamemaker.io/hc/en-us/articles/13150754375453#h_01J15CZA1TP1FH04XQE2P18AAG)

**Comment by DJLink** [comment]
> Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue to ensure we see exactly what you see and then learn why this problem is caused.

Forgot to update the issue, but I did tried to upload but the links are showing up as public downloads, I can't have this. We used to have a private way to share them with Yoyo but now via github that seems impossible? if you noticed I have 2 history changes on OP because I uploaded the file and it was showing up for public download which is not acceptable.
What other ways are to do so?

**Comment by stuckie** [comment]
All projects attached through the IDE's bug reporter are only accessible via GameMaker staff.

**Comment by DJLink** [comment]
> All projects attached through the IDE's bug reporter are only accessible via GameMaker staff.

I tried but 
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/423769/ea9ffac9-51e0-4a6d-b421-cbe6b564bb93)

**Comment by YYDan** [comment]
Can you contact the Helpdesk via the Contact Us link on the Help menu inside GameMaker, please? They can sort out your permissions there and then you will be able to upload private console issues via the IDE. That's an account issue and I suspect you also can't access the console support docs, etc., right now.

As Steven said above and as the bug reporter dialog itself says, **all** files sent to us from inside the IDE are always only available to us staff. It doesn't matter if you set the issue visibility dropdown to private (and get that error above) or not (which obvs works for you already) - but as this is a console-specific bug it really should be private anyway and so I recommend you still contact the Helpdesk, rather than sending a new public issue with your project privately attached.
