### ISSUE TITLE
Code editor 2: Trying to type the \" escape character at the end of a string will attempt to close off the string instead of typing the "

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6429]
### Description
When you type ", a 2nd " is automatically added. If you press " twice in a row, instead of adding a 3rd ", it skips over the 2nd ". This is definitely intended.
However, it still happens if you try to do this `"\""` to make a string with a " inside. This leaves you with an unterminated string unless you notice and press " again.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/6b3cd87f-1412-4f55-a744-d2581d4f7d7a

### Steps To Reproduce
Type a ", then a \, then " again.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[025d50a6-1dae-498f-a78f-5e8ffb4588c9](https://api.gamemaker.io/api/github/downloads/025d50a6-1dae-498f-a78f-5e8ffb4588c9)

**Comment by zreedy** [comment]
This is expected behavior. Typing `"` once more will insert the terminating quote. Token Pairs such as `{ }`, `( )`, `" "`, etc. overwrite tokens if a matching pair is found. This is to improve typing speed by both allowing for the autocompletion of token pairs and to avoid having to skip over the autocompletion with the arrow keys when typing longer lines of code.

**Comment by mgeddesGM** [comment]
closing as expected as per developer's comment
