### ISSUE TITLE
In-Game: [Windows] keyboard_check_pressed() does not work for key 21 when using Korean keyboard layouts and IME

### ISSUE THREAD

**Issue by MatthewStone218** [YoYoGames/GameMaker-Bugs#6493]
### Description

keyboard_check_pressed dosen't work for key 21.
only keyboard_check work for it.

[bug report.zip](https://github.com/user-attachments/files/16077144/bug.report.zip)

P.s
keyboard_check(21) dose not work properly too.

it also returns 1 after releasing the button 21.

### Steps To Reproduce

1. Start GameMaker
2. execute keyboard_virtual_hide();
3. execute `if(keyboard_check_pressed(21)){show_message(123)}`. It will not work.
4. execute `if(keyboard_check(21)){show_message(123)}`. It will work.
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yoyo-danielc** [comment]
@MatthewStone218 What keyboard/layout are you using to press "key 21"? MSDN suggests it is "IME Kana mode", assuming you are on Windows.

**Comment by MatthewStone218** [comment]
I'm using common korean keyboard

**Comment by yoyo-danielc** [comment]
I've done a bit of digging and what appears to be happening here, is that key 21 (Alt Gr on a UK keyboard with Korean layout selected) activates an IME mode, so we receive a `WM_KEYDOWN` message for key code `VK_PROCESSKEY` instead of 21, when the key is released we get a `WM_KEYUP` message for key 21 which triggers a spurious key up event in GM since we ignored the `VK_PROCESSKEY` key.

You can call `keyboard_virtual_hide()` to disable IMEs during gameplay (i.e. when not reading text input) and key 21 will be handled as a normal key instead, then use `keyboard_virtual_show()` to re-enable them if/when the player is entering text.

Does this resolve your issue? I will look at fixing the spurious key up event when is raised when the IME key is released in the mean time.

**Comment by yoyo-danielc** [comment]
Spurious key up event is fixed on 2024.10 branch.

**Comment by YYDan** [comment]
Presumably this would affect far more keys/languages than just this key 21 when using Korean?

**Comment by alicemoretti** [comment]
This is fixed for me on Beta IDE v2024.1100.0.626  Runtime v2024.1100.0.652 for key 21. 
@yoyo-danielc @MatthewStone218  is it impacting any other keys?

**Comment by sihammill** [comment]
Reopening as Key 21 is not working, tested by myself and @Emc1923

**Comment by yoyo-danielc** [comment]
@sihammill can you confirm your testing method?

**Comment by sihammill** [comment]
@yoyo-danielc sorry for the delay in getting back to you, I didn't realise you had responded.

I run the attached project, I don't have an Alt Gr key but Ctrl + Alt apparently is a substitute for it, I get no message stating '123' using either keyboard_check_pressed or keyboard_check.

**Comment by yoyo-danielc** [comment]
@sihammill did you insert a call to `keyboard_virtual_hide()` as per https://github.com/YoYoGames/GameMaker-Bugs/issues/6493#issuecomment-2246049264?

The only thing changed with this fix is that the key up event is no longer generated, since there was no preceding key down event for IME activation.

**Comment by sihammill** [comment]
@yoyo-danielc yes the `keyboard_virtual_hide()` was called in the create event prior to running the project. With the Korean IME off, it's doesn't appear to work but with it on, it does show the 123 message.

I wasn't able to do this myself since I don't have a dedicated Alt Gr key on my keyboard but @SamTHodson managed to get the above result.

**Comment by yoyo-danielc** [comment]
Ah I see the test project was updated... `kor_input.yyz` displays the 123 message for me just fine in the current beta when I press Alt+Gr with the Korean keyboard layout selected.

**Comment by YYDan** [comment]
As above, this works just fine for me on a UK keyboard set to use the Korean language pack in Windows and when I press the Alt+GR key in-game:

![Image](https://github.com/user-attachments/assets/44c620a0-c2bc-4260-88e0-f6369677a211)

Note that changing back to English (even while the game is running) immediately stops the key check from succeeding, so I know that the key code is the correct one we want.

Verifying in IDE v2024.1100.0.687  Runtime v2024.1100.0.708
