### ISSUE TITLE
Manual Content: 3D Audio becomes extremely loud in 2024.6, when near the centre of the emitter

### ISSUE THREAD

**Issue by OrangeeInkling** [YoYoGames/GameMaker-Bugs#6526]
### Description

When using 3D audio, the audio gets extremely loud until it cuts off or goes into static when getting closer and closer to the emitter, it didn't do this in the previous version of GameMaker. In the previous version, it worked as expected where the audio would slowly fade in when getting closer to the emitter and would have the correct gain and volume.

### Expected Change

Audio should be normal when approaching the center of the emitter

### Steps To Reproduce

1. Start GameMaker
2. Create an object that works as a 3D audio emitter.
3. Use the "audio_falloff_exponent_distance" model for the audio falloff model
4. audio_play_sound_at(sound, x, y, 0, 800, 250, 5, true, 0, 0.2) (replace sound with a 3D sound)
5. Make a listener object that can go near the object and hear the audio get extremely loud and eventually cut off
6. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

**Comment by toby-yoyo** [comment]
This isn't a bug.

This is a documented side effect of the exponential component of the calculation. This can be seen in the manual page for [`audio_falloff_set_model`](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Audio/audio_falloff_set_model.htm), which contains the following diagram:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/98745055/63d8b916-7ee5-4ddb-93c6-2c0dc134d45a)

There are `_clamped` and `_scaled` variants of the exponential falloff model which both avoid this side effect, so perhaps one of those models would be more suitable for your use case.

Additionally, the falloff parameters used should be reviewed:
- The reference distance (800) is greater than the max distance (250). The max distance should be equal to or greater than the reference distance.
- The falloff factor (5) is a huge contributor to blowing up the resultant gain in this case. Setting this to something less impactful (e.g. 1), will do a lot to even out the gain scaling (assuming the falloff model isn't changed).

The reason this is only being heard now is because we removed a previous cap on source gains in 2024.6 - that was done as part of addressing https://github.com/YoYoGames/GameMaker-Bugs/issues/5580.

**Comment by YYDan** [comment]
Need to review what the manual says, following this change in 2024.6.0.
