### ISSUE TITLE
font_enable_effects and glow blending

### ISSUE THREAD

**Issue by Patchy-DaYo** [YoYoGames/GameMaker-Bugs#6560]
### Description
The glowColour property specified in font_enable_effects() is blending with the text color. So for example, setting the text color to blue and the glow color to white results in a blue glow. Is that supposed to happen or is it a bug?

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.0.157 Runtime v2024.4.1.202

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

[eb81919f-3c61-4712-99f7-2b68fd2430ed](https://api.gamemaker.io/api/github/downloads/eb81919f-3c61-4712-99f7-2b68fd2430ed)

**Comment by stuckie** [comment]
Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue to ensure we see exactly what you see and then learn why this problem is caused.

Please report this issue again, but ensure you have a suitable project open at the time you open the bug reporter and that you allow GameMaker to include the project.

Thanks!

[Why Have You Asked Me For A Sample?](https://help.gamemaker.io/hc/en-us/articles/13150754375453#h_01J15CZA1TP1FH04XQE2P18AAG)
