### ISSUE TITLE
Code Editor 2: Importing project caused server issues and resulted in grey colouring 

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#6701]
### Description

When verifying #5462, I noticed that after importing the project I was met with grey colouring. This fixed itself after restarting the IDE and project, and it appears from the ui.log that there was an error on the server on import. 

[ui.log](https://github.com/user-attachments/files/16252922/ui.log)

https://drive.google.com/file/d/1XklcoAJE0aAS7v2dUhkM65xsAl35kxC3/view?usp=sharing

### Steps To Reproduce

1. Ensure CE2 is enabled in GM.
2. Download and unzip attached project.
3. Double click on the project in the explorer to open.
4. Go to oPlayer and see issue.
5. Close IDE and reopen project and see colouring has come back.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by zreedy** [comment]
Fixed. Client side ProjectManager now dispatches a message packet which specifies if an upgrade was performed, once the upgrade is serialized back to disk a recovery OpenWorkspace command is dispatched to the server to indicate that it is safe for it to reload the project (which is probably has already or will soon fail to load). Server will log but not report to the client when a project fails to load due to a version mismatch now.

**Comment by scott-dunbar** [comment]
Issue appears to be resolved in  IDE v2024.1100.0.643  Runtime v2024.1100.0.664
