### ISSUE TITLE
Crash in html5

### ISSUE THREAD

**Issue by MatthewStone218** [YoYoGames/GameMaker-Bugs#6718]
### Description

The current version has an error when playing the game in html5.
It doesn't occur in 2024.4 version

contact us package-please give your email or other ways to contact. I can't upload the package as public because it's our company project.
[index 백업.zip](https://github.com/user-attachments/files/16260395/index.zip)

### Steps To Reproduce

1. Start GameMaker with the attached project.
2. build in html5.
3. change the index.html file as I attached.
4. upload it on ftp.
5. play the game.
6. click the start button and don't do anything.
7. after a few seconds, the game will make an error.
8. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you seeing the problem on?

HTML5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue to ensure we see exactly what you see and then learn why this problem is caused.

Please report this issue again, but ensure you have a suitable project open at the time you open the bug reporter and that you allow GameMaker to include the project.

Also note that ***all projects attached via the IDE's bug reporter are private and can only be accessed by GameMaker staff***

Thanks!

[Why Have You Asked Me For A Sample?](https://help.gamemaker.io/hc/en-us/articles/13150754375453#h_01J15CZA1TP1FH04XQE2P18AAG)
