### ISSUE TITLE
Play a "create_stream_sound" generate errors in sound queue that block the other sounds from play

### ISSUE THREAD

**Issue by DarkTiger** [YoYoGames/GameMaker-Bugs#6727]
### Description

Play a "create_stream_sound" generate errors in sound queue that block the other normal sounds from play. See in sound debug overlay. 
This bug has been introduced with 2024.6

### Expected Change

Play a "create_stream_sound" doesn't block normal sounds from play

### Steps To Reproduce

1. Start GameMaker
2. Create a sound with "create_stream_sound" and add code to play it with a key.
3. Add a sound in project and a code to play it with another key.
4. Play the stream sound a few times and after play the normal sound a few times.
5. See the issue: the normal sound lag and get blocked from play.
6. See in audio debug overlay (white none sounds)

![image](https://github.com/user-attachments/assets/ae18c6ce-3533-4049-8bc1-c6c6d18ced22)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by toby-yoyo** [comment]
Please [provide an example project](https://help.gamemaker.io/hc/en-us/articles/13150754375453-Submitting-a-Bug-Report-What-Does-It-Contain#h_01J15CZA1TP1FH04XQE2P18AAG) which shows the issue.

I've tested this based on the repro steps above and cannot reproduce the problem. Here is the project I used: [gmb-6727-x.zip](https://github.com/user-attachments/files/16274650/gmb-6727-x.zip)

**Comment by DarkTiger** [comment]
> Please [provide an example project](https://help.gamemaker.io/hc/en-us/articles/13150754375453-Submitting-a-Bug-Report-What-Does-It-Contain#h_01J15CZA1TP1FH04XQE2P18AAG) which shows the issue.
> 
> I've tested this based on the repro steps above and cannot reproduce the problem. Here is the project I used: [gmb-6727-x.zip](https://github.com/user-attachments/files/16274650/gmb-6727-x.zip)

I have tested you project and the problem not exists with file from includes. I have loaded an external sound with disabled file system sandbox and it exists.
You need to spam the stream audio play until remain white row in debug ui and after play the normal sound.

This problem exists only from the version 2024.6

**Comment by stuckie** [comment]
This is why we ask for projects, to ensure we are looking at the same thing you are.
Can you please attach a project that is configured to show what you are seeing.

**Comment by DarkTiger** [comment]
> [toby-yoyo](/toby-yoyo)

The **[toby-yoyo](https://github.com/toby-yoyo)** project is fine, it need to change the path of the sound with an external sound outside of "file system sandbox" (for example c:/sound.ogg)

**Comment by DarkTiger** [comment]
Were you able to reproduce the problem?
Thanks

**Comment by toby-yoyo** [comment]
Unfortunately I'm still unable to reproduce the issue, having disabled the filesystem sandbox and moved the streamed file out of the sandboxed area to the suggested location.

**Comment by toby-yoyo** [comment]
Linking this issue to https://github.com/YoYoGames/GameMaker-Bugs/issues/6755 as they seem to be related. I've now managed to reproduce the issue by a different method.

**Comment by toby-yoyo** [comment]
Fixed an issue where ogg streams were not always completely deinitialised before their associated voices were deactivated.

This issue is easily reproducible using this test project: [gmb-6727-x.zip](https://github.com/user-attachments/files/16346677/gmb-6727-x.zip)
- Open and run the project
- Hit '1' to flood the audio engine.
    - Observe various error messages being printed to the console. 
- After a few seconds hit '2' to stop playing new sounds.
    - Most of the time there will be voices stuck in a playing state (white text).
    - Most of the time there will be voices that haven't been fully deinitialised (buffer id not -1, sound name visible).
    - Sometimes there will be voices that never finish playing.
- Expected behaviour is that no error messages are printed to the console, and that all voices eventually finish playing and are deinitialised when '2' is pressed.

**Comment by toby-yoyo** [comment]
@shichen85 I don't think it would be possible to do this for this particular issue. 

The reason the audio functions won't pick it up is because they are geting their info from a higher-level layer of the audio engine which wasn't functioning correctly due to a misinterpretation of info from a lower-level layer.

The info on the debug view is pulled straight up from that lower-level layer, which is why it happens to be better at showing some symptoms of the issue in this case. However, that layer is not exposed to GML.

**Comment by Emc1923** [comment]
Verified in  IDE v2024.800.0.603  Runtime v2024.800.0.625
