### ISSUE TITLE
In-Game: [Android] "Edge detection" layer effect shows missing lines of pixels on some devices

### ISSUE THREAD

**Issue by KasparTheAhv** [YoYoGames/GameMaker-Bugs#6741]
### Description

**The issue is fully discussed here:**
https://forum.gamemaker.io/index.php?threads/half-of-the-view-is-missing-lines-of-pixels.113178/#post-677709

**regarding:** `_filter_edgedetect_shader.fsh`

**TL,DR:**
On android, with a 1920x1080px size screen. The filter starts introducing missing lines of pixels just after half of the view.
Doesn't matter if you zoom in my game. The left 50% of the screen processes fine. But the right 50% of the screen is missing pixels.

My project/game that I've been working on for +2 years now, heavily relies on this effect. 
I've just finished the first chapter and would like to start advertising my game. 
But I can't do this when some of my mobile gamers would face such ugly/broken graphics. 

Can you please look into this and help me fix this issue?
I don't want to scrap all the work + money spent on your platform just to now even release the game because of a bugged shader effect. 

Weirdly enough, 

this bug doesn't happen on: "Redmi Note 8 Pro  2340x1080 screen",  "Redmi Note 13 Pro 2400x1080 screen" 

but it happens on: "Redmi Note 4 Pro 1920x1080 screen" and a testers "2280x1080 screen"

Also doesn't happen on windows export and emulated phone screens with 1920x1080

![1718057346197](https://github.com/user-attachments/assets/3ccd50d9-1a0e-40fc-84a9-5cb8f2f9eaf9)
![Screenshot_20240715-100137_CyberCat - Catnip Trip](https://github.com/user-attachments/assets/b545bd1c-442f-4d3e-8e79-8085caff93fc)

### Expected Change

For the effect to work properly on all screen resolutions and not introduce missing vertical lines of pixels after 50% of the screen. 

### Steps To Reproduce

1. Start GameMaker
2. Make a room with a tileset and a few pixelart objects.
3. Apply edge detection filter to the entire room along with the objects.
4. Export to android.
5. Open up the game on 1920x1080 screen resolution phone.
6. See if the left 50% part of the screen is rendered correctly under the shader and if the right 50% has missing vertical lines of pixels. 

Alternatively:
1. Download my free game: https://play.google.com/store/apps/details?id=com.randomprimategaming.cybercat
2. Open up the game on 1920x1080 screen resolution phone.
3. Enter any level/game room (excluding menu because there I haven't have set dynamic scaling yet. )
4. See if the left 50% part of the screen is rendered correctly under the shader and if the right 50% has missing vertical lines of pixels. 
5. Use the zoom in and out feature next to the pause and tutorial book icon. ( right up of the screen )
6. Witness the same problem of missing lines of pixels regardless of the zoom level. 

[contactUsZip.zip](https://github.com/user-attachments/files/16279556/contactUsZip.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which platform(s) are you having trouble building this project for?

Android

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by JonnoRobson** [comment]
Tested this issue and was able to reproduce on an Android device with a 2160x1080 screen. Issue didn't reproduce on a separate device with a 1920x1200 screen.

The issue is due to insufficient floating point precision when calculating the offset texture coordinates. Calculating the offset by first using unnormalised texture coordinates and then normalising the coordinates before sampling fixes the issue for me on the device that was reproducing the issue. The output on the device that was not reproducing the issue remains unchanged.

I've push the fix to the shader and it should be available in the next BETA release. If you don't want to wait for the next release you can also try out the fix yourself by finding the edge detection filter your IDE is building from (C:\ProgramData\GameMakerStudio2\Cache\runtimes\<current runtime>\bin\FiltersAndEffects\_filter_edgedetect) and modifying the .fsh file. 

Replace lines 13-18 with:
```
        vec2 fragcoord = v_vTexcoord * gm_pSurfaceDimensions;
	
	vec4 texcol = texture2D( gm_BaseTexture, v_vTexcoord );
	vec4 texcol_right = texture2D( gm_BaseTexture, vec2(fragcoord.x + 1.0, fragcoord.y) / gm_pSurfaceDimensions );
	vec4 texcol_down = texture2D( gm_BaseTexture, vec2(fragcoord.x, fragcoord.y + 1.0) / gm_pSurfaceDimensions );
```

**Comment by KasparTheAhv** [comment]
Wow! I'll try it as soon as I can!

amazing job if this really fixes it!

**Comment by KasparTheAhv** [comment]
So me and my friend tried out the newer version of the edge detect shader. 


For me, it's still working fine, for him, it's working better, but not completely right:
![missing pixels with edge detect shader](https://github.com/user-attachments/assets/9f2e3c1a-df38-4973-8966-b8832d008ab2)

Here's their comment:
![image](https://github.com/user-attachments/assets/8beef4bf-e58d-46be-94c8-d312ee2abdb0)

And here's my zooming code, tho I don't think it's the culprit. 
`// kui onjumal zoom tase
if !(global.magnifyZoom)
{
    // Turning into god zooms out
    if (oGodZoom)
    {
        if (zoomLevel<2) {zoomLevel+=0.02;} else {zoomLevel=2;}   
    } else { // turning back to normal zoom in again
        if (zoomLevel>1) {zoomLevel-=0.04;} else {zoomLevel=1;}   
    }
}

// Update view size
zoomXTo = cam_default_w * zoomLevel;
zoomYTo = cam_default_h * zoomLevel;
temp_cam_w += (zoomXTo - camera_get_view_width(cam)) / 5;
temp_cam_h += (zoomYTo - camera_get_view_height(cam)) / 5;
var temp_cam_w_half = temp_cam_w *0.5;
var temp_cam_h_half = temp_cam_h *0.5;
camera_set_view_size(cam, (temp_cam_w), (temp_cam_h));

// Update destination
if (instance_exists(follow)) {
    xTo = follow.x;
    yTo = follow.y;
}

// Update object position
x += (xTo - x) / 5;
y += (yTo - y) / 5;

// Keep within room
x = clamp(x, temp_cam_w_half, room_width-temp_cam_w_half);
y = clamp(y, temp_cam_h_half, room_height-temp_cam_h_half);

// Update camera view
viewposx=floor(x-temp_cam_w_half);
viewposy=floor(y-temp_cam_h_half);
camera_set_view_pos(cam,viewposx,viewposy);
camera_set_view_border(cam,defborderX*zoomLevel,defborderY*zoomLevel);`

And here's mu setup object for managing dynamic resolution:
`/// SETUP OBJECT IN THE FIRST ROOM OF THE GAME

global.gameWidth=display_get_width();
global.gameHeight=display_get_height();

var ideal_height=360;
var aspect_ratio =global.gameWidth/global.gameHeight;

var ideal_width=ideal_height*aspect_ratio;

if (ideal_width & 1)
{
    ideal_width++;
}

// Ideal camera size
global.idealW=floor(ideal_width);
global.idealH=floor(ideal_height);


// set viewports only GAME ROOMS to match desired cam size.
// In my example picture is the skin selection room where the viewport/cam size is fixed to 800/400.
// Should have given an example image from within the room where the proper calculations have been made for the camera size/viewport
// but hopefully you can trust me, the result is exactly same. Even worse when moving around.
// half of the screen looks fine, the other half is epileptic

for (var i = 0; i < 31; i++)
{
var whatroom="Room"+string(i);
var roomid=asset_get_index(whatroom);
room_set_viewport(roomid,0,true,0,0,global.idealW,global.idealH);
}

// Set window size:
window_set_size(global.gameWidth,global.gameHeight);
display_set_gui_size(global.gameWidth,global.gameHeight);
surface_resize(application_surface,global.gameWidth,global.gameHeight);
gpu_set_texfilter(false);`

**Comment by YYDan** [comment]
Reopening per the above comment from the original reporter.

**Comment by JonnoRobson** [comment]
There were issues with interpolating the texture coordinates across the full screen on Android, meaning certain rows/columns of screen pixels were sharing the same texture coordinates when applying the effect. If a colour edge fell on one of the affected rows/columns then the edge would be missed by the filter. Using high precision floats for the texture coordinates and reworking the edge detection filter so that the texture coordinates are output from the vertex shader unnormalised fixes missing edges in the test project I created.

One additional source of missing edges in the final image is disabling texture filtering through `gpu_set_tex_filter(false)`. If there are still missing edges then try enabling texture filtering using the same function. If you need to keep texture filtering disabled for your project's drawing then you can try disabling it at the start of drawing and then re-enabling it once all necessary draw calls have been made. Otherwise texture filtering will remain disabled when the application draws the application surface to the back buffer at the end of the frame, which can also lead to missing edges in the final output if the application needs to resize the image.

I've attached the project I created to test the issue myself. If everything is working correctly it should produce a consistently repeating pattern of coloured edges across the entire screen.
[edge_detection_test.zip](https://github.com/user-attachments/files/17212297/edge_detection_test.zip)

**Comment by scott-dunbar** [comment]
As far as i can tell with the limited set of devices available this works fine now.

Closing in  IDE v2024.1100.0.681  Runtime v2024.1100.0.703

Obviously if you are still encountering an issue please do get back in touch with details
