### ISSUE TITLE
gamemaker studio 2 bug problem

### ISSUE THREAD

**Issue by serdarbayram** [YoYoGames/GameMaker-Bugs#6847]
### Description

Greetings, first of all I apologize for my bad English. I started to see errors in the game engine that I have never seen lately, I started to experience this error after updating to the latest version, I returned to the version that I did not get the error, but it continues again, if I come to the error, when I am doing operations in gamemaker, the menus at the top disappear, I cannot click on the buttons or anything as if the mouse cursor has shifted. I took a small video to explain the subject, as it can be seen in the video, I can't click on the buttons, they detect different places. the top menus do not appear. How can I fix this problem. I would appreciate your help.
Gamemaker version
![Ekran görüntüsü 2024-07-24 115602](https://github.com/user-attachments/assets/f4a191ab-ef59-4095-8e6f-b631466a2d23)

video link : https://youtu.be/ukPehNZbHpI?si=xiR_Vsyrl7CLE2Mo

### Steps To Reproduce

1. Start GameMaker
2.  bug 

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
To be clear, that Preferences screenshot is not showing your GameMaker install version - that's your runtime install, so "just the bit that builds and runs your projects" - and your IDE version number is hidden off the top of your screen because you have this issue, so I can't see it on the video ;)

Unfortunately, you did not actually attach the Contact Us package the form asked for, so I can't check your log to see if that gives us any more information, but this _looks_ like you're either already using or you need to set a custom DPI override in Preferences > General, and so reviewing that value and then restarting GameMaker might well fix this.

If for some reason your IDE is not 2024.6 also, please do update your GameMaker install also.

If the DPI thing and making sure you're on the correct version of GM does not fix this, please submit this problem again using the Help > Report a Bug option inside GameMaker, as that way it will include all the logging information automatically for you and also some information about your PC, so then we can see what's going on.

Thanks!

**Comment by YYDan** [comment]
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6079
