### ISSUE TITLE
CE2: Tab indicator is over text

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#6889]
### Description
no good

### Steps To Reproduce
1) See attached project line 138 __GameMedia Script
2) why is above?

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Attached Files:
GameMaker-Beta_tGocw6AwZC.png

![Image](https://github.com/user-attachments/assets/29fac0eb-8315-406a-9c58-99bd72c0977f)

[452d6bf0-59d6-4bd6-8357-75a39fe72f6d](https://api.gamemaker.io/api/github/downloads/452d6bf0-59d6-4bd6-8357-75a39fe72f6d)

**Comment by zreedy** [comment]
Fixed. Both the tab accumulator in the whitespace highlighting component and the tab accumulator in the text renderer were calculating off of an incorrect basis. Leading to the `TextRenderer` overshooting the tab stops (usually 5 spaces instead of 4), and the `WhitespaceRendererComponent` undershooting the tab stops.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.1000.0.622  Runtime v2024.1000.0.648, thanks.
