### ISSUE TITLE
In-Game: [Ubuntu] Background sprites scaled down won't be drawn

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#69]
GM-7121

{quote}
When running on Ubuntu, (VM or YYC), trying to scale a background to < 1x results in the background not being drawn. I believe this has been an issue since 2022.8.x.

In the test project, I have set up several layers which are created dynamically using layer_create() and layer_background_create(). On Windows, all of the layers are created and displayed correctly. On Ubuntu, only the layers with a scale >= 1 are shown, despite never changing the opacity, visibility, etc. You can verify this by modifying the struct for a given layer and changing its scale, leaving all other values equal.
{quote}

*Steps*
- Import the attached sample
- Open the project selecting Ubuntu VM/YYC as target and run
- Observe the differences

||Target: Windows||Target: Ubuntu||
| !Windows_Example.png|width=500|height=200|thumbnail! | !Ubuntu_Example.png|width=500|height=200|thumbnail! |

*Repro:* 100%

**Comment by TehCupcakes** [comment]
I am the original submitter for this issue. This has now been an issue for over a year and persists in the latest beta. The problem occurs with both VM and YYC. This issue is severe enough (with no workaround) that I have stopped updating my game on Linux, because there is no practical way for me to maintain the visual design of the game due to this bug.

Since the imported tickets did not maintain attachments, here are the screenshots and sample project I provided with this report:

[Sample Project File - Click to download](https://mega.nz/file/9l82SRRD#Ndn3T4K8XWjQ-ubkmmQVnm5HwRVzMhkDpvHFVQNiWFs)

![Windows_Example](https://github.com/YoYoGames/GameMaker-Bugs/assets/2908553/444dd925-2fa7-4dd4-8c18-fbc9a2faa10a)
![Ubuntu_Example](https://github.com/YoYoGames/GameMaker-Bugs/assets/2908553/e929e355-2132-4544-9139-a880ad7acc94)
