### ISSUE TITLE
GMRT: More files for #6876

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6900]
### Description
This is the same issue as #6876, but I'm doing this separate issue to provide more files without making them public by putting them in a comment. I managed to come up with two sprites that will cause the issue even when freshly imported, unlike the previous report which stopped crashing if the sprites were imported again.

### Steps To Reproduce
Along with the project, I have also attached the JSON files for each sprite. You can see the crash on launch by running the sample project, or try importing the JSON files into a new fresh project. The original spine projects are included as well, in case they have any useful info for narrowing the issue down.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Attached Files:
For GMRT Spine Report.zip

[7f276ea7-2d0f-4e87-9b1f-7821e97e4013](https://api.gamemaker.io/api/github/downloads/7f276ea7-2d0f-4e87-9b1f-7821e97e4013)

**Comment by LukeBrownYoYoGames** [comment]
This was actually a bit more of a subtle issue and was down to wad alignment. We were writing the spine data with a specific alignment which wasn't being honoured when reading back the data, meaning no spine data was being loaded since it didnt not know what version of spine data was being used.

This should be fixed in 0.12.0
