### ISSUE TITLE
Install: 2024.6.2 IDE does not get its runtime automatically

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6915]
### Description
Normally, new gamemaker IDE versions will automatically install the corresponding runtime version when first launched. However, 2024.6.2 does not. I believe this is due to there not being a 2024.6.2 runtime, and the intended matching runtime being 2024.6.1 instead.

2024.6.0, on fresh install:
![image](https://github.com/user-attachments/assets/e8d97947-13c1-46a4-9d9f-6b8770ab0e9f)

2024.6.2, had trouble screenshotting the loading text because it went by so fast (very nice load time improvements!):
![image](https://github.com/user-attachments/assets/09e4827b-f0f7-4691-99be-f117adee3737)

There have been many bug reports and help requests related to mismatched IDE/runtime versions recently, with some returning users having runtime versions as old as 2.3. I believe many of them are because of the automatic installer not working.
![image](https://github.com/user-attachments/assets/84f26125-3d9b-4ece-b0b1-d88e83d86042)

### Steps To Reproduce
Install some older runtime and delete the 2024.6.1 runtime. Install the 2024.6.2 IDE while not having the 2024.6.1 runtime installed. It will not automatically install the newer runtime, instead leaving you on whatever runtime you already had selected.

### Which version of GameMaker are you reporting this issue for?
Don't mind this, I just happened to report this after doing the 2024.6.0 install for the test/screenshot
IDE v2024.6.0.157 Runtime v2024.6.0.205

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[10ef9d95-d663-46ff-89ec-74d457cfeeaf](https://api.gamemaker.io/api/github/downloads/10ef9d95-d663-46ff-89ec-74d457cfeeaf)

**Comment by YYDan** [comment]
We think we know the reason why - it's not the lack of a 6.2 runtime, but it is a version number thing in that same area.

**Comment by YYDan** [comment]
Okay, so for this .6.2 IDE release it will be a bit of a pain to fix on our end, as whatever route we choose we would have to ask people to reinstall the same _content_, but with a different version number.

So we're not going to do anything just now beyond asking anyone with this issue to manually install and set active the correct runtime version in their Preferences:

![image](https://github.com/user-attachments/assets/b2ee00e9-cf02-459f-a89a-b37cc40aebd4)

_Double-click the version number to download the runtime AND set it active, rather than just clicking the download button over to the right!_

(This issue is now pinned to the top of the known issues also.)

**Comment by YYDan** [comment]
However, we have now realised the underlying cause of this issue and so will prevent that from ever happening again.

**Comment by YYDan** [comment]
Deliberately leaving this one as "Open" for a while, even though no new release is coming for 2024.6, so that it shows as green and a known issue and therefore more people are inclined to click in and read these comments.

**Comment by L-Clouds** [comment]
Utterly shocking that the choice was made to let this languish until 2024.8

**Comment by YYDan** [comment]
2024.8.0 is out now and does not have this issue, so finally closing this one.
