### ISSUE TITLE
Building Game Randomly Crash 

### ISSUE THREAD

**Issue by ezekiel-hls** [YoYoGames/GameMaker-Bugs#6920]
### Description
I am having issue building the project. Running the game would always stop after showing the  "DirectX11: Using hardware device" log

Sometimes it will not open  any window at all. Sometimes the game will open with black screen and closes after few seconds. Sometimes it will open the window with white screen (with process not responding pop up from windows) but will not procceed to running the game. Upon checking task manager during white screens it will show 0% CPU 0 RAM and 0 disk usage.

What sometimes fix  it is by restarting the computer. The game will run properly two or three times and this issue will persist again.

 ---
..Long log..
Setting scheduler resolution to 1
DirectX11: Using hardware device
 
C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.6.1.208/windows/x64/Runner.exe exited with non-zero status (-1073740771)
elapsed time 00:01:03.3731021s for command "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.6.1.208/bin/igor/windows/x64/Igor.exe" -j=8  -options="C:\Users\Ezekiel\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Windows Run started at 07/28/2024 09:44:17
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.

### Steps To Reproduce
1. Restart computer
2. Open project
3. Build game
4. If it runs, close and repeat step 3
5. Experience the bug

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[3b161a0b-99a3-48ef-a45a-95ec6d66ab16](https://api.gamemaker.io/api/github/downloads/3b161a0b-99a3-48ef-a45a-95ec6d66ab16)

**Comment by stuckie** [comment]
Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue to ensure we see exactly what you see and then learn why this problem is caused.

Please report this issue again, but ensure you have a suitable project open at the time you open the bug reporter and that you allow GameMaker to include the project.

Thanks!

[Why Have You Asked Me For A Sample?](https://help.gamemaker.io/hc/en-us/articles/13150754375453#h_01J15CZA1TP1FH04XQE2P18AAG)
