### ISSUE TITLE
Code Editor 2: Can avoid the need to restart GM on toggling CE2 in 2024. 800 Beta 2 by simply pressing "Cancel" on the restart prompt

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6930]
### Description

2024.8 made it so you need to restart GM when swapping between CE1 and CE2, to prevent various problems. Except it actually goes ahead and swaps as soon as the prompt appears, so saying no to restarting lets you have CE1 and CE2 open at the same time.

https://github.com/user-attachments/assets/3ea6b37a-e571-4011-8d34-0ca8a9dd9853

### Expected Change

Don't swap the active editor until the prompt is confirmed instead of cancelled

### Steps To Reproduce

Go into preferences and turn CE2 on or off, then hit "Cancel" when the restart prompt appears

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of IDE v2024.800.0.599  Runtime v2024.800.0.622

**Comment by KormexGit** [comment]
Can still be done in beta 2024.8.0.602 by swapping and pressing cancel twice

https://github.com/user-attachments/assets/1e073835-b20a-464a-b95d-7794605f7406

**Comment by mgeddesGM** [comment]
reopening for Beta IDE v2024.800.0.602  Runtime v2024.800.0.624as per users comment
Steps
1. open the IDE and set CE2 to be enabled, restart if needed
2. open a project
3. open or create an object - it will appear as CE2
4. go to preferences and click disable CE2 then press "Apply"
5. press cancel to the restart modal
6. notice the object is still ce2
7. close both ce2 pref and obj then reopen
8. notice the object is ce2 and preferences is set as disabled
9. click the enable checkbox, press apply and press cancel
10. close and reopen the object
11. the object will show as CE1 - not as expected due to no restart
12. restart the IDE and reopen both CE2 preferences and the object
13. ce2 will be enabled and the object will show as ce2 as expected

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.800.0.604  Runtime v2024.800.0.627, thanks.
