### ISSUE TITLE
In-Game: Visual glitch instead of room loading in GMRT when going from room with a viewport to one without

### ISSUE THREAD

**Issue by cameron-home** [YoYoGames/GameMaker-Bugs#6953]
### Description

When running a game that has a room with a viewport as any room but the first, the game will return visual glitches when trying to change from this room to one without a viewport. If the viewport room is the first room, this issue does not occur. This issue does not occur for VM. This issue was found in IDE v2024.800.0.589  Runtime v2024.800.0.613.

![Runner_6E7YwfKbZW](https://github.com/user-attachments/assets/6b8f944f-5b89-4bbc-a3b5-5ee9295ffce2)

Test Project: 
[GMRT Viewport.zip](https://github.com/user-attachments/files/16195729/GMRT.Viewport.zip)

### Expected Change

It is expected that the behaviour matches VM, where the room will change even if there is no viewport present

### Steps To Reproduce

1. Start GameMaker
2. Open attached project
3. Target GMRT
4. Run project
5. See the issue
Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Compiler Log File

- [X] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by JonnoRobson** [comment]
GMRT was not correctly resetting the internal viewport to display scale when switching from a room with viewports enabled to one without. This caused a rendering validation error when switching from a room with a smaller viewport to one without viewports enabled as the rendering viewport would be scaled to be larger than the actual surface that was being rendered to. I've made sure we correctly reset the internal viewport to display scale when viewports are not enabled so there should no longer be any rendering issues.

**Comment by JonnoRobson** [comment]
Also for some reason the attached project had some issues on my end where underlying assets were missing when imported into GameMaker. This caused a crash in the asset compiler when trying to load a missing png file which I've since fixed, but also meant that the necessary scripts were missing to demonstrate the issue. I've created another project that demonstrates the issue by using the space bar to switch between three rooms with different viewport set ups. Without the fix switching between rooms "rm_02" and "rm_03" would trigger the rendering issue.[viewport_test.zip](https://github.com/user-attachments/files/17587603/viewport_test.zip)
