### ISSUE TITLE
GMRT: Project crashes on launch due to multiple issues

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6992]
### Description
Even after the spine fixes today, my project is still crashing immediately after launching, so here's the whole project

### Steps To Reproduce
Run the attached project in GMRT

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[7922b6d5-3027-4c36-9af0-140911fed1d5](https://api.gamemaker.io/api/github/downloads/7922b6d5-3027-4c36-9af0-140911fed1d5)

**Comment by LukeBrownYoYoGames** [comment]
Fixed the initial issue related to ds_grip_copy
Another issue was hiding behind that related to scribble performing font baking on the first frame (possibly related to the surface resize which occurs just before it not being fully initialised)

**Comment by pkraif** [comment]
I've tested this using latest `develop` and the first crash happens in `draw_clear`(), which is using the solid white texture, which doesn't seem to be created yet when code in global scope of scripts is called. I've tried moving the creation of that texture, but then it crashes in `vertex_submit()` that uses `sprite_get_texture()` - sprites don't seem to be loaded at that point either. We need to reorganize the loading code a little to make rendering from global scopes of sprites possible.

**Comment by LukeBrownYoYoGames** [comment]
I can now open and play around with the project after a few different fixes hiding behind each other. There are likely more issues in this project but at least it opens now so we can find out more.

I only tested the stretching face stuff because I dont know how this project is supposed to work but that seems to be working ^^

![image](https://github.com/user-attachments/assets/e25effc9-3c03-4e94-bd15-319c78ac2a51)


Closing this issue for now as the crashing on launch is fixed

**Comment by LukeBrownYoYoGames** [comment]
Fix should be present in GMRT 0.15
