### ISSUE TITLE
In-Game: While using Windows Audio enhancements or Spatial sound, VM and YYC have different behaviours.

### ISSUE THREAD

**Issue by Indibulous** [YoYoGames/GameMaker-Bugs#7005]
### Description

While using an audio device on Windows 11 with Audio enhancements or Spatial sound enabled, Windows VM builds will treat the device as having 8 audio channels, but YYC builds will treat it as 2, resulting in different audio levels between the two. 

This has been tested with 3 different pairs of headphones, which all give the same results:
### Windows VM:
![image](https://github.com/user-attachments/assets/bd68a74a-6224-4c6a-a791-4bf376667b1f)
### Windows YYC:
![image](https://github.com/user-attachments/assets/f9621f56-a14b-4a4a-9816-54a35266e053)

VM displays the devices as having 8 channels, with the loudest channel (ch3) reaching an amplitude of around +/-0.3, unlike YYC, which has 2 channels and reaches an amplitude of only +/-0.2, as expected of stereo devices. 

This has not been tested on any actual multi-channel audio hardware, due to a lack of access to such hardware, so there's a chance this may simply be an issue with any device considered to have more than 2 audio channels, regardless of any audio enhancements.

Sample project: [gm-4218-x.zip](https://github.com/user-attachments/files/16410240/gm-4218-x.zip)

YYC Log: [YYC output log.txt](https://github.com/user-attachments/files/16410250/YYC.output.log.txt)

VM Log: [VM output log.txt](https://github.com/user-attachments/files/16410251/VM.output.log.txt)

### Expected Change

Audio volume and number of channels used should be consistent across VM and YYC builds.

### Steps To Reproduce

1. Start GameMaker
2. Open the sample project: [gm-4218-x.zip](https://github.com/user-attachments/files/16410240/gm-4218-x.zip)
3. Ensure you are using headphones with Audio enhancements / [Spatial Sound](https://winaero.com/how-to-enable-spatial-sound-in-windows-11/#Enable_Spatial_Sound_in_Windows_11_using_Settings) enabled in Windows settings
4. Run the game on Windows YYC.
5. As the game loads, please wait a couple of seconds, as shown on the screen. An initial sound will play which will calibrate the graph axes.
6. Then, as shown on the screen, hit 1 to play a sound. This is a square wave of 0.2 linear gain which is also accounting for some attenuation built into the engine.
7. As the sound plays, observe that the top and bottom of the waveform aligns with +0.2 and -0.2 on the y-axis.
8. Repeat steps 5-7 on Windows VM, but this time observe the increase in channels, as well as the waveform reaching closer to +/-0.3.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which platform(s) are you seeing the problem on?

Windows

### Compiler Log File

- [X] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by toby-yoyo** [comment]
After quite a lot of investigation on this, I now think that this is a Windows issue rather than a GameMaker issue.

There are no differences to how we are handling audio endpoints on VM and YYC, and really the inconsistency here is that running VM from the IDE seems to get us 8 channels with Windows Sonic enabled. With all other export options (zip/installer), the VM runner behaves the same as YYC and we get only ever get 2 channels in this situation (2 channel device w/ Windows Sonic enabled).

Windows doesn't give us any control over this area - all we can do is ask to use one of the audio endpoints it provides. It will sometimes make those endpoints appear to have 8 channels instead of 2 - how and why it does that is completely out of our hands. In the end, we can only use the devices in the way that Windows will allow us, and what it does behind the scenes cannot be influenced by us.

Additionally, this issue doesn't seem to be exclusive to GameMaker. Browsers, for example, also cannot get 8 channels as far as I've found. In a new tab in your browser (with Windows Sonic enabled) you can run the following in the console to see the maximum number of output channels:
```
const context = new AudioContext();
console.log("Max output channels: " + context.destination.maxChannelCount);
```
For me, this only ever returns two. From memory (although, this was a while ago now) this wasn't always the case, as I remember looking into a particular [reverb distortion bug](https://bugs.opera.com/browse/GM-6331) only heard on devices with more than 2 channels, which was also checked on HTML5 (implied in the [PR](https://github.com/YoYoGames/GameMaker/pull/1770)). As I don't personally have a device with more than 2 channels, this would have been checked using Windows Sonic.

My best guess is that a Windows update has changed how and when Windows decides to allow applications to route into a respatialising submix, but again, the inner workings of these rather niche Windows features do not seem to be documented at all.

Closing as 'not a (GameMaker) bug'.
