### ISSUE TITLE
(Beta) Source Control: A lot of changed .yy files without any changes

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#7030]
### Description
While working on my game and doing regular commits, I noticed that GM touched a lot of .yy files in some way. Git marks them as changes to be committed but the contents haven't been changed at all.

This also happens to objects I haven't really touched or worked with.

I also noticed the same thing happened earlier to the .yy files of all the options.

If a project is required, please refer to my previously privately shared one.

### Steps To Reproduce
1. Work in GameMaker beta
2. Do regular commits.
3. Eventually .yy changes show up without changed content.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[6153f713-da24-4a7f-b61b-28fd291ec503](https://api.gamemaker.io/api/github/downloads/6153f713-da24-4a7f-b61b-28fd291ec503)

**Comment by stuckie** [comment]
Is there any change at all? whitespacing or perhaps line endings?

**Comment by nullbunny** [comment]
I was using GitHub Desktop and it usually mentions line endings and stuff having changed, but it just said no changes at all. I can check with a different tool next time I notice it happening. It hasn't occurred again since I submitted the ticket, so I don't yet know how to reproduce it consistently.

**Comment by YYDan** [comment]
There was an issue in Beta 2 (which is the version I can see you were using for this report), where if you had tilesets in your project and you built it, then the File Watcher would pop up towards the end of the build because your files were being incorrectly updated by the build tools. If you clicked the "Save" button on that File Watcher, then it would give the exact results you're seeing here.

That was already fixed for Beta 3, so I'll go ahead and close this one as a duplicate just now, but if you do happen to see this again in future, please do re-report it.
