### ISSUE TITLE
In-Game: [GX.Games] Crash on load if any Texture Group uses PNG format and has a custom path defined

### ISSUE THREAD

**Issue by FoxyOfJungle** [YoYoGames/GameMaker-Bugs#7157]
### Description
The project does not start if a texture group (at least a single one) is in PNG format and has a path defined. The project starts if there is no path defined in the group. This can be reproduced in an empty project.

### Steps To Reproduce
Press F5 and see that the game does not load and there is a stack error in the browser console. Open a texture group and remove the path, try running it again and it will work. This only happens if the format is PNG. If I don't put the path, the project compiles, even if it is in PNG.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
GX.games

[b1da3ac9-fe8f-4a13-87a8-0159daa46cb2](https://api.gamemaker.io/api/github/downloads/b1da3ac9-fe8f-4a13-87a8-0159daa46cb2)

**Comment by FoxyOfJungle** [comment]
This is what appears in the browser console:

![image](https://github.com/user-attachments/assets/f94d5497-324c-45d6-8a5a-cd39b3bada96)

**Comment by FoxyOfJungle** [comment]
I updated the Emscripten SDK to test it on YYC and it works. So the problem seems to be only on the VM.

**Comment by JonnoRobson** [comment]
This issue is caused by there being a '/' path separator in the Texture Group path. This path separator causes the asset compiler to fail to copy the texture group asset to the correct directory in the packaged game so it can never be loaded. I've fixed the asset compiler so that it can handle the alternative path separator on Windows and now project loads correctly for me. This fix should be in the 2024.11 release of GameMaker.

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.1100.0.635  Runtime v2024.1100.0.659
