### ISSUE TITLE
Room editor goes to a crawl if too many sprites and/or tiles are in a room

### ISSUE THREAD

**Issue by adamrpippin** [YoYoGames/GameMaker-Bugs#7170]
### Description

I have been having issues with large rooms as well, it slows down when there are a lot of sprites but even worse if there are a lot of tiles, which makes level creation difficult because tiles are more efficient on render. The new layout with the layer bar makes selection easier, but the slow room editor makes it really hard to work on my game as well. 

### Steps To Reproduce

1. Start GameMaker
2. Make a large room, ie 3000x3000
3. Paint 1000+ tiles into the room or 2000+sprites
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue to ensure we see exactly what you see and then learn why this problem is caused.

Please report this issue again, but ensure you have a suitable project open at the time you open the bug reporter and that you allow GameMaker to include the project.

Thanks!

[Why Have You Asked Me For A Sample?](https://help.gamemaker.io/hc/en-us/articles/13150754375453#h_01J15CZA1TP1FH04XQE2P18AAG)
