### ISSUE TITLE
Building Projects: [YYC] Can't compile projects on my machine if using VS2019

### ISSUE THREAD

**Issue by batblaster** [YoYoGames/GameMaker-Bugs#7176]
### Description
Hi,
i can't build in YYC also if i check the VS2019 solution i get the same error.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[8cbb016a-e189-408b-95b6-ec2dca61cf16](https://api.gamemaker.io/api/github/downloads/8cbb016a-e189-408b-95b6-ec2dca61cf16)

**Comment by YYDan** [comment]
Can see the linker errors at the very end of the output log, but no content errors higher up in the log, so I suspect we might need you to send the project/confirm if even a blank new project has the same problem for your setup.

(Filepaths and duplicate lines removed)
```
fatal error LNK1120: 1 esterni non risolti 

     2>Compilazione progetto  NON COMPLETATA.
     1>Compilazione progetto destinazioni: build) NON RIUSCITA.

Compilazione NON RIUSCITA.


    Avvisi: 0
    Errori: 2
```

**Comment by stuckie** [comment]
Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue to ensure we see exactly what you see and then learn why this problem is caused.

Please report this issue again, but ensure you have a suitable project open at the time you open the bug reporter and that you allow GameMaker to include the project.

Thanks!

[Why Have You Asked Me For A Sample?](https://help.gamemaker.io/hc/en-us/articles/13150754375453#h_01J15CZA1TP1FH04XQE2P18AAG)
