### ISSUE TITLE
In-game: [GX.games] Platformer Template shows momentarily a black screen after pressing play

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#7287]
### Description

When building the Platformer Template from start page targeting GX.games a black screen will appear for a few seconds after pressing play while loading the next room.

### Steps To Reproduce

1. Start GameMaker
2. Create a new Platformer Template project from the start page
3. Run for GX.games VM/YYC
4. See the issue

https://api.gamemaker.io/api/github/downloads/6322fc2c-3661-443d-9c12-8d0fa39fc599

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly), 2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

GX.games

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
The delay is coming as the texture groups are being loaded in. This happens when they are first drawn as they are loaded on demand, thus you get the black screen whilst the first frame is being rendered. This can be avoided by prefetching the textures either in the create event of an instance that is present in the first gameplay room or as the menu is being exited from. 

texture_prefetch("tg_game");
texture_prefetch("tg_hud");
texture_prefetch("tg_ui");
