### ISSUE TITLE
problem with draw_sprite_general

### ISSUE THREAD

**Issue by rephaim1** [YoYoGames/GameMaker-Bugs#7376]
### Description

draw_sprite_general(sprite, subimg, left, top, width, height, x, y, xscale, yscale, rot, c1, c2, c3, c4, alpha);

variable c3 causes a diagonal line traveling from the lower right to the upper left.  c3, being the lower right corner is being shaded perpendicular to the proper axis.  

IDE: 2024.6.2.162
d3d11: nvidia gtx 970

intel64 family 6 model 94 stepping 3, GenuineIntel

**Comment by YYDan** [comment]
Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue to ensure we see exactly what you see and then learn why this problem is caused.

Please report this issue again, but ensure you have a suitable project open at the time you open the bug reporter and that you allow GameMaker to include the project.

Thanks!

[Why Have You Asked Me For A Sample?](https://help.gamemaker.io/hc/en-us/articles/13150754375453#h_01J15CZA1TP1FH04XQE2P18AAG)

**Comment by attic-stuff** [comment]
this is the hardware implementation of vertex color and its to spec, btw, not a bug. the color interpolation is done across the individual triangles that make the quad, using barycentric coordinates. the vertex color is not done with a bilinear interpolation across the whole face.

better illustrated here, both sides are rectangles made of two triangles. A's color is interpolated using a bilinear interpolation between each point[^1]. B's color is the same standard, business-as-usual vertex color used for draw_sprite_general:

![Capture](https://github.com/user-attachments/assets/13af08e2-d0af-49e6-9046-e1d693fb74a7)

[^1]: this interpolation is done using oklab color space, but that doesn't effect the manner of the interpolation just the visual result. its much prettier!

**Comment by rephaim1** [comment]
This is showing interpolation between two triangles to create each square.  

Maybe I'm not understanding.  In the same sense, the square on the left is how the corner should be shaded (using blue in this case).  

The square on the right, the blue is running like a stripe diagonally.  

When I used draw_sprite_general(); , I am using it across a the face of a single square sprite.  

I will try to upload project shortly.

**Comment by rephaim1** [comment]
The other three corners are shaded differently that the lower right when you use that function.  I will upload.
