### ISSUE TITLE
Runtime Feed Error

### ISSUE THREAD

**Issue by Danillo001** [YoYoGames/GameMaker-Bugs#7384]
### Description

It is my first time using/installing Gamemaker and when i open it the error appears
I first installed it on steam but it had this error so i tried the tutorial to install the runtime manually but it didn't work(i had to create the runtime folder and download folder since there was just "Survey" on the Cache folder). It didn't work.
Then i installed the gamemaker from the site and the error was still there, so i was going to try and install the runtime manually there but i noticed that there was no runtime on the site for the version i had!?
And now there is 2 runtime folders too
I'm pretty confused here, i'm new to these things so i don't really know what to do and i would really appreciate some help
I think that the version i installed is 2024.6.2.162

ui log: 
[ui.log](https://github.com/user-attachments/files/16707415/ui.log)

images
![imagem_2024-08-22_050403665](https://github.com/user-attachments/assets/b09abaf2-6a87-471e-a415-75e30bc4de31)
![image](https://github.com/user-attachments/assets/004c64f0-34b7-4169-95b7-e83fdfae4f6c)

Sorry if the english is wrong, it's not my first language.

### Expected Change

For the program to work

### Steps To Reproduce

1. Start GameMaker
2. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Okay, so your original "it had this error"/the reason the runtimes are not working is because you're either offline in Steam itself or you're firewalling GameMaker:

```
[03:34:27:690(a53f)] DoRSSDownload :: No Internet connection
[03:34:28:27(a53f)] Unable to find the Active runtime  in this Runtime feed
[03:34:28:28(a53f)] Unable to download RSS Feed and no local runtime installed - unable to continue, exiting
[03:35:46:232(a53f)] InternalCheckForInternetConnection :: Unable to reach site https://api.gamemaker.io/api/health-check 
[03:35:46:233(a53f)] InternalCheckForInternetConnection :: Unable to reach site https://api.gamemaker.io/api/health-check 
[03:35:46:233(a53f)] System.Threading.Tasks.TaskCanceledException: A task was canceled.
```

This is an issue with the OS account permissions, antivirus/firewall settings or other security products on your machine or network, rather than a GameMaker bug or something we could fix for you.

You need to review our [Permissions FAQ](https://help.gamemaker.io/hc/en-us/articles/360022953052) and follow the steps there. Note that we always link to this guide on the release notes page, as many users need to review their protection settings every time they install a new version of GameMaker, so this may be something you need to do also in future.

That will allow you to fix both your Steam and non-Steam (if you want to keep that) installs.

**Comment by YYDan** [comment]
The second part of your issue is that you have then run into this pinned known issue: https://github.com/YoYoGames/GameMaker-Bugs/issues/6915

The correct runtime to download is the 2024.6.1 runtime - there is no 2024.6.2 runtime, as the release notes page says: https://releases.gamemaker.io/release-notes/2024/6

**Comment by YYDan** [comment]
Closing as "duplicate" of 6915 - but, as I say, you will always need to fix why GameMaker cannot connect to the internet on your machine before it will all be able to work.

**Comment by Danillo001** [comment]
It was solved by configuring the antivirus exceptions.
Thank you very much and sorry for the trouble.
