### ISSUE TITLE
Install: Implement a better way to deliver runtime updates

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#7509]
### Is your feature request related to a problem?

Another monthly release, another non-trivial subset of users whose projects are breaking because of a runtime/IDE mismatch because the IDE update didn't install the runtime.

![image](https://github.com/user-attachments/assets/db113d21-6c15-4e34-b8bd-ebf9a0732462)

(This has been going on all morning.)

### Describe the solution you'd like

I don't know enough about content delivery to suggest an alternative to the RSS feed, but it would probably be beneficial to start getting to the bottom of this.

### Describe alternatives you've considered

Installing runtimes manually is still an option but it's not practical to ask people to do that every time they have this problem

**Comment by MrPr1993** [comment]
This is such a problem!

**Comment by arrosev** [comment]
I often fail to update so manually installing updates is a must, unfortunately when I try to manually download the new runtime in the morning I realise that the new runtime hasn't been uploaded yet!

**Comment by DragoniteSpam** [comment]
The runtimes exist online, but the problem is that (for what seems to be several different reasons) certain peoples' IDEs arent able to find it

**Comment by arrosev** [comment]
> The runtimes exist online, but the problem is that (for what seems to be several different reasons) certain peoples' IDEs arent able to find it

It's uploaded now! Download it here: https://gamemaker.io/account/runtimes#_ga=2.225495123.896895315.1725412814-1639657231.1720707256

**Comment by YYDan** [comment]
Can see from ui.logs in other reports that some users are stuck getting an older copy of the runtime RSS feed and so the IDE is not aware of the newer runtime - be aware that this reason may also mean downloading the runtime .zip yourself still does not actually install it (as was the case on #7510).

You should find all is fixed already and your IDE should automatically install the runtime on the next startup. as we have cleared the caches on those files again and also worked out the reason some people are stuck seeing old content for a while, so this should be fine in future.

To be clear about downloading runtimes manually, here is nothing that we can do in the case of someone firewalling GameMaker and installing the IDE update themselves via downloading the installer off our site - anyone in that situation should see our permissions guide and change their settings so GameMaker can access its feeds properly. Downloading the runtimes manually is meant to be a "last-resort" in the case of intermittent internet access means downloads keep failing, or for teachers/IT admins in schools to save many computers all downloading the same runtimes, rather than something we expect people to routinely do each release.

This is a web issue, rather than a GameMaker bug for us to fix ahead of a new release, and again this should actually be fixed already as far as you're all concerned; however, I will leave this FR open for further discussion.

**Comment by stuckie** [comment]
The new runtimes will be delivered via the package manager.
The existing one had issues with a cache, which should now be resolved.
