### ISSUE TITLE
In-Game: [iOS] Sounds clip/distort momentarily when restoring game audio after turning off music played by an external app

### ISSUE THREAD

**Issue by KamilWdowczyk** [YoYoGames/GameMaker-Bugs#7549]
### Description
When you listen to music from an external source while playing a game (like Apple Music or YouTube Music) a few things happen: 
1. The game stops playing sound, 
2. When it resumes the sound sometimes appears, sometimes not. 
3. When the sound resumes ALL SOUNDS that should have been playing recently play.

### Steps To Reproduce
1. Play game
2. Turn on music from YouTube Music or Apple Music - you can do it only from top bar
3. Play game a while
4. Minimise the app 
5. Stop your external music source
6. Restore focus to the game
7. Manually restore volume to the game (if required)
8. Hear that all of the sounds play at once, which can give distortion

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.0.169 Runtime v2024.8.0.216

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
iOS

### Attached Files
* RPReplay_Final1725624508.MP4

[8137e187-b21f-4f53-8c9d-8a4966a64d65](https://api.gamemaker.io/api/github/downloads/8137e187-b21f-4f53-8c9d-8a4966a64d65)

**Comment by YYDan** [comment]
Updated the info and steps after watching the video.

**Comment by stuckie** [comment]
Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue to ensure we see exactly what you see and then learn why this problem is caused.

Please report this issue again, but ensure you have a suitable project open at the time you open the bug reporter and that you allow GameMaker to include the project.

Thanks!

[Why Have You Asked Me For A Sample?](https://help.gamemaker.io/hc/en-us/articles/13150754375453#h_01J15CZA1TP1FH04XQE2P18AAG)
