### ISSUE TITLE
Unknown type on parameter 0 in optimize call for method string

### ISSUE THREAD

**Issue by bsabiston** [YoYoGames/GameMaker-Bugs#7645]
### Description

I updated to v2024.8.1.218 today and am getting this error in two calls to show_debug_message.  The calls look like this:

show_debug_message("player value "+string(obj_player))

Is that not valid?  It always worked before...

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

macOS Ventura

### Which platform(s) are you having trouble building this project for?

macOS

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue to ensure we see exactly what you see and then learn why this problem is caused.

Please report this issue again, but ensure you have a suitable project open at the time you open the bug reporter and that you allow GameMaker to include the project.

Thanks!

[Why Have You Asked Me For A Sample?](https://help.gamemaker.io/hc/en-us/articles/13150754375453#h_01J15CZA1TP1FH04XQE2P18AAG)

**Comment by bsabiston** [comment]
Correct me if I'm wrong, but could you not have just glanced at my issue and explained why 
`show_debug_message("player value "+string(obj_player))`
no longer works.  It doesn't require a bug report.  Just forget it.

**Comment by stuckie** [comment]
Because there are many things in the way that could trigger it - which is why we almost always ask for a project attached.
In this case, is this a runtime issue or an IDE issue? It's not exactly clear from the initial report.
If it's an IDE only issue, it could be that feather is telling you the wrong thing.
If it's a runtime issue, it could be that there's an issue in the project where there's something else that's called "obj_player" ( perhaps you use source control or a sync drive, and have reverted something in a manner that it's in the project, but unseen? ) it could be the compilation is tripping over it for some reason, it could even be that a file write caused a problem with the resulting runtime data so that that reference isn't found.

GameMaker is a complicated product, there are several moving parts - the IDE, various runtime tools and the runtime itself - and a bug can be in any one of them, and perhaps more, so we ask for a project to verify where it is, to ensure we see what you are seeing, and to verify that we have fixed it.

There are thousands of issues in this repository, and it's not uncommon for there to be 30+ tickets each morning for us to have to quickly go through to see if they are in fact an issue or not. We simply do not have time to create a project ourselves, and put that line in, and then create - we assume - an object named the same thing; but as said, it could well be something else in that project that's causing an issue. We simply cannot know from what is here.

So we've asked for your project so we can investigate.
