### ISSUE TITLE
GameMaker Doesnt Run game without ANY ERROR CODES

### ISSUE THREAD

**Issue by 4-ED** [YoYoGames/GameMaker-Bugs#7651]
### Description

i was making a new game and suddenly i couldnt run my game and it didnt show anything like error codes. the output just says its 
failed

### Expected Change

Run the game properly

### Steps To Reproduce

1. Start GameMaker
2. Add some codes that are not wrong
3. Trying to run the game
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [ ] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue to ensure we see exactly what you see and then learn why this problem is caused.

Please report this issue again, but ensure you have a suitable project open at the time you open the bug reporter and that you allow GameMaker to include the project.

Thanks!

[Why Have You Asked Me For A Sample?](https://help.gamemaker.io/hc/en-us/articles/13150754375453#h_01J15CZA1TP1FH04XQE2P18AAG)
