### ISSUE TITLE
Throw an exception when calling a constructor function without `new`

### ISSUE THREAD

**Issue by kat-fl** [YoYoGames/GameMaker-Bugs#7690]
### Is your feature request related to a problem?

In YYC and GMRT, the following code will construct an instance of `Bee` instead of `Cas`:
```
function Cas() constructor {
  show_debug_message("Calling Cas");
  Bee();
}

function Bee() constructor {
  show_debug_message("Calling Bee");
}

var bee = new Cas();
show_message(instanceof(bee)); // Bee
```

### Describe the solution you'd like

A runtime error when calling a constructor function without `new`. `Bee()` should be a runtime error like "cannot call a constructor without the 'new' keyword".

**Comment by rwkay** [comment]
Feature added in 2024.11 - an error will be thrown if a constructor is called normally - they MUST be called view `new`

**Comment by Hyomoto** [comment]
For clarity, can we have some answer as to why constructor exists then? New and constructor seem to both perform the same task: indicate to the engine that this code produces structs. The JS we're seemingly emulating uses new but doesn't use constructor. Thus, while new never worked on non-constructor calls, constructors could be called without new. Weird, but a quirk of two keywords.

As with my post on #3055, with this change, we can now say, without exception, one of them is superfluous. If we've decided new, arguably the less important of the two, is now vital then we shouldn't need to declare constructors anymore. If we admit that constructor is important, then new is completely unneccessary as the identity of the constructor is to BE a constructor. Enforcing the use of new only ensures this is true and adds a language keyword that actually does nothing but throw runtime errors when omitted.

Thus one can easily argue that removing new also solves this problem as calling a constructor, which has been declared as a constructor, should be sufficient to indicate to the engine it's purpose and also close the aforementioned since constructors would be legal to call with method_call and return the expected results.

**Comment by Hyomoto** [comment]
> @Hyomoto
> 
> > As with my post on #3055, with this change, we can now say, without exception, one of them is superfluous. If we've decided new, arguably the less important of the two, is now vital then we shouldn't need to declare constructors anymore.
> 
> You are absolutely wrong. The `constructor` keyword is needed in order to show that this function is a constructor and the result of its correct call with the `new` keyword is a structure, and with a certain static binding, that is, it replaces `return struct (as CtorName)`. Running the constructor without the keyword `new` allows you to initialize static fields, or inject structure fields from ctor-function into an instance of an object or other structure where it is called, this is also part of the inherent logic that you did not see.

Perhaps, except the fix here requires the use of new with a function explicitly flagged as a constructor. I wasn't born yesterday, and code isn't magic. We have drawn an explicit link from a new declaration to a constructor declaration, if the two most be used together and can not be used without one another, we have one keyword too many.

**Comment by Shoozes** [comment]
So with this runtime exception, how would you go about instantiating constructors dynamically?

For example, this would work previously, but now returns the "new" error:
function inst_create(actor_struct, xx, yy, zz) {
	if (is_struct(actor_struct)) {
	        // Check if actor_struct is a constructor and apply 'new' explicitly
	        var new_instance = new actor_struct(); //<---- using 'new' right here

	        // Add the new instance to the global array and assign its index
	        new_instance.ind = array_length(global.instances_array);
	        global.instances_array[new_instance.ind] = new_instance;

	        // Assign the properties to the instance
	        new_instance.pos = [xx, yy, zz];
	        new_instance.create();

	        return new_instance; // Return the new instance for external use
	}
    }
}

// Define actor constructor child of mini_instance() constructor
act_tree = function inst_tree() : mini_instance() constructor { } 
inst_create(act_tree, 0, 0, 0); // Instantiate actor constructor

Returns the error:
calling a constructor directly - constructors should only be called using new

**Comment by sihammill** [comment]
Fix verified in Beta IDE v2024.1100.0.626 Beta Runtime v2024.1100.0.652

**Comment by StarJackal57** [comment]
This now also throws an error for constructor inheritance because that requires you to call the parent constructor without using "new".
![image](https://github.com/user-attachments/assets/86cf01eb-8474-4b99-bfdc-7da9492ad14f)

**Comment by RefresherTowel** [comment]
This is still a problem in **Beta v2024.1100.0.652**. Constructor inheritance is broken as the parent cannot be invoked without a new command. 
![Screenshot (653)](https://github.com/user-attachments/assets/733cce83-1a96-4964-9269-4186994a6534)
Very simple project just consisting of a parent and child constructor, with the child constructor being called properly with the `new` command. As you can see in the output, the project fails to compile because the child is not invoking the parent properly.
