### ISSUE TITLE
Ram peakUsage inconsistency for the same operation

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#7697]
### Description
In the sample, we are observing that when performing the same operation and calling `debug_event("DumpMemory", true).peakUsage`, the second and subequent times would return a number that is about 66% larger. We want to know if this peak RAM usage increase is intended.

### Steps To Reproduce
1. Run the sample for windows VM
2. Observe that the first `debug_event("DumpMemory", true).peakUsage` call returns about 1815 mb, and the subsequent calls return about 3036 mb.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1000.0.621 Runtime v2024.1000.0.648

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Windows

[ffbc64b2-1222-4384-a395-77fac54980a9](https://api.gamemaker.io/api/github/downloads/ffbc64b2-1222-4384-a395-77fac54980a9)

**Comment by jackerley** [comment]
When you call gc_collect it's only a flag to the garbage collector to do the collection at the end of the frame, it doesn't do it immediately, so on the first frame you have the allocated objects, on the second you have the allocated objects and the ones that have not yet been garbage collected, so you have a higher peak memory usage at this point. 
Hope this helps,
Fritz

**Comment by shichen85** [comment]
@BscotchSeth

**Comment by shichen85** [comment]
Hello @jackerley, just following up on the question above. Please let me know if I am understanding how GC works correctly. Thanks!

**Comment by jackerley** [comment]
Hi, sorry @shichen85 I've been on holiday, I think @yymrennie would be best to describe the GC functionality.

**Comment by yymrennie** [comment]
Hi all, the memory spike which occurs the second time is primarily caused by the way arrays are handled by the garbage collector. They need to be handled in multiple phases, which means that the work required to free them is actually spread across two GC cycles. This results in some memory for them staying allocated until the second GC frame.

In the second sample project (which is the one I tested) since no work triggers the garbage collector apart from the gc_collect() calls in the code the aforementioned array-related memory is allocated until the gc_collect() of the *next* call to "anon_assignment" at which point it is then freed. However this overlaps with the new allocations made on the same frame as the call to gc_collect() which is what causes the memory to be higher then.

**Comment by shichen85** [comment]
@yymrennie @jackerley Thanks for the explanation! @BscotchSeth please see Mike's response above regarding why the RAM peak increases over the same operations.

**Comment by BscotchSeth** [comment]
@yymrennie @jackerley Understood! I'd like to request that your team reevaluates this aspect of the garbage collector so that it functions as described & expected. The current implementation means that to _actually_ free up memory, you have to run the garbage collector twice, over multiple frames. It seems that the GC should be handling both phases of its cleanup back to back in the same frame, rather than leaving a bunch of lingering memory loose ends.
