### ISSUE TITLE
[iOS] Suppress Build & Run (Only Create .xcodeproj)

### ISSUE THREAD

**Issue by caroparo** [YoYoGames/GameMaker-Bugs#7849]
### Is your feature request related to a problem?

Currently under IDE v2024.4.152, the suppress build and run toggle in platform settings no longer seems to work. IDE always builds the .xcodeproj, does pod install, and then opens up the .xcworkspace. Please fix this.

### Describe the solution you'd like

Please bring back the "suppress build & run" feature.

**Comment by YYDan** [comment]
That IS what the feature does - https://manual.gamemaker.io/monthly/en/#t=Setting_Up_And_Version_Information%2FPlatform_Preferences%2FiOS.htm&rhsearch=suppress&rhhlterm=suppress

The bit that is supressed is that we don't trigger the build to _start_ inside Xcode (and therefore nothing is deployed to a device either).

Xcode _is_ opened as the point of this feature is that you can then modify the Xcode values and manually control the build.

Pod _is_ installed (if required on your Mac) in order to build and prep any extensions in the project, ready for making the Xcode project.

I doubt it will make much difference, but worth saying that you're 2 major releases behind the current release also, and so if you have recently updated your Xcode install this might be why you're now seeing different results. Try updating to the August release anyway, but as I say there doesn't seem to be anything for us to change here.
