### ISSUE TITLE
Code Editor 2: latin charaters with diacritics have less width in CE2

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#8097]
### Description

When using diacritics/accented characters, it seems they have different width in CE2, making text narrower.

For example:
```
Zazolc gesla jazn Zazolc gesla jazn
Zażółć gęślą jaźń Zażółć gęślą jaźń
```

is rendered as:
![obraz](https://github.com/user-attachments/assets/0049cd2f-9cb8-4837-862f-b08a3c8ecbe7)

In the end, there's difference of one character in width!

### Steps To Reproduce

1. Start GameMaker
2. Open CE2
3. Paste text from `Description` anywhere

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

**Comment by zreedy** [comment]
Related https://github.com/YoYoGames/GameMaker-Bugs/issues/8097 and https://github.com/YoYoGames/GameMaker-Bugs/issues/8111 and https://github.com/YoYoGames/GameMaker-Bugs/issues/8097

**Comment by zreedy** [comment]
The following changes to rendering non-ASCII characters have been made:
 - HarfBuzz `advance` metrics are truncated to emulate behavior from SharpFont
 - Fallback Font selection no longer considers icon fonts for selection
 - Fallback Font text runs are scaled on font provided line heights rather than height of `W` characters

**Comment by zreedy** [comment]
Fixed + Merged

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1300.0.714  Runtime v2024.1300.0.727
