### ISSUE TITLE
In-Game: Nested arrays do not free memory as expected when you set all the values to "undefined"

### ISSUE THREAD

**Issue by Binsk** [YoYoGames/GameMaker-Bugs#8110]
### Description

Nested arrays don't seem to be freeing at all; whether done manually or automatically at the end of a script.

Bug package: https://api.gamemaker.io/api/github/downloads/9476f027-90ee-497f-9c7f-7adfbd7755f1

Note: I noticed this on Linux, however after testing it on Windows 10 I saw the same issue occurring on both the VM and YYC.

### Expected Change

Nested arrays should free when out-of-scope or when the top-most array is set to something new.

### Steps To Reproduce

1. Create a function that generates an array with a size of 1,000,000
2. Loop over the array and fill each index with a new, unique array
3. At the end of the loop reset the original array to 'undefined'
4. Call the function numerous times (e.g., through a key-press)
5. Note that memory usage will continue to increase after each iteration

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which platform(s) are you seeing the problem on?

Ubuntu / Windows 10

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by yymrennie** [comment]
One thing to note is that if there are a large number of simultaneous allocations then a lot of memory will be reserved and this memory will stay reserved even when the resources that used it are then freed. However, when making new allocations, as long as the combined size of the allocations stays within the original peak memory usage then the originally reserved memory will be reused and no new allocations will be made. This means that the amount of memory reserved will level off at the peak usage but shouldn't grow from there.

There was a bug where the amount of used memory shown in the debug overlay was incorrect when the total amount of free memory exceeded a certain size - this has been fixed in 2024.11.

The garbage collector frees memory for arrays in phases and depending on the workload not all phases would be completed in a timely manner (the memory would be freed, but this would only happen when the garbage collector also had other work to do) - this has now been changed in 2024.11 so that all phases complete even if the garbage collector is otherwise idle.

Finally, a new mechanism has been added so that if you set an array variable (or a struct) to "undefined" (or if you use the "delete" keyword to indicate that the variable should be freed in the case of structs) then this will hint to the garbage collector that it should prioritise freeing the memory for that object's generation in the next collection cycle, which should result in the memory being freed more quickly then at present. Please note that this specifically relies on the variable being set to "undefined" (or delete being used), so the mechanism in the sample project "array = []" won't work but "array = undefined" will work. This change is also in 2024.11.

**Comment by sihammill** [comment]
Verified as per @yymrennie comment above on both Ubuntu and Windows 11 in IDE v2024.1100.0.675  Runtime v2024.1100.0.701
