### ISSUE TITLE
If more than two duplicate resources are polluted by git within .yyp, issues arise in code that uses the object asset id.

### ISSUE THREAD

**Issue by OnlookerRian** [YoYoGames/GameMaker-Bugs#8393]
### Description
This issue sometimes occurs during collaboration through git.

When opening the project, duplicate resources should be removed except for one.

A simple way to check if this issue is occurring is to look for warnings during the yyc build.

This problem was identified when code handling object assets produced different IDs for the same asset, and this was the cause.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.1.171 Runtime v2024.8.1.218

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[4df9c101-d708-4698-8885-231245344eed](https://api.gamemaker.io/api/github/downloads/4df9c101-d708-4698-8885-231245344eed)

**Comment by stuckie** [comment]
Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue to ensure we see exactly what you see and then learn why this problem is caused.

Technically, the serialiser should be warning you on multiple resources, so we really need a broken project in this manner to see why it did not warn you and what happened.

Please report this issue again, but ensure you have a suitable project open at the time you open the bug reporter and that you allow GameMaker to include the project.

Thanks!

[Why Have You Asked Me For A Sample?](https://help.gamemaker.io/hc/en-us/articles/13150754375453#h_01J15CZA1TP1FH04XQE2P18AAG)
