### ISSUE TITLE
CE2: "Analyzing Project" forever

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#8482]
### Description
Hello,
as soon as I activate CE2, GameMaker shows "Analyzing Project" in the top right corner, even when Feather is disabled.
This stays forever, I just restarted the session after like 1 hour of working with donut/hourglass cursor. It never finishes.

The project I am working in is not that large, it's about 50k lines of code in like 250-300 files, not more. Should only take a few seconds to analyze.
When I turn off CE2, no "analyzing project" appears, as expected, because feather is disabled.

 In the CE2 preferences I have deactivated "autofill jsdoc" so there should not be anything to analyze at all.

kind regards, 
Gris

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.686 Runtime v2024.1100.0.707

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[2f43872e-b045-44ac-bdf3-dfea0d7d2fd9](https://api.gamemaker.io/api/github/downloads/2f43872e-b045-44ac-bdf3-dfea0d7d2fd9)

**Comment by Grisgram** [comment]
Thanks for the comment,
It happens every time I start the IDE with this project, no change upon restart.

and no, in our company we make it 100% english, from comments to class names, everything - no special alphabet characters involved in any way.

**Comment by stuckie** [comment]
Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue to ensure we see exactly what you see and then learn why this problem is caused.

Please report this issue again, but ensure you have a suitable project open at the time you open the bug reporter and that you allow GameMaker to include the project.

Thanks!

[Why Have You Asked Me For A Sample?](https://help.gamemaker.io/hc/en-us/articles/13150754375453#h_01J15CZA1TP1FH04XQE2P18AAG)

**Comment by Grisgram** [comment]
My apologies, I was sure, I had it attached --> #8489 contains the project

**Comment by stuckie** [comment]
If we've detected it, it'll automatically add the project tag in the labels.
Or if you've added it as an additional file, there'll be an additional files area in the description with something in there ( as some users like to include it outwith the IDE for a variety of reasons. )

**Comment by Grisgram** [comment]
I'm only human after all :-) nevermind - the second has the label, all good!

**Comment by stuckie** [comment]
Yup, it happens... thanks!
