### ISSUE TITLE
Asset Browser: Unable to use arrow keys after after renaming an asset

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#861]
GM-7932

When renaming an asset in the asset browser, right after pressing "Enter", it is not possible to navigate to other assets using the arrow keys. 

*Steps to reproduce:*
- Open a project with 2 assets or more
- Select one asset in the asset browser
- Rename the asset (either use F2 or "Rename" in the RMB menu)
- Press "Enter" to complete the reaming
- Try to use the arrow keys to navigate to other assets
- Observe the issue

**Comment by rikman81** [comment]
This wasn't in the release notes and has had nobody assigned to it, but it appears to have been fixed in the latest Beta Release.

IDE: 2023.1100.0.425
Runtime: 2023.1100.0.439

It doesn't sound too bad, but it's a real workflow killer when trying to use a keyboard centric workflow- especially when first organising project assets but even just renaming assets sporadically whilst work is ongoing.

Thanks for the silent fix, much appreciated - hopefully it won't come back again!

**Comment by iampremo** [comment]
Fixed in https://github.com/YoYoGames/YoYoStudio/pull/8723

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2023.1100.0.448  Runtime v2023.1100.0.457, thanks.
