### ISSUE TITLE
Room Editor: Edge Detect filter preview is broken in 2024.1100

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#8628]
### Description

When previewing the Edge Detect filter in the Room Editor using the latest Betas, the filter will appear as a solid colour rather than showing the filter. 

This only occurs in the Room Editor and not in-game.

### 2024.1100

![Image](https://github.com/user-attachments/assets/0e59f715-5a8b-4e79-89fd-b62e7417833e)

### 2024.8

![Image](https://github.com/user-attachments/assets/311abbaa-e7b9-4d3b-a2c4-1c0321dbeb2e)

Tested using IDE v2024.1100.0.703  Runtime v2024.1100.0.719

[Sample Package](https://api.gamemaker.io/api/github/downloads/25616772-75ea-424f-b78e-e880047b65d5)

### Steps To Reproduce

1. Start GameMaker
2. Open one of the Template Projects (Such as Windy Woods)
3. Open a Room and add an Effects layer
4. Change the Effect Type to be "Edge Detect"
5. See the issue

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11, macOS Sequoia

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by JonnoRobson** [comment]
This issue came about due to a problem in the tool we use to generate shaders for the IDE. For now I've fixed the issue by rolling back the IDE version of the filter shader to a previous working version. The change that originally broke the shader on the IDE side was to resolve an issue with the filter on Android, so there should be no noticeable difference between the filter visuals in the IDE or runtime. As the IDE and runtime use different shader formats there should also be no regression in functionality of the filter on any runtime platforms. I'll also be looking into the problem with the shader tool itself to avoid these issues occurring in the future.

**Comment by SamTHodson** [comment]
Verified fixed in IDE v2024.1100.0.708  Runtime v2024.1100.0.725
