### ISSUE TITLE
Install: [Mac IDE] macOS Monterey (and older) cannot start 2024.1100 Beta IDEs 708-712

### ISSUE THREAD

**Issue by alicemoretti** [YoYoGames/GameMaker-Bugs#8669]
### Description

On macOS Monterey 12.7.6, when trying to install IDE v2024.1100.0.708  Runtime v2024.1100.0.725, once the install is finished the IDE does not launch and the system reports the following error: 

``` You can't use this version of the application "GameMaker Beta" with this version of macOS.  You have macOS 12.7.6. This application requires macOS 13.0 or later. ```

Please note that IDE v2024.1100.0.703  Runtime v2024.1100.0.719 (public Beta) installs and launches correctly. 

### Steps To Reproduce

1. Download GM's 708 installer on macOS 12.7.6 
2. Install the build
3. Launch the build 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

IDE v2024.1100.0.708  Runtime v2024.1100.0.725 

### Which operating system(s) are you seeing the problem on?

macOS Monterey

### Are you running GameMaker from inside your Steam library?

None

**Comment by YYDan** [comment]
Unfortunately, this was not able to be fixed for all tools GameMaker uses, and so we reverted the change above, so now your Mac will simply tell you that GameMaker cannot start on your old macOS version.

If your Mac is eligible to update its OS install, please do so. Otherwise, remain using 2024.8 on that Mac, as 2024.11 and future versions will not be supported.
