### ISSUE TITLE
Feather Autocomplete broken

### ISSUE THREAD

**Issue by AweJosh** [YoYoGames/GameMaker-Bugs#8774]
### Description

The latest release has broken feather autocomplete. It now seems to miss assets off autocomplete, completely. This is in CE1 AND CE2. I've noticed if you restart gamemaker, the asset is then added to feather. This doesn't always seem to happen, but most times.

Attached video of this happening

### Steps To Reproduce

https://github.com/user-attachments/assets/e9edc019-65e8-4b41-a2fd-016de9645c5d
1. Start GameMaker
2. Make asset
3. Type asset in code editor
4. See the issue

### How reliably can you recreate this issue using your steps above?

Most Times

### Which version of GameMaker are you reporting this issue for?

2024.11.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue to ensure we see exactly what you see and then learn why this problem is caused.

Please report this issue again, but ensure you have a suitable project open at the time you open the bug reporter and that you allow GameMaker to include the project.

Thanks!

[Why Have You Asked Me For A Sample?](https://help.gamemaker.io/hc/en-us/articles/13150754375453#h_01J15CZA1TP1FH04XQE2P18AAG)

**Comment by AweJosh** [comment]
Hi. **This is a bug with the latest IDE**, not my project. You shouldn't be making folks jump through unnecessary hoops to report issues with **_your_** software. I took time to post a video demonstrating the issue, that should definitely be enough. Disregarding this bug report because i didn't send you my project is just stupid of you to do.

Here is another video of this issue occurring in a **BLANK PROJECT** (not my project). Your "add files" link is busted, so i had to take further time to upload this to youtube so you could see it:

https://www.youtube.com/watch?v=4HDWZbguiX4&ab_channel=JoshSullivan

**Comment by attic-stuff** [comment]
this is an issue you that **you** are having, which is why the need to see if there is something about what **you** are doing that is causing it. they need a project for that. perhaps its the number of assets causing the problem, perhaps a project setting. it could be any number of things. here, for example, is autocomplete working for me in 2024.11 using both ce1, ce2, and ce1 in a fresh project:

https://github.com/user-attachments/assets/ffeb1ea3-3666-49ef-bb61-5fd70f11c61a

https://github.com/user-attachments/assets/9d23fca7-1b2b-45f3-bbe4-dcb8d45f6593

https://github.com/user-attachments/assets/960b5f8e-368a-4568-90c9-4f7383b5a870

do you expect them to recreate your entire project from nothing to find out what the deal is? and why do you think calling them stupid will somehow get you the results you want? did you click the link explaining why they need projects to more easily and quickly solve these mysteries?

**Comment by AweJosh** [comment]
Hi, firstly attic-stuff thank you for taking the time to look into this for yourself!

Now let me address some of the things you have said:

_"this is an issue you that you are having that others may not be having, which is why the need to see if there is something about what you are doing that is causing it. "_
This is an IDE issue, its nothing to do with my project (see my second post with the blank project).

I did say this issue is not always repeatable, in the second video i posted ([here](https://www.youtube.com/watch?v=4HDWZbguiX4&ab_channel=JoshSullivan)) **_you can see that the issue didn't occur at first._** 

_"do you expect them to recreate your entire project from nothing to find out what the deal is?"_
No sir, **this isn't an issue with my project**, its a bug with the IDE. Again let me point you to my second post where i re-create the issue in a blank project. 

_"and why do you think calling them stupid will somehow get you the results you want?"_
I did NOT call anybody stupid, i said the action taken by the individual staff member was stupid (i will elaborate on why i feel so strongly about this below), please re-read what i wrote in my above post. There is a large margin of difference between calling someone stupid, and saying something somebody did is stupid. Although my language is harsh; I did not call anybody stupid.

I appreciate your defensive to my post as from first glance I would probably be quite reactionary too at first glance too. I apologise that i have come across as sounding quite rude, but i do feel very strongly about this. And now let me elaborate as to why this is:


**Why I am upset about how YYG handled this issue:**

I just want to say first that i am writing the following with good intentions:
It is not my job to find bugs for GameMaker. If anybody not on staff do this, it's because they want to further improve the product and help GameMaker. Yes - i completely understand the logic behind why they ask for projects to "more easily and quickly solve these mysteries" but please let me be frank here: That isn't my problem. As the end user of this product; I shouldn't have to send you my entire project to report a bug with the GameMaker program itself (this bug isn't even anything to do with my project, i cant stress this enough - its a bug with the IDE that was introduced in the update this week.) - this is just stupid. The bug report was instantly rejected because i hadn't uploaded my project, which is just ludicrous - i am helping you find valid issues in your game engine YYG. It's just foolishness. If i wanted people (who have paid money to buy my software) to help me by reporting bugs they find, i would make that process as simple as possible as they are doing me a favour. Now that i've learned this process of informing YYG that there is an issue with their software requires me to upload my entire project (which isn't owned by me its owned by my company) i am very unlikely to report any issues again. And this is not me being immature about the situation, i just don't want to go through this silly process again.

So i hope some of what i've said has made sense to whoever reads this. Again, i just want to state i didn't call anybody stupid because that is just uncalled for.

**Comment by attic-stuff** [comment]
- there are secure ways of sending in commercial projects
- you can send in a blank project where you recreated the bug
- you can also send in other diagnostics (the help package mentioned when submitting the issue) that include things that help out.

for example, you have this bug, i do not. something about your ide might be different about my ide, and viewing the ui.log file is where they could see what the differences are. but if you dont wanna submit a project or the other diagnostics, and yyg never gets the same bug as you, how do you expect them to find it?

its not really a big deal if you dont have the time to and/or dont want to deal with including the project and diagnostics but its not realistically possible for yyg to try every permutation of ide settings and situations until they find the bug. so you are at an impasse; there is no stupid decision or people.

likewise: if you sell your game and people have a bug, but all they say is "hey i have a bug" and show you a video of it, you will not have the time to meticulously guess how they got that bug. but the more information they give you, the more likely you are to solve the bug. knowing the system spec, knowing if they altered their save file or if it became corrupt (hello diagnostics!), knowing if their gpu is on fire, knowing if they pressed a magic debug button you forgot to take out, or knowing any number of things always contributes to help.

any bug or qa team asking for diagnostics is just them asking for a _little_ bit of help so that they can better help you.
