### ISSUE TITLE
Sound Editor: GameMaker doesn't play an audio file from Audacity

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#880]
GM-7592

Cropped this file from longer sound in Audacity and exported as MP3. Dragged into GM and GM doesn't play it. Windows media player plays it fine

**Comment by toby-yoyo** [comment]
This was quite an extreme case - the affected file was an extremely short mp3 which seemed to be almost entirely nullified by a filter used when converting assets for playback within the IDE. The filter has been tweaked to reduce the changes made when converting the file and that seems to have resolved the issue here.

Note that part of the solution here was avoiding resampling as part of the filter chain - this is now done post-filtering. However, this is something that is incompatible with ffmpeg-4.x, and so users of the Linux IDE on Ubuntu 22.04 should be aware of the need to update their ffmpeg to at least v6.x. A guide for this can be found [here](https://help.gamemaker.io/hc/en-us/articles/20724217655453-Ubuntu-IDE-Updating-FFmpeg-to-the-latest-version-if-you-re-using-Ubuntu-22-04-LTS).

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.1300.0.714  Runtime v2024.1300.0.727.
