### ISSUE TITLE
Licensing: Logged-out users who are offline cannot proceed past Splash Screen without an error dialog they have to go online to fix

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#934]
GM-6984

If a user is logged out then starts the IDE but is also offline at the time, they cannot proceed past the Splash. When the Splash starts there is a check for RSS feeds. This check fails and brings up a modal saying it cannot access the API and only offers an ok button. The user cannot get around this

Steps
- open the browser and log out
- close the IDE
- go offline, i was on wifi only and disconnected from my network
- re-start the ide
- notice the alert and that the user cannot get past unless they go online again and press ok
 !screenshot-1.png|thumbnail!

**Comment by YYDan** [comment]
Super-old version and very little info here, so just closing. Licensing and being able to use the IDE whilst logged-out has changed massively since this issue was reported also, so I don't think this is valid/possible now anyway.

If still an issue in current/future releases, we should re-report using the current bug report standards, etc.
